import type { WordCard } from "../types";
import { fromTable, type Entry } from "./gen";

// Bible: the hard 3-point answer is a famous Bible term, place, or character
// pairing, kept to 2-3 words and a real, widely-recognized phrase (Rules 3-4)
// — no verbatim long-form quotes. The easy 1-point word is a word taken
// *from* that phrase, so it satisfies containment (Rule 2) — mirrors the
// Movies set's approach for named/titled content. Some anchors carry a small
// variety pool of phrases (Rule 1), e.g. Mount → Mount Sinai / Mount Zion.
const TABLE: Entry[] = [
  ["Ark", ["Noah's Ark"]],
  ["Calf", ["Golden Calf", "Fatted Calf"]],
  ["Eve", ["Adam And Eve"]],
  ["Goliath", ["David And Goliath"]],
  ["David", ["King David", "City Of David"]],
  ["Solomon", ["King Solomon", "Solomon's Temple", "Wisdom Of Solomon"]],
  ["Eden", ["Garden Of Eden"]],
  ["Babel", ["Tower Of Babel"]],
  ["Commandments", ["Ten Commandments"]],
  ["Samaritan", ["Good Samaritan"]],
  ["Mount", ["Mount Sinai", "Mount Zion", "Mount Of Olives"]],
  ["Supper", ["The Last Supper", "Lord's Supper"]],
  ["Judas", ["Judas Iscariot"]],
  ["Christ", ["Jesus Christ"]],
  ["John", ["John The Baptist", "Gospel Of John"]],
  ["Abel", ["Cain And Abel"]],
  ["Rib", ["Adam's Rib"]],
  ["Fruit", ["Forbidden Fruit"]],
  ["Loaves", ["Loaves And Fishes"]],
  ["Sea", ["Red Sea", "Sea Of Galilee", "Dead Sea"]],
  ["Star", ["Star Of Bethlehem", "Star Of David"]],
  ["Men", ["Three Wise Men"]],
  ["Son", ["Prodigal Son", "Son Of God", "Son Of Man"]],
  ["Shepherd", ["Good Shepherd"]],
  ["Land", ["Promised Land", "Holy Land"]],
  ["Salt", ["Pillar Of Salt"]],
  ["Queen", ["Queen Of Sheba"]],
  ["Bush", ["Burning Bush"]],
  ["Samson", ["Samson And Delilah"]],
  ["Mary", ["Virgin Mary", "Mary Magdalene", "Mary And Martha"]],
  ["Isaac", ["Abraham And Isaac"]],
  ["Jacob", ["Jacob's Ladder"]],
  ["Esau", ["Jacob And Esau"]],
  ["Joseph", ["Joseph's Coat", "Joseph And Mary"]],
  ["Esther", ["Queen Esther"]],
  ["Job", ["Patience Of Job", "Book Of Job"]],
  ["Lion", ["Lion's Den"]],
  ["Peter", ["Simon Peter"]],
  ["Paul", ["Saint Paul"]],
  ["Damascus", ["Road To Damascus"]],
  ["Thomas", ["Doubting Thomas"]],
  ["Matthew", ["Gospel Of Matthew"]],
  ["Mark", ["Gospel Of Mark"]],
  ["Luke", ["Gospel Of Luke"]],
  ["Lazarus", ["Lazarus Effect"]],
  ["Cross", ["Holy Cross"]],
  ["Crown", ["Crown Of Thorns"]],
  ["Wine", ["Water Into Wine", "Bread And Wine"]],
  ["Water", ["Walking On Water", "Holy Water"]],
  ["Bread", ["Bread Of Life", "Unleavened Bread", "Daily Bread"]],
  ["Egypt", ["Plagues Of Egypt"]],
  ["Plagues", ["Ten Plagues"]],
  ["Plague", ["Plague Of Locusts", "Plague Of Frogs", "Plague Of Darkness"]],
  ["Moses", ["Moses Basket"]],
  ["Angel", ["Guardian Angel", "Fallen Angel"]],
  ["Gabriel", ["Angel Gabriel"]],
  ["Trinity", ["Holy Trinity"]],
  ["Spirit", ["Holy Spirit"]],
  ["Ghost", ["Holy Ghost"]],
  ["Sins", ["Seven Deadly Sins"]],
  ["Apostles", ["Twelve Apostles"]],
  ["Disciples", ["Twelve Disciples"]],
  ["Sabbath", ["Sabbath Day"]],
  ["Jordan", ["River Jordan"]],
  ["Jerusalem", ["New Jerusalem"]],
  ["Nazareth", ["Jesus Of Nazareth"]],
  ["Jericho", ["Walls Of Jericho"]],
  ["Calvary", ["Mount Calvary"]],
  ["Sodom", ["Sodom And Gomorrah"]],
  ["Canaan", ["Land Of Canaan"]],
  ["Cain", ["Mark Of Cain"]],
  ["Flood", ["Great Flood"]],
  ["Sarah", ["Abraham And Sarah"]],
  ["Tribes", ["Twelve Tribes"]],
  ["Israel", ["Children Of Israel"]],
  ["Ruth", ["Book Of Ruth"]],
  ["Jesus", ["Baby Jesus"]],
  ["Kings", ["King Of Kings"]],
  ["Lamb", ["Lamb Of God", "Passover Lamb", "Sacrificial Lamb"]],
  ["Peace", ["Prince Of Peace"]],
  ["Alpha", ["Alpha And Omega"]],
  ["Herod", ["King Herod"]],
  ["Pilate", ["Pontius Pilate"]],
  ["Friday", ["Good Friday"]],
  ["Sunday", ["Easter Sunday", "Palm Sunday"]],
  ["Tomb", ["Empty Tomb"]],
  ["Gethsemane", ["Garden Of Gethsemane"]],
  ["Kiss", ["Judas Kiss"]],
  ["Silver", ["Pieces Of Silver"]],
  ["Revelation", ["Book Of Revelation"]],
  ["Horsemen", ["Four Horsemen"]],
  ["Armageddon", ["Battle Of Armageddon"]],
  ["Communion", ["Holy Communion"]],
  ["Bible", ["Holy Bible"]],
  ["City", ["Holy City"]],
  ["Week", ["Holy Week"]],
  ["Matrimony", ["Holy Matrimony"]],
  ["Tree", ["Tree Of Life", "Tree Of Knowledge", "Fig Tree"]],
  ["Fishers", ["Fishers Of Men"]],
  ["Seed", ["Mustard Seed"]],
  ["Sheep", ["Lost Sheep"]],
  ["Coin", ["Lost Coin"]],
  ["Ararat", ["Mount Ararat"]],
  ["Prayer", ["Lord's Prayer", "House Of Prayer"]],
  ["Exodus", ["Book Of Exodus"]],
  ["Genesis", ["Book Of Genesis"]],
  ["Psalms", ["Book Of Psalms"]],
  ["Proverbs", ["Book Of Proverbs"]],
  ["Rule", ["Golden Rule"]],
  ["Neighbor", ["Love Thy Neighbor"]],
  ["Gates", ["Pearly Gates"]],
  ["Streets", ["Streets Of Gold"]],
  ["Judgment", ["Judgment Day"]],
  ["Times", ["End Times"]],
  ["Coming", ["Second Coming"]],
  ["Saul", ["King Saul"]],
  ["Bathsheba", ["David And Bathsheba"]],
  ["Furnace", ["Fiery Furnace"]],
  ["Pentecost", ["Day Of Pentecost"]],
  ["Tongues", ["Speaking In Tongues"]],
  ["Birth", ["Virgin Birth"]],
  ["Offering", ["Burnt Offering"]],
  ["Atonement", ["Day Of Atonement"]],
  ["Priest", ["High Priest"]],
  ["God", ["Living God"]],
  ["Word", ["Word Of God"]],
  ["Kingdom", ["Kingdom Of God", "Kingdom Of Heaven"]],
  ["Brimstone", ["Fire And Brimstone"]],
  ["Fire", ["Lake Of Fire", "Pillar Of Fire", "Baptism Of Fire"]],
  ["Cloud", ["Pillar Of Cloud"]],
  ["Life", ["Eternal Life", "Book Of Life"]],
  ["Branch", ["Olive Branch"]],
  ["Cornerstone", ["Chief Cornerstone"]],
  ["Silas", ["Paul And Silas"]],
  ["Donkey", ["Balaam's Donkey"]],
  ["Honey", ["Milk And Honey"]],
  ["Pastures", ["Green Pastures"]],
  ["Waters", ["Still Waters"]],
  ["Feast", ["Wedding Feast"]],
  ["Body", ["Body Of Christ"]],
  ["Blood", ["Blood Of Christ"]],
  ["House", ["House Of God"]],
  ["Days", ["Forty Days", "Six Days"]],
  ["Years", ["Forty Years"]],
  ["Seals", ["Seven Seals"]],
  ["Testament", ["New Testament", "Old Testament"]],
  ["Scripture", ["Holy Scripture"]],
  ["Book", ["Good Book"]],
  ["Wall", ["Wailing Wall"]],
  ["Chaff", ["Wheat And Chaff"]],
  ["Prophet", ["False Prophet"]],
  ["Scrolls", ["Dead Sea Scrolls"]],
  ["Tablets", ["Stone Tablets"]],
  ["Man", ["Man Of God"]],
  ["Bride", ["Bride Of Christ"]],
  ["Day", ["Lord's Day", "Seventh Day"]],
  ["Risen", ["He Is Risen"]],
  ["Darkness", ["Prince Of Darkness"]],
  ["Rest", ["Day Of Rest"]],
  ["Thieves", ["Den Of Thieves"]],
  ["Leaf", ["Fig Leaf"]],
  ["Voice", ["Voice Of God"]],
];

export const BIBLE_CARDS: WordCard[] = fromTable(TABLE);
