import type { WordCard } from "../types";
import { fromTable, type Entry } from "./gen";

// The default "Standard" deck. Built from a curated table of base words, each
// paired with genuinely common compounds/phrases that contain it. The base is
// the easy 1-point word; each phrase is the harder 3-point answer.
//
// Quality bar (see docs/word-set-guidelines.md): cut anything even ~10% a
// stretch — no jargon, niche, archaic or awkwardly-split entries. Rule 5: the
// hard phrase must read as two distinct, real words — no fake splits of a
// single word ("Yester Day", "Net Work", "Cup Board", "Uni Corn"). Easy words
// may repeat; only the hard phrase must be unique (dedupe drops repeats). The
// set is kept intentionally tight (~1000) — quality dips when it grows past that.

const TABLE: Entry[] = [
  ["Fire", ["Camp Fire", "Fire Fly", "Fire Truck", "Fire Wood", "Fire Place", "Fire Works", "Fire Man", "Fire Ball", "Wild Fire", "Fire Engine"]],
  ["Water", ["Water Fall", "Water Melon", "Under Water", "Salt Water", "Water Slide", "Rain Water", "Water Gun", "Fresh Water"]],
  ["Sun", ["Sun Shine", "Sun Flower", "Sun Burn", "Sun Set", "Sun Rise", "Sun Glasses", "Sun Screen", "Sun Tan"]],
  ["Moon", ["Full Moon", "Moon Light", "Moon Walk", "Half Moon", "Honey Moon"]],
  ["Star", ["Movie Star", "Star Fish", "Shooting Star", "Rock Star", "North Star", "Super Star", "Pop Star"]],
  ["Rain", ["Rain Bow", "Rain Coat", "Rain Drop", "Rain Forest", "Rain Fall", "Rain Storm"]],
  ["Snow", ["Snow Man", "Snow Ball", "Snow Flake", "Snow Storm", "Snow Board", "Snow Angel"]],
  ["Wind", ["Wind Mill", "Wind Screen", "Wind Surf", "Wind Chime", "Wind Shield"]],
  ["Sea", ["Sea Shell", "Sea Weed", "Sea Horse", "Sea Food", "Sea Shore", "Sea Gull", "Sea Lion"]],
  ["Fish", ["Gold Fish", "Jelly Fish", "Cat Fish", "Sword Fish", "Fish Hook", "Fish Tank", "Fish Bowl"]],
  ["Bird", ["Bird Bath", "Black Bird", "Bird House", "Bird Cage", "Song Bird", "Bird Nest"]],
  ["Cat", ["Copy Cat", "Wild Cat", "Cat Nap", "Cat Walk", "Tom Cat"]],
  ["Dog", ["Hot Dog", "Bull Dog", "Dog House", "Sheep Dog", "Watch Dog", "Guard Dog"]],
  ["Cow", ["Cow Boy", "Cow Girl", "Cow Bell", "Cow Hide"]],
  ["Pig", ["Guinea Pig", "Pig Pen", "Pig Tail", "Pig Sty"]],
  ["Sheep", ["Sheep Dog", "Sheep Skin", "Black Sheep"]],
  ["Snake", ["Rattle Snake", "Snake Skin", "Snake Bite", "Snake Pit"]],
  ["Bear", ["Teddy Bear", "Polar Bear", "Bear Hug", "Grizzly Bear", "Bear Trap", "Brown Bear"]],
  ["Bee", ["Bumble Bee", "Bee Hive", "Spelling Bee", "Queen Bee", "Honey Bee", "Bee Sting"]],
  ["Ant", ["Fire Ant", "Ant Hill", "Ant Eater", "Army Ant"]],
  ["Fly", ["Butter Fly", "Dragon Fly", "Fire Fly", "Horse Fly", "Fruit Fly", "House Fly"]],
  ["Frog", ["Bull Frog", "Tree Frog", "Leap Frog"]],
  ["Duck", ["Rubber Duck", "Duck Pond", "Sitting Duck"]],
  ["Worm", ["Earth Worm", "Silk Worm", "Book Worm", "Glow Worm", "Tape Worm"]],
  ["Book", ["Note Book", "Text Book", "Book Shelf", "Book Mark", "Cook Book", "Comic Book"]],
  ["Foot", ["Foot Ball", "Foot Print", "Foot Path", "Foot Step", "Bare Foot", "Big Foot"]],
  ["Hand", ["Hand Shake", "Hand Bag", "Hand Cuff", "Hand Ball", "Hand Made", "Hand Stand"]],
  ["Eye", ["Eye Ball", "Eye Brow", "Eye Lash", "Eye Lid", "Black Eye", "Eagle Eye"]],
  ["Head", ["Head Ache", "Fore Head", "Head Light", "Head Line", "Head Phone", "Egg Head"]],
  ["Hair", ["Hair Cut", "Hair Brush", "Hair Pin", "Hair Style", "Hair Band", "Hair Spray"]],
  ["Tooth", ["Sweet Tooth", "Tooth Brush", "Tooth Paste", "Tooth Ache", "Tooth Pick"]],
  ["Nose", ["Runny Nose", "Nose Dive", "Nose Bleed", "Nose Ring"]],
  ["Ear", ["Ear Ring", "Ear Drum", "Ear Ache", "Ear Wax", "Ear Phone", "Ear Muff"]],
  ["Face", ["Face Paint", "Face Lift", "Poker Face", "Baby Face", "Face Off", "Face Mask"]],
  ["Heart", ["Broken Heart", "Heart Beat", "Sweet Heart", "Heart Burn", "Heart Break", "Heart Attack"]],
  ["Ball", ["Beach Ball", "Base Ball", "Basket Ball", "Snow Ball", "Meat Ball", "Golf Ball", "Pin Ball", "Cannon Ball"]],
  ["Box", ["Music Box", "Mail Box", "Match Box", "Sand Box", "Tool Box", "Lunch Box"]],
  ["Bell", ["Door Bell", "Dumb Bell", "Cow Bell", "Jingle Bell", "Bell Pepper", "Blue Bell"]],
  ["Bath", ["Bird Bath", "Bath Room", "Bath Tub", "Bubble Bath", "Blood Bath", "Bath Robe"]],
  ["Bed", ["Bed Room", "Flower Bed", "Bed Time", "Bunk Bed", "Bed Bug", "Water Bed"]],
  ["Door", ["Trap Door", "Door Bell", "Door Way", "Door Step", "Door Knob", "Back Door"]],
  ["Clock", ["Alarm Clock", "Clock Work", "Clock Wise", "Cuckoo Clock", "Clock Tower"]],
  ["Wheel", ["Wheel Chair", "Ferris Wheel", "Water Wheel", "Steering Wheel", "Wheel Barrow", "Cart Wheel"]],
  ["Chair", ["Wheel Chair", "Arm Chair", "High Chair", "Deck Chair", "Rocking Chair", "Beach Chair"]],
  ["Table", ["Time Table", "Table Cloth", "Turn Table", "Pool Table", "Table Spoon", "Coffee Table"]],
  ["Bread", ["Ginger Bread", "Bread Crumb", "Corn Bread", "White Bread", "Bread Stick", "Banana Bread"]],
  ["Egg", ["Egg Roll", "Egg Plant", "Egg Shell", "Egg Cup", "Scotch Egg", "Egg White"]],
  ["Milk", ["Milk Shake", "Milk Man", "Butter Milk", "Milk Maid", "Coconut Milk", "Milk Bar"]],
  ["Corn", ["Pop Corn", "Corn Bread", "Corn Field", "Sweet Corn", "Corn Flake", "Corn Dog"]],
  ["Cake", ["Cup Cake", "Pan Cake", "Cheese Cake", "Fish Cake", "Carrot Cake", "Birthday Cake", "Wedding Cake"]],
  ["Pie", ["Meat Pie", "Apple Pie", "Pork Pie", "Pie Chart", "Pumpkin Pie", "Cherry Pie"]],
  ["Cream", ["Ice Cream", "Sun Cream", "Cream Cheese", "Sour Cream", "Whipped Cream", "Shaving Cream"]],
  ["Cup", ["Cup Cake", "Tea Cup", "Egg Cup", "Butter Cup", "World Cup"]],
  ["Pot", ["Jack Pot", "Tea Pot", "Flower Pot", "Pot Hole", "Hot Pot", "Honey Pot"]],
  ["Pan", ["Frying Pan", "Pan Cake", "Sauce Pan", "Dust Pan", "Pan Handle"]],
  ["Plate", ["License Plate", "Home Plate", "Hot Plate", "Number Plate"]],
  ["Knife", ["Pocket Knife", "Butter Knife", "Jack Knife", "Bread Knife", "Steak Knife"]],
  ["Spoon", ["Wooden Spoon", "Tea Spoon", "Table Spoon", "Spoon Feed", "Soup Spoon"]],
  ["Fork", ["Tuning Fork", "Pitch Fork", "Fork Lift", "Salad Fork"]],
  ["Salt", ["Salt Shaker", "Sea Salt", "Salt Water", "Rock Salt", "Table Salt"]],
  ["Bean", ["Jelly Bean", "Bean Bag", "String Bean", "Coffee Bean", "Bean Stalk", "Green Bean"]],
  ["Rock", ["Rock Band", "Rock Star", "Bed Rock", "Rock Salt", "Rock Garden", "Rock Bottom"]],
  ["Tree", ["Family Tree", "Tree House", "Palm Tree", "Pine Tree", "Apple Tree", "Christmas Tree"]],
  ["Wood", ["Fire Wood", "Wood Pecker", "Ply Wood", "Drift Wood", "Red Wood", "Hard Wood"]],
  ["Leaf", ["Tea Leaf", "Fig Leaf", "Bay Leaf", "Gold Leaf", "Maple Leaf"]],
  ["Grass", ["Grass Hopper", "Grass Land", "Lemon Grass", "Grass Snake", "Blue Grass"]],
  ["Flower", ["Sun Flower", "Flower Pot", "Wild Flower", "Flower Bed", "May Flower", "Flower Girl"]],
  ["Field", ["Corn Field", "Battle Field", "Field Trip", "Oil Field", "Field Day", "Field Goal"]],
  ["Hill", ["Ant Hill", "Down Hill", "Up Hill", "Hill Side", "Hill Top"]],
  ["Stone", ["Grave Stone", "Mile Stone", "Corner Stone", "Stone Wall", "Lime Stone", "Stepping Stone"]],
  ["Sand", ["Sand Castle", "Sand Box", "Sand Paper", "Quick Sand", "Sand Bag", "Sand Storm"]],
  ["Ice", ["Ice Cream", "Ice Berg", "Ice Cube", "Ice Box", "Ice Skate", "Ice Rink"]],
  ["Cloud", ["Rain Cloud", "Storm Cloud", "Cloud Nine", "Mushroom Cloud", "Thunder Cloud"]],
  ["Storm", ["Thunder Storm", "Snow Storm", "Sand Storm", "Brain Storm", "Rain Storm", "Dust Storm"]],
  ["Light", ["Sun Light", "Moon Light", "Flash Light", "Day Light", "Spot Light", "Traffic Light", "Head Light", "Light House"]],
  ["House", ["Tree House", "Dog House", "Light House", "Green House", "House Boat", "White House", "Bird House", "Farm House"]],
  ["Room", ["Bed Room", "Bath Room", "Class Room", "Living Room", "Ball Room", "Court Room", "Rest Room"]],
  ["Yard", ["Back Yard", "Court Yard", "Grave Yard", "Junk Yard", "Barn Yard", "Farm Yard"]],
  ["Way", ["High Way", "Drive Way", "Rail Way", "Run Way", "Path Way", "Sub Way", "Hall Way"]],
  ["Side", ["Sea Side", "Country Side", "Road Side", "Bed Side", "Out Side", "In Side", "Hill Side"]],
  ["Line", ["Head Line", "Base Line", "Coast Line", "Dead Line", "Life Line", "Out Line", "Punch Line", "Finish Line"]],
  ["Time", ["Bed Time", "Day Time", "Night Time", "Life Time", "Over Time", "Play Time", "Half Time", "Time Machine"]],
  ["Work", ["Home Work", "Art Work", "Team Work", "Frame Work", "Fire Work", "Wood Work"]],
  ["Ground", ["Play Ground", "Back Ground", "Under Ground", "Camp Ground", "Battle Ground", "Fair Ground"]],
  ["Paper", ["News Paper", "Sand Paper", "Wall Paper", "Paper Clip", "Paper Back", "Toilet Paper"]],
  ["Board", ["Key Board", "Surf Board", "Chalk Board", "Card Board", "Dash Board", "Skate Board", "Score Board", "White Board"]],
  ["Chip", ["Potato Chip", "Poker Chip", "Chocolate Chip", "Wood Chip", "Blue Chip"]],
  ["Coffee", ["Coffee Cup", "Coffee Bean", "Coffee Table", "Coffee Break", "Coffee Shop", "Coffee Mug"]],
  ["Tea", ["Tea Pot", "Tea Cup", "Tea Spoon", "Tea Bag", "Tea Time", "Green Tea", "Bubble Tea"]],
  ["Cheese", ["Cheese Cake", "Cheese Burger", "Cheese Board", "Blue Cheese", "Cream Cheese", "Grilled Cheese"]],
  ["Butter", ["Butter Fly", "Butter Cup", "Butter Milk", "Peanut Butter", "Butter Knife", "Butter Bean"]],
  ["Honey", ["Honey Bee", "Honey Comb", "Honey Moon", "Honey Pot", "Honey Dew", "Honey Bun"]],
  ["Sugar", ["Sugar Cane", "Sugar Cube", "Brown Sugar", "Sugar Rush", "Sugar Free", "Sugar Bowl"]],
  ["Apple", ["Apple Pie", "Apple Sauce", "Pine Apple", "Apple Tree", "Apple Juice", "Big Apple"]],
  ["Orange", ["Orange Juice", "Orange Peel", "Blood Orange", "Orange Tree"]],
  ["Berry", ["Straw Berry", "Blue Berry", "Black Berry", "Goose Berry", "Berry Bush"]],
  ["Grape", ["Grape Fruit", "Grape Vine", "Grape Juice", "Sour Grape"]],
  ["Lemon", ["Lemon Grass", "Lemon Tree", "Lemon Drop", "Lemon Peel", "Lemon Juice"]],
  ["Nut", ["Pea Nut", "Coco Nut", "Chest Nut", "Dough Nut", "Nut Shell"]],
  ["Meat", ["Meat Ball", "Meat Loaf", "Mince Meat", "Meat Pie", "Red Meat", "Lunch Meat"]],
  ["Beef", ["Beef Burger", "Corned Beef", "Beef Cake", "Beef Steak", "Ground Beef", "Roast Beef"]],
  ["Ham", ["Ham Burger", "Ham Bone", "Ham Steak"]],
  ["Pork", ["Pork Chop", "Pork Pie", "Pork Belly", "Roast Pork", "Pulled Pork"]],
  ["Chicken", ["Chicken Pox", "Chicken Wing", "Chicken Soup", "Fried Chicken", "Roast Chicken", "Chicken Coop"]],
  ["Rice", ["Fried Rice", "Rice Cake", "Rice Pudding", "Wild Rice", "Brown Rice", "Rice Bowl"]],
  ["Soup", ["Chicken Soup", "Soup Spoon", "Pea Soup", "Tomato Soup", "Soup Bowl"]],
  ["Salad", ["Fruit Salad", "Salad Bowl", "Salad Bar", "Potato Salad", "Caesar Salad"]],
  ["Bar", ["Chocolate Bar", "Candy Bar", "Crow Bar", "Sand Bar", "Space Bar", "Snack Bar", "Handle Bar"]],
  ["Juice", ["Orange Juice", "Apple Juice", "Fruit Juice", "Grape Juice", "Juice Box", "Lemon Juice"]],
  ["Bug", ["Lady Bug", "Bed Bug", "June Bug", "Bug Spray", "Love Bug"]],
  ["Spider", ["Spider Web", "Spider Man", "Spider Bite", "Spider Plant"]],
  ["Web", ["Spider Web", "Web Site", "Web Page", "Cob Web", "Web Cam"]],
  ["Net", ["Fish Net", "Hair Net", "Safety Net", "Net Ball"]],
  ["Bag", ["Hand Bag", "Tea Bag", "Sleeping Bag", "Bean Bag", "Sand Bag", "Air Bag", "Gift Bag"]],
  ["Belt", ["Seat Belt", "Green Belt", "Belt Buckle", "Tool Belt", "Conveyor Belt", "Black Belt"]],
  ["Boot", ["Boot Camp", "Rubber Boot", "Boot Lace", "Ski Boot", "Snow Boot"]],
  ["Shoe", ["Horse Shoe", "Snow Shoe", "Shoe Lace", "Shoe Box", "Shoe Horn", "Tennis Shoe"]],
  ["Sock", ["Wind Sock", "Ankle Sock", "Tube Sock", "Knee Sock"]],
  ["Hat", ["Top Hat", "Hard Hat", "Sun Hat", "Hat Trick", "Straw Hat", "Party Hat"]],
  ["Coat", ["Rain Coat", "Over Coat", "Trench Coat", "Coat Rack", "Coat Hanger", "Fur Coat"]],
  ["Glass", ["Hour Glass", "Eye Glass", "Wine Glass", "Magnifying Glass", "Stained Glass", "Shot Glass"]],
  ["Key", ["Key Board", "Key Ring", "Key Hole", "Key Chain", "Key Note", "Key Pad"]],
  ["Lock", ["Pad Lock", "Dead Lock", "Lock Smith", "Lock Down", "Lock Jaw"]],
  ["Chain", ["Key Chain", "Chain Saw", "Food Chain", "Daisy Chain", "Chain Mail", "Chain Link"]],
  ["Nail", ["Finger Nail", "Toe Nail", "Nail Polish", "Nail File", "Thumb Nail", "Nail Clipper"]],
  ["Pin", ["Safety Pin", "Push Pin", "Rolling Pin", "Bobby Pin", "Clothes Pin", "Pin Wheel"]],
  ["Pen", ["Play Pen", "Pig Pen", "Pen Knife", "Pen Pal", "Fountain Pen"]],
  ["Cap", ["Night Cap", "Knee Cap", "Ice Cap", "Bottle Cap", "Swim Cap"]],
  ["Cloth", ["Table Cloth", "Wash Cloth", "Face Cloth", "Dish Cloth", "Loin Cloth"]],
  ["Brush", ["Tooth Brush", "Hair Brush", "Paint Brush", "Nail Brush", "Bottle Brush", "Brush Fire"]],
  ["Comb", ["Honey Comb", "Comb Over"]],
  ["Soap", ["Soap Box", "Soap Opera", "Soap Dish", "Soap Suds", "Hand Soap", "Dish Soap"]],
  ["Towel", ["Bath Towel", "Beach Towel", "Tea Towel", "Paper Towel", "Hand Towel", "Dish Towel"]],
  ["Mat", ["Door Mat", "Bath Mat", "Place Mat", "Yoga Mat", "Welcome Mat", "Beer Mat"]],
  ["Rug", ["Bear Rug", "Area Rug", "Rug Rat", "Throw Rug"]],
  ["Lamp", ["Lamp Shade", "Lamp Post", "Desk Lamp", "Oil Lamp", "Lava Lamp", "Street Lamp"]],
  ["Candle", ["Candle Stick", "Candle Light", "Candle Wick", "Candle Wax", "Birthday Candle"]],
  ["Watch", ["Wrist Watch", "Watch Dog", "Watch Man", "Watch Tower", "Stop Watch", "Pocket Watch"]],
  ["Ring", ["Ear Ring", "Boxing Ring", "Key Ring", "Ring Master", "Wedding Ring", "Nose Ring", "Onion Ring"]],
  ["Card", ["Post Card", "Playing Card", "Score Card", "Flash Card", "Credit Card", "Report Card", "Birthday Card", "Wild Card"]],
  ["Game", ["Board Game", "Video Game", "Ball Game", "Card Game", "Game Show", "End Game", "Game Plan"]],
  ["Show", ["Talk Show", "Game Show", "Slide Show", "Show Down", "Show Off", "Show Case", "Puppet Show"]],
  ["Play", ["Play Ground", "Play Time", "Play House", "Play Pen", "Play Boy", "Word Play", "Role Play"]],
  ["Note", ["Note Book", "Note Pad", "Foot Note", "Bank Note", "Sticky Note"]],
  ["Pad", ["Note Pad", "Key Pad", "Launch Pad", "Lily Pad", "Mouse Pad", "Knee Pad"]],
  ["Mark", ["Book Mark", "Land Mark", "Bench Mark", "Trade Mark", "Birth Mark", "Question Mark"]],
  ["Print", ["Foot Print", "Finger Print", "Blue Print", "Paw Print", "Thumb Print", "Hand Print"]],
  ["Camp", ["Camp Fire", "Camp Site", "Camp Ground", "Boot Camp", "Base Camp", "Summer Camp"]],
  ["Trip", ["Road Trip", "Field Trip", "Trip Wire", "Day Trip", "Round Trip"]],
  ["Boat", ["Sail Boat", "Row Boat", "Speed Boat", "House Boat", "Tug Boat", "Life Boat", "Steam Boat"]],
  ["Ship", ["Space Ship", "Battle Ship", "Ship Yard", "Ship Wreck", "Ship Mate", "Flag Ship", "Cruise Ship"]],
  ["Car", ["Race Car", "Cable Car", "Box Car", "Car Wash", "Car Park", "Sports Car", "Car Seat", "Bumper Car"]],
  ["Truck", ["Fire Truck", "Dump Truck", "Monster Truck", "Tow Truck", "Food Truck", "Truck Stop"]],
  ["Train", ["Freight Train", "Train Track", "Steam Train", "Train Station", "Bullet Train", "Train Set"]],
  ["Plane", ["Air Plane", "Sea Plane", "War Plane", "Jet Plane", "Paper Plane"]],
  ["Bike", ["Motor Bike", "Mountain Bike", "Dirt Bike", "Bike Rack", "Bike Lane", "Bike Path"]],
  ["Road", ["Rail Road", "Cross Road", "Road Block", "Road Side", "Road Trip", "Road Map", "Road Sign", "Road Rage"]],
  ["Rail", ["Rail Road", "Rail Way", "Guard Rail", "Hand Rail", "Mono Rail"]],
  ["Bridge", ["Draw Bridge", "Foot Bridge", "Toll Bridge", "Rope Bridge"]],
  ["Station", ["Train Station", "Bus Station", "Gas Station", "Space Station", "Fire Station", "Police Station"]],
  ["Port", ["Air Port", "Sea Port", "Car Port", "Pass Port", "Port Hole"]],
  ["Park", ["Car Park", "Ball Park", "Theme Park", "National Park", "Park Bench", "Water Park"]],
  ["Garden", ["Rose Garden", "Garden Hose", "Beer Garden", "Garden Path", "Herb Garden", "Garden Shed"]],
  ["Farm", ["Farm House", "Farm Yard", "Farm Hand", "Wind Farm", "Dairy Farm", "Ant Farm"]],
  ["City", ["City Hall", "Inner City", "City Centre", "City Limits", "Capital City"]],
  ["Town", ["Down Town", "Home Town", "China Town", "Ghost Town", "Town Hall", "Town House"]],
  ["Street", ["Street Light", "Main Street", "Street Car", "Side Street", "Wall Street", "High Street"]],
  ["Wall", ["Fire Wall", "Wall Paper", "Stone Wall", "Wall Flower", "Brick Wall", "Great Wall"]],
  ["Roof", ["Roof Top", "Sun Roof", "Roof Rack", "Roof Tile", "Flat Roof"]],
  ["Floor", ["Ground Floor", "Floor Board", "Dance Floor", "Floor Plan", "Sea Floor", "Top Floor"]],
  ["Gate", ["Gate Way", "Gate Keeper", "Gate Post", "Flood Gate", "Toll Gate", "Golden Gate"]],
  ["Fence", ["Picket Fence", "Fence Post", "Electric Fence", "Garden Fence"]],
  ["Sky", ["Sky Line", "Sky Scraper", "Sky Light", "Sky Diver", "Sky Rocket", "Sky Blue", "Night Sky"]],
  ["Air", ["Air Port", "Air Plane", "Air Line", "Air Craft", "Air Bag", "Air Force", "Fresh Air", "Hot Air"]],
  ["Fog", ["Fog Horn", "Fog Light", "Fog Machine", "Brain Fog"]],
  ["Frost", ["Frost Bite", "Jack Frost", "Ground Frost"]],
  ["Dew", ["Dew Drop", "Honey Dew", "Morning Dew", "Dew Point"]],
  ["Wave", ["Tidal Wave", "Heat Wave", "Micro Wave", "Sound Wave", "Brain Wave", "Shock Wave"]],
  ["Tide", ["High Tide", "Low Tide", "Red Tide", "Rip Tide", "Tide Pool"]],
  ["Beach", ["Beach Ball", "Beach Chair", "Beach Towel", "Beach House", "Beach Front", "Sandy Beach"]],
  ["Gold", ["Gold Fish", "Gold Mine", "Gold Smith", "Gold Rush", "Gold Medal", "Gold Bar"]],
  ["Silver", ["Silver Ware", "Silver Fish", "Silver Smith", "Silver Screen", "Silver Medal"]],
  ["Iron", ["Cast Iron", "Iron Man", "Flat Iron", "Iron Fist", "Waffle Iron", "Steam Iron"]],
  ["Coal", ["Coal Mine", "Coal Field", "Char Coal", "Coal Face"]],
  ["Oil", ["Oil Field", "Oil Well", "Oil Rig", "Oil Paint", "Olive Oil", "Oil Spill"]],
  ["Gas", ["Gas Station", "Gas Mask", "Tear Gas", "Gas Pump", "Natural Gas", "Laughing Gas"]],
  ["Steam", ["Steam Boat", "Steam Ship", "Steam Roller", "Steam Engine", "Steam Train", "Steam Iron"]],
  ["Life", ["Life Boat", "Life Guard", "Wild Life", "Life Time", "Life Line", "Life Style", "Life Jacket"]],
  ["Home", ["Home Work", "Home Made", "Home Town", "Home Sick", "Home Land", "Home Run", "Home Page"]],
  ["School", ["High School", "School Boy", "School Girl", "School Bus", "School Yard", "Pre School", "Sunday School"]],
  ["Baby", ["Baby Sit", "Baby Boom", "Baby Food", "Baby Face", "Baby Shower", "Cry Baby"]],
  ["Blood", ["Blood Hound", "Blood Bath", "Blood Shot", "Blood Stream", "Blood Line", "Blood Bank"]],
  ["Night", ["Night Fall", "Night Gown", "Night Mare", "Night Owl", "Mid Night", "Over Night", "Night Club"]],
  ["Day", ["Day Dream", "Day Break", "Day Light", "Birth Day", "Pay Day", "Day Care", "Snow Day"]],
  ["Green", ["Green House", "Green Horn", "Ever Green", "Green Room", "Green Belt", "Green Thumb"]],
  ["Blue", ["Blue Bird", "Blue Berry", "Blue Print", "Blue Bell", "Navy Blue", "Sky Blue"]],
  ["Black", ["Black Bird", "Black Board", "Black Berry", "Black Out", "Black Smith", "Black Mail", "Black Belt"]],
  ["White", ["White Wash", "White Board", "Egg White", "White Out", "Snow White", "White House"]],
  ["Red", ["Red Head", "Red Wood", "Red Neck", "Red Coat", "Red Card", "Red Carpet"]],
  ["Under", ["Under Dog", "Under Wear", "Under Water", "Under Ground", "Under Cover"]],
  ["Over", ["Over Board", "Over Coat", "Over Head", "Over Pass", "Over Night"]],
  ["Out", ["Out Side", "Out Break", "Out Law", "Out Post", "Out Fit"]],
  ["Back", ["Back Bone", "Back Fire", "Back Ground", "Back Pack", "Back Yard", "Feed Back", "Come Back"]],
  ["Down", ["Down Fall", "Down Hill", "Down Load", "Down Pour", "Down Town", "Count Down"]],
  ["Up", ["Up Grade", "Up Hill", "Up Load", "Up Set", "Up Town", "Up Stairs"]],
  ["Cross", ["Cross Bow", "Cross Fire", "Cross Road", "Cross Walk", "Cross Word", "Cross Over"]],
];

export const EVERYDAY_CARDS: WordCard[] = fromTable(TABLE);
