import type { WordCard } from "../types";
import { fromTable, type Entry } from "./gen";

// The default "Standard" deck. Built from a curated table of base words, each
// paired with genuinely common compounds/phrases that contain it. The base is
// the easy 1-point word; each phrase is the harder 3-point answer.
//
// Quality bar (see docs/word-set-guidelines.md): cut anything even ~10% a
// stretch — no jargon, niche, archaic or awkwardly-split entries. Rule 5: the
// hard phrase must read as two distinct, real words — no fake splits of a
// single word ("Yester Day", "Net Work", "Cup Board", "Uni Corn"). Rule 6: the
// base word should be a noun — no "Over"/"Up" function words.
//
// Easy words may repeat; only the hard phrase must be unique (build() drops
// repeats). But per Rule 7 a game deals at most one card per base word, so the
// real size of this set is its count of *distinct base words* — grow that (add
// new noun anchors), not just the raw card count.

const TABLE: Entry[] = [
  ["Fire", ["Camp Fire", "Fire Fly", "Fire Truck", "Fire Wood", "Fire Place", "Fire Works", "Fire Man", "Fire Ball", "Wild Fire", "Fire Engine"]],
  ["Water", ["Water Fall", "Water Melon", "Under Water", "Salt Water", "Water Slide", "Rain Water", "Water Gun", "Fresh Water"]],
  ["Sun", ["Sun Shine", "Sun Flower", "Sun Burn", "Sun Set", "Sun Rise", "Sun Glasses", "Sun Screen", "Sun Tan"]],
  ["Moon", ["Full Moon", "Moon Light", "Moon Walk", "Half Moon", "Honey Moon"]],
  ["Star", ["Movie Star", "Star Fish", "Shooting Star", "Rock Star", "North Star", "Super Star", "Pop Star"]],
  ["Rain", ["Rain Bow", "Rain Coat", "Rain Drop", "Rain Forest", "Rain Fall", "Rain Storm"]],
  ["Snow", ["Snow Man", "Snow Ball", "Snow Flake", "Snow Storm", "Snow Board", "Snow Angel"]],
  ["Wind", ["Wind Mill", "Wind Screen", "Wind Surf", "Wind Chime", "Wind Shield"]],
  ["Sea", ["Sea Shell", "Sea Weed", "Sea Horse", "Sea Food", "Sea Shore", "Sea Gull", "Sea Lion"]],
  ["Fish", ["Gold Fish", "Jelly Fish", "Cat Fish", "Sword Fish", "Fish Hook", "Fish Tank", "Fish Bowl"]],
  ["Bird", ["Bird Bath", "Black Bird", "Bird House", "Bird Cage", "Song Bird", "Bird Nest"]],
  ["Cat", ["Copy Cat", "Wild Cat", "Cat Nap", "Cat Walk", "Tom Cat"]],
  ["Dog", ["Hot Dog", "Bull Dog", "Dog House", "Sheep Dog", "Watch Dog", "Guard Dog"]],
  ["Cow", ["Cow Boy", "Cow Girl", "Cow Bell", "Cow Hide"]],
  ["Pig", ["Guinea Pig", "Pig Pen", "Pig Tail", "Pig Sty"]],
  ["Sheep", ["Sheep Dog", "Sheep Skin", "Black Sheep"]],
  ["Snake", ["Rattle Snake", "Snake Skin", "Snake Bite", "Snake Pit"]],
  ["Bear", ["Teddy Bear", "Polar Bear", "Bear Hug", "Grizzly Bear", "Bear Trap", "Brown Bear"]],
  ["Bee", ["Bumble Bee", "Bee Hive", "Spelling Bee", "Queen Bee", "Honey Bee", "Bee Sting"]],
  ["Ant", ["Fire Ant", "Ant Hill", "Ant Eater", "Army Ant"]],
  ["Fly", ["Butter Fly", "Dragon Fly", "Fire Fly", "Horse Fly", "Fruit Fly", "House Fly"]],
  ["Frog", ["Bull Frog", "Tree Frog", "Leap Frog"]],
  ["Duck", ["Rubber Duck", "Duck Pond", "Sitting Duck"]],
  ["Worm", ["Earth Worm", "Silk Worm", "Book Worm", "Glow Worm", "Tape Worm"]],
  ["Book", ["Note Book", "Text Book", "Book Shelf", "Book Mark", "Cook Book", "Comic Book"]],
  ["Foot", ["Foot Ball", "Foot Print", "Foot Path", "Foot Step", "Bare Foot", "Big Foot"]],
  ["Hand", ["Hand Shake", "Hand Bag", "Hand Cuff", "Hand Ball", "Hand Made", "Hand Stand"]],
  ["Eye", ["Eye Ball", "Eye Brow", "Eye Lash", "Eye Lid", "Black Eye", "Eagle Eye"]],
  ["Head", ["Head Ache", "Fore Head", "Head Light", "Head Line", "Head Phone", "Egg Head"]],
  ["Hair", ["Hair Cut", "Hair Brush", "Hair Pin", "Hair Style", "Hair Band", "Hair Spray"]],
  ["Tooth", ["Sweet Tooth", "Tooth Brush", "Tooth Paste", "Tooth Ache", "Tooth Pick"]],
  ["Nose", ["Runny Nose", "Nose Dive", "Nose Bleed", "Nose Ring"]],
  ["Ear", ["Ear Ring", "Ear Drum", "Ear Ache", "Ear Wax", "Ear Phone", "Ear Muff"]],
  ["Face", ["Face Paint", "Face Lift", "Poker Face", "Baby Face", "Face Off", "Face Mask"]],
  ["Heart", ["Broken Heart", "Heart Beat", "Sweet Heart", "Heart Burn", "Heart Break", "Heart Attack"]],
  ["Ball", ["Beach Ball", "Base Ball", "Basket Ball", "Snow Ball", "Meat Ball", "Golf Ball", "Pin Ball", "Cannon Ball"]],
  ["Box", ["Music Box", "Mail Box", "Match Box", "Sand Box", "Tool Box", "Lunch Box"]],
  ["Bell", ["Door Bell", "Dumb Bell", "Cow Bell", "Jingle Bell", "Bell Pepper", "Blue Bell"]],
  ["Bath", ["Bird Bath", "Bath Room", "Bath Tub", "Bubble Bath", "Blood Bath", "Bath Robe"]],
  ["Bed", ["Bed Room", "Flower Bed", "Bed Time", "Bunk Bed", "Bed Bug", "Water Bed"]],
  ["Door", ["Trap Door", "Door Bell", "Door Way", "Door Step", "Door Knob", "Back Door"]],
  ["Clock", ["Alarm Clock", "Clock Work", "Clock Wise", "Cuckoo Clock", "Clock Tower"]],
  ["Wheel", ["Wheel Chair", "Ferris Wheel", "Water Wheel", "Steering Wheel", "Wheel Barrow", "Cart Wheel"]],
  ["Chair", ["Wheel Chair", "Arm Chair", "High Chair", "Deck Chair", "Rocking Chair", "Beach Chair"]],
  ["Table", ["Time Table", "Table Cloth", "Turn Table", "Pool Table", "Table Spoon", "Coffee Table"]],
  ["Bread", ["Ginger Bread", "Bread Crumb", "Corn Bread", "White Bread", "Bread Stick", "Banana Bread"]],
  ["Egg", ["Egg Roll", "Egg Plant", "Egg Shell", "Egg Cup", "Scotch Egg", "Egg White"]],
  ["Milk", ["Milk Shake", "Milk Man", "Butter Milk", "Milk Maid", "Coconut Milk", "Milk Bar"]],
  ["Corn", ["Pop Corn", "Corn Bread", "Corn Field", "Sweet Corn", "Corn Flake", "Corn Dog"]],
  ["Cake", ["Cup Cake", "Pan Cake", "Cheese Cake", "Fish Cake", "Carrot Cake", "Birthday Cake", "Wedding Cake"]],
  ["Pie", ["Meat Pie", "Apple Pie", "Pork Pie", "Pie Chart", "Pumpkin Pie", "Cherry Pie"]],
  ["Cream", ["Ice Cream", "Sun Cream", "Cream Cheese", "Sour Cream", "Whipped Cream", "Shaving Cream"]],
  ["Cup", ["Cup Cake", "Tea Cup", "Egg Cup", "Butter Cup", "World Cup"]],
  ["Pot", ["Jack Pot", "Tea Pot", "Flower Pot", "Pot Hole", "Hot Pot", "Honey Pot"]],
  ["Pan", ["Frying Pan", "Pan Cake", "Sauce Pan", "Dust Pan", "Pan Handle"]],
  ["Plate", ["License Plate", "Home Plate", "Hot Plate", "Number Plate"]],
  ["Knife", ["Pocket Knife", "Butter Knife", "Jack Knife", "Bread Knife", "Steak Knife"]],
  ["Spoon", ["Wooden Spoon", "Tea Spoon", "Table Spoon", "Spoon Feed", "Soup Spoon"]],
  ["Fork", ["Tuning Fork", "Pitch Fork", "Fork Lift", "Salad Fork"]],
  ["Salt", ["Salt Shaker", "Sea Salt", "Salt Water", "Rock Salt", "Table Salt"]],
  ["Bean", ["Jelly Bean", "Bean Bag", "String Bean", "Coffee Bean", "Bean Stalk", "Green Bean"]],
  ["Rock", ["Rock Band", "Rock Star", "Bed Rock", "Rock Salt", "Rock Garden", "Rock Bottom"]],
  ["Tree", ["Family Tree", "Tree House", "Palm Tree", "Pine Tree", "Apple Tree", "Christmas Tree"]],
  ["Wood", ["Fire Wood", "Wood Pecker", "Ply Wood", "Drift Wood", "Red Wood", "Hard Wood"]],
  ["Leaf", ["Tea Leaf", "Fig Leaf", "Bay Leaf", "Gold Leaf", "Maple Leaf"]],
  ["Grass", ["Grass Hopper", "Grass Land", "Lemon Grass", "Grass Snake", "Blue Grass"]],
  ["Flower", ["Sun Flower", "Flower Pot", "Wild Flower", "Flower Bed", "May Flower", "Flower Girl"]],
  ["Field", ["Corn Field", "Battle Field", "Field Trip", "Oil Field", "Field Day", "Field Goal"]],
  ["Hill", ["Ant Hill", "Down Hill", "Up Hill", "Hill Side", "Hill Top"]],
  ["Stone", ["Grave Stone", "Mile Stone", "Corner Stone", "Stone Wall", "Lime Stone", "Stepping Stone"]],
  ["Sand", ["Sand Castle", "Sand Box", "Sand Paper", "Quick Sand", "Sand Bag", "Sand Storm"]],
  ["Ice", ["Ice Cream", "Ice Berg", "Ice Cube", "Ice Box", "Ice Skate", "Ice Rink"]],
  ["Cloud", ["Rain Cloud", "Storm Cloud", "Cloud Nine", "Mushroom Cloud", "Thunder Cloud"]],
  ["Storm", ["Thunder Storm", "Snow Storm", "Sand Storm", "Brain Storm", "Rain Storm", "Dust Storm"]],
  ["Light", ["Sun Light", "Moon Light", "Flash Light", "Day Light", "Spot Light", "Traffic Light", "Head Light", "Light House"]],
  ["House", ["Tree House", "Dog House", "Light House", "Green House", "House Boat", "White House", "Bird House", "Farm House"]],
  ["Room", ["Bed Room", "Bath Room", "Class Room", "Living Room", "Ball Room", "Court Room", "Rest Room"]],
  ["Yard", ["Back Yard", "Court Yard", "Grave Yard", "Junk Yard", "Barn Yard", "Farm Yard"]],
  ["Way", ["High Way", "Drive Way", "Rail Way", "Run Way", "Path Way", "Sub Way", "Hall Way"]],
  ["Side", ["Sea Side", "Country Side", "Road Side", "Bed Side", "Out Side", "In Side", "Hill Side"]],
  ["Line", ["Head Line", "Base Line", "Coast Line", "Dead Line", "Life Line", "Out Line", "Punch Line", "Finish Line"]],
  ["Time", ["Bed Time", "Day Time", "Night Time", "Life Time", "Over Time", "Play Time", "Half Time", "Time Machine"]],
  ["Work", ["Home Work", "Art Work", "Team Work", "Frame Work", "Fire Work", "Wood Work"]],
  ["Ground", ["Play Ground", "Back Ground", "Under Ground", "Camp Ground", "Battle Ground", "Fair Ground"]],
  ["Paper", ["News Paper", "Sand Paper", "Wall Paper", "Paper Clip", "Paper Back", "Toilet Paper"]],
  ["Board", ["Key Board", "Surf Board", "Chalk Board", "Card Board", "Dash Board", "Skate Board", "Score Board", "White Board"]],
  ["Chip", ["Potato Chip", "Poker Chip", "Chocolate Chip", "Wood Chip", "Blue Chip"]],
  ["Coffee", ["Coffee Cup", "Coffee Bean", "Coffee Table", "Coffee Break", "Coffee Shop", "Coffee Mug"]],
  ["Tea", ["Tea Pot", "Tea Cup", "Tea Spoon", "Tea Bag", "Tea Time", "Green Tea", "Bubble Tea"]],
  ["Cheese", ["Cheese Cake", "Cheese Burger", "Cheese Board", "Blue Cheese", "Cream Cheese", "Grilled Cheese"]],
  ["Butter", ["Butter Fly", "Butter Cup", "Butter Milk", "Peanut Butter", "Butter Knife", "Butter Bean"]],
  ["Honey", ["Honey Bee", "Honey Comb", "Honey Moon", "Honey Pot", "Honey Dew", "Honey Bun"]],
  ["Sugar", ["Sugar Cane", "Sugar Cube", "Brown Sugar", "Sugar Rush", "Sugar Free", "Sugar Bowl"]],
  ["Apple", ["Apple Pie", "Apple Sauce", "Pine Apple", "Apple Tree", "Apple Juice", "Big Apple"]],
  ["Orange", ["Orange Juice", "Orange Peel", "Blood Orange", "Orange Tree"]],
  ["Berry", ["Straw Berry", "Blue Berry", "Black Berry", "Goose Berry", "Berry Bush"]],
  ["Grape", ["Grape Fruit", "Grape Vine", "Grape Juice", "Sour Grape"]],
  ["Lemon", ["Lemon Grass", "Lemon Tree", "Lemon Drop", "Lemon Peel", "Lemon Juice"]],
  ["Nut", ["Pea Nut", "Coco Nut", "Chest Nut", "Dough Nut", "Nut Shell"]],
  ["Meat", ["Meat Ball", "Meat Loaf", "Mince Meat", "Meat Pie", "Red Meat", "Lunch Meat"]],
  ["Beef", ["Beef Burger", "Corned Beef", "Beef Cake", "Beef Steak", "Ground Beef", "Roast Beef"]],
  ["Ham", ["Ham Burger", "Ham Bone", "Ham Steak"]],
  ["Pork", ["Pork Chop", "Pork Pie", "Pork Belly", "Roast Pork", "Pulled Pork"]],
  ["Chicken", ["Chicken Pox", "Chicken Wing", "Chicken Soup", "Fried Chicken", "Roast Chicken", "Chicken Coop"]],
  ["Rice", ["Fried Rice", "Rice Cake", "Rice Pudding", "Wild Rice", "Brown Rice", "Rice Bowl"]],
  ["Soup", ["Chicken Soup", "Soup Spoon", "Pea Soup", "Tomato Soup", "Soup Bowl"]],
  ["Salad", ["Fruit Salad", "Salad Bowl", "Salad Bar", "Potato Salad", "Caesar Salad"]],
  ["Bar", ["Chocolate Bar", "Candy Bar", "Crow Bar", "Sand Bar", "Space Bar", "Snack Bar", "Handle Bar"]],
  ["Juice", ["Orange Juice", "Apple Juice", "Fruit Juice", "Grape Juice", "Juice Box", "Lemon Juice"]],
  ["Bug", ["Lady Bug", "Bed Bug", "June Bug", "Bug Spray", "Love Bug"]],
  ["Spider", ["Spider Web", "Spider Man", "Spider Bite", "Spider Plant"]],
  ["Web", ["Spider Web", "Web Site", "Web Page", "Cob Web", "Web Cam"]],
  ["Net", ["Fish Net", "Hair Net", "Safety Net", "Net Ball"]],
  ["Bag", ["Hand Bag", "Tea Bag", "Sleeping Bag", "Bean Bag", "Sand Bag", "Air Bag", "Gift Bag"]],
  ["Belt", ["Seat Belt", "Green Belt", "Belt Buckle", "Tool Belt", "Conveyor Belt", "Black Belt"]],
  ["Boot", ["Boot Camp", "Rubber Boot", "Boot Lace", "Ski Boot", "Snow Boot"]],
  ["Shoe", ["Horse Shoe", "Snow Shoe", "Shoe Lace", "Shoe Box", "Shoe Horn", "Tennis Shoe"]],
  ["Sock", ["Wind Sock", "Ankle Sock", "Tube Sock", "Knee Sock"]],
  ["Hat", ["Top Hat", "Hard Hat", "Sun Hat", "Hat Trick", "Straw Hat", "Party Hat"]],
  ["Coat", ["Rain Coat", "Over Coat", "Trench Coat", "Coat Rack", "Coat Hanger", "Fur Coat"]],
  ["Glass", ["Hour Glass", "Eye Glass", "Wine Glass", "Magnifying Glass", "Stained Glass", "Shot Glass"]],
  ["Key", ["Key Board", "Key Ring", "Key Hole", "Key Chain", "Key Note", "Key Pad"]],
  ["Lock", ["Pad Lock", "Dead Lock", "Lock Smith", "Lock Down", "Lock Jaw"]],
  ["Chain", ["Key Chain", "Chain Saw", "Food Chain", "Daisy Chain", "Chain Mail", "Chain Link"]],
  ["Nail", ["Finger Nail", "Toe Nail", "Nail Polish", "Nail File", "Thumb Nail", "Nail Clipper"]],
  ["Pin", ["Safety Pin", "Push Pin", "Rolling Pin", "Bobby Pin", "Clothes Pin", "Pin Wheel"]],
  ["Pen", ["Play Pen", "Pig Pen", "Pen Knife", "Pen Pal", "Fountain Pen"]],
  ["Cap", ["Night Cap", "Knee Cap", "Ice Cap", "Bottle Cap", "Swim Cap"]],
  ["Cloth", ["Table Cloth", "Wash Cloth", "Face Cloth", "Dish Cloth", "Loin Cloth"]],
  ["Brush", ["Tooth Brush", "Hair Brush", "Paint Brush", "Nail Brush", "Bottle Brush", "Brush Fire"]],
  ["Comb", ["Honey Comb", "Comb Over"]],
  ["Soap", ["Soap Box", "Soap Opera", "Soap Dish", "Soap Suds", "Hand Soap", "Dish Soap"]],
  ["Towel", ["Bath Towel", "Beach Towel", "Tea Towel", "Paper Towel", "Hand Towel", "Dish Towel"]],
  ["Mat", ["Door Mat", "Bath Mat", "Place Mat", "Yoga Mat", "Welcome Mat", "Beer Mat"]],
  ["Rug", ["Bear Rug", "Area Rug", "Rug Rat", "Throw Rug"]],
  ["Lamp", ["Lamp Shade", "Lamp Post", "Desk Lamp", "Oil Lamp", "Lava Lamp", "Street Lamp"]],
  ["Candle", ["Candle Stick", "Candle Light", "Candle Wick", "Candle Wax", "Birthday Candle"]],
  ["Watch", ["Wrist Watch", "Watch Dog", "Watch Man", "Watch Tower", "Stop Watch", "Pocket Watch"]],
  ["Ring", ["Ear Ring", "Boxing Ring", "Key Ring", "Ring Master", "Wedding Ring", "Nose Ring", "Onion Ring"]],
  ["Card", ["Post Card", "Playing Card", "Score Card", "Flash Card", "Credit Card", "Report Card", "Birthday Card", "Wild Card"]],
  ["Game", ["Board Game", "Video Game", "Ball Game", "Card Game", "Game Show", "End Game", "Game Plan"]],
  ["Show", ["Talk Show", "Game Show", "Slide Show", "Show Down", "Show Off", "Show Case", "Puppet Show"]],
  ["Play", ["Play Ground", "Play Time", "Play House", "Play Pen", "Play Boy", "Word Play", "Role Play"]],
  ["Note", ["Note Book", "Note Pad", "Foot Note", "Bank Note", "Sticky Note"]],
  ["Pad", ["Note Pad", "Key Pad", "Launch Pad", "Lily Pad", "Mouse Pad", "Knee Pad"]],
  ["Mark", ["Book Mark", "Land Mark", "Bench Mark", "Trade Mark", "Birth Mark", "Question Mark"]],
  ["Print", ["Foot Print", "Finger Print", "Blue Print", "Paw Print", "Thumb Print", "Hand Print"]],
  ["Camp", ["Camp Fire", "Camp Site", "Camp Ground", "Boot Camp", "Base Camp", "Summer Camp"]],
  ["Trip", ["Road Trip", "Field Trip", "Trip Wire", "Day Trip", "Round Trip"]],
  ["Boat", ["Sail Boat", "Row Boat", "Speed Boat", "House Boat", "Tug Boat", "Life Boat", "Steam Boat"]],
  ["Ship", ["Space Ship", "Battle Ship", "Ship Yard", "Ship Wreck", "Ship Mate", "Flag Ship", "Cruise Ship"]],
  ["Car", ["Race Car", "Cable Car", "Box Car", "Car Wash", "Car Park", "Sports Car", "Car Seat", "Bumper Car"]],
  ["Truck", ["Fire Truck", "Dump Truck", "Monster Truck", "Tow Truck", "Food Truck", "Truck Stop"]],
  ["Train", ["Freight Train", "Train Track", "Steam Train", "Train Station", "Bullet Train", "Train Set"]],
  ["Plane", ["Air Plane", "Sea Plane", "War Plane", "Jet Plane", "Paper Plane"]],
  ["Bike", ["Motor Bike", "Mountain Bike", "Dirt Bike", "Bike Rack", "Bike Lane", "Bike Path"]],
  ["Road", ["Rail Road", "Cross Road", "Road Block", "Road Side", "Road Trip", "Road Map", "Road Sign", "Road Rage"]],
  ["Rail", ["Rail Road", "Rail Way", "Guard Rail", "Hand Rail", "Mono Rail"]],
  ["Bridge", ["Draw Bridge", "Foot Bridge", "Toll Bridge", "Rope Bridge"]],
  ["Station", ["Train Station", "Bus Station", "Gas Station", "Space Station", "Fire Station", "Police Station"]],
  ["Port", ["Air Port", "Sea Port", "Car Port", "Pass Port", "Port Hole"]],
  ["Park", ["Car Park", "Ball Park", "Theme Park", "National Park", "Park Bench", "Water Park"]],
  ["Garden", ["Rose Garden", "Garden Hose", "Beer Garden", "Garden Path", "Herb Garden", "Garden Shed"]],
  ["Farm", ["Farm House", "Farm Yard", "Farm Hand", "Wind Farm", "Dairy Farm", "Ant Farm"]],
  ["City", ["City Hall", "Inner City", "City Centre", "City Limits", "Capital City"]],
  ["Town", ["Down Town", "Home Town", "China Town", "Ghost Town", "Town Hall", "Town House"]],
  ["Street", ["Street Light", "Main Street", "Street Car", "Side Street", "Wall Street", "High Street"]],
  ["Wall", ["Fire Wall", "Wall Paper", "Stone Wall", "Wall Flower", "Brick Wall", "Great Wall"]],
  ["Roof", ["Roof Top", "Sun Roof", "Roof Rack", "Roof Tile", "Flat Roof"]],
  ["Floor", ["Ground Floor", "Floor Board", "Dance Floor", "Floor Plan", "Sea Floor", "Top Floor"]],
  ["Gate", ["Gate Way", "Gate Keeper", "Gate Post", "Flood Gate", "Toll Gate", "Golden Gate"]],
  ["Fence", ["Picket Fence", "Fence Post", "Electric Fence", "Garden Fence"]],
  ["Sky", ["Sky Line", "Sky Scraper", "Sky Light", "Sky Diver", "Sky Rocket", "Sky Blue", "Night Sky"]],
  ["Air", ["Air Port", "Air Plane", "Air Line", "Air Craft", "Air Bag", "Air Force", "Fresh Air", "Hot Air"]],
  ["Fog", ["Fog Horn", "Fog Light", "Fog Machine", "Brain Fog"]],
  ["Frost", ["Frost Bite", "Jack Frost", "Ground Frost"]],
  ["Dew", ["Dew Drop", "Honey Dew", "Morning Dew", "Dew Point"]],
  ["Wave", ["Tidal Wave", "Heat Wave", "Micro Wave", "Sound Wave", "Brain Wave", "Shock Wave"]],
  ["Tide", ["High Tide", "Low Tide", "Red Tide", "Rip Tide", "Tide Pool"]],
  ["Beach", ["Beach Ball", "Beach Chair", "Beach Towel", "Beach House", "Beach Front", "Sandy Beach"]],
  ["Gold", ["Gold Fish", "Gold Mine", "Gold Smith", "Gold Rush", "Gold Medal", "Gold Bar"]],
  ["Silver", ["Silver Ware", "Silver Fish", "Silver Smith", "Silver Screen", "Silver Medal"]],
  ["Iron", ["Cast Iron", "Iron Man", "Flat Iron", "Iron Fist", "Waffle Iron", "Steam Iron"]],
  ["Coal", ["Coal Mine", "Coal Field", "Char Coal", "Coal Face"]],
  ["Oil", ["Oil Field", "Oil Well", "Oil Rig", "Oil Paint", "Olive Oil", "Oil Spill"]],
  ["Gas", ["Gas Station", "Gas Mask", "Tear Gas", "Gas Pump", "Natural Gas", "Laughing Gas"]],
  ["Steam", ["Steam Boat", "Steam Ship", "Steam Roller", "Steam Engine", "Steam Train", "Steam Iron"]],
  ["Life", ["Life Boat", "Life Guard", "Wild Life", "Life Time", "Life Line", "Life Style", "Life Jacket"]],
  ["Home", ["Home Work", "Home Made", "Home Town", "Home Sick", "Home Land", "Home Run", "Home Page"]],
  ["School", ["High School", "School Boy", "School Girl", "School Bus", "School Yard", "Pre School", "Sunday School"]],
  ["Baby", ["Baby Sit", "Baby Boom", "Baby Food", "Baby Face", "Baby Shower", "Cry Baby"]],
  ["Blood", ["Blood Hound", "Blood Bath", "Blood Shot", "Blood Stream", "Blood Line", "Blood Bank"]],
  ["Night", ["Night Fall", "Night Gown", "Night Mare", "Night Owl", "Mid Night", "Over Night", "Night Club"]],
  ["Day", ["Day Dream", "Day Break", "Day Light", "Birth Day", "Pay Day", "Day Care", "Snow Day"]],
  ["Green", ["Green House", "Green Horn", "Ever Green", "Green Room", "Green Belt", "Green Thumb"]],
  ["Blue", ["Blue Bird", "Blue Berry", "Blue Print", "Blue Bell", "Navy Blue", "Sky Blue"]],
  ["Black", ["Black Bird", "Black Board", "Black Berry", "Black Out", "Black Smith", "Black Mail", "Black Belt"]],
  ["White", ["White Wash", "White Board", "Egg White", "White Out", "Snow White", "White House"]],
  ["Red", ["Red Head", "Red Wood", "Red Neck", "Red Coat", "Red Card", "Red Carpet"]],
  ["Back", ["Back Bone", "Back Fire", "Back Ground", "Back Pack", "Back Yard", "Feed Back", "Come Back"]],
  ["Cross", ["Cross Bow", "Cross Fire", "Cross Road", "Cross Walk", "Cross Word", "Cross Over"]],

  // --- Body ---
  ["Arm", ["Arm Pit", "Arm Band", "Arm Rest", "Fore Arm"]],
  ["Leg", ["Peg Leg", "Leg Room", "Leg Work"]],
  ["Knee", ["Knee Deep", "Knee Jerk", "Knee High"]],
  ["Neck", ["Neck Lace", "Neck Tie", "Turtle Neck", "Bottle Neck", "Neck Line"]],
  ["Lip", ["Lip Stick", "Lip Balm", "Lip Gloss"]],
  ["Skin", ["Skin Deep", "Skin Care", "Skin Tight"]],
  ["Bone", ["Jaw Bone", "Wish Bone", "Bone Dry", "Funny Bone", "Collar Bone", "Bone Yard"]],
  ["Brain", ["Brain Wash", "Brain Power", "Brain Child", "Brain Freeze"]],
  ["Chest", ["Treasure Chest", "War Chest"]],
  ["Rib", ["Rib Cage", "Spare Rib", "Prime Rib"]],
  ["Tongue", ["Tongue Twister", "Mother Tongue", "Tongue Tied"]],
  ["Finger", ["Finger Tip", "Lady Finger", "Finger Food", "Finger Paint"]],
  ["Cell", ["Cell Phone", "Jail Cell", "Blood Cell", "Cell Block", "Brain Cell"]],
  ["Pill", ["Pill Box", "Sleeping Pill", "Bitter Pill"]],

  // --- Animals ---
  ["Horse", ["Horse Power", "Horse Back", "Race Horse", "Rocking Horse", "Horse Radish", "Work Horse"]],
  ["Lion", ["Lion Heart", "Mountain Lion", "Lion Cub"]],
  ["Wolf", ["Wolf Pack", "Lone Wolf", "Wolf Whistle"]],
  ["Fox", ["Fox Hole", "Fox Trot", "Silver Fox"]],
  ["Rat", ["Rat Race", "Gym Rat", "Rat Trap", "Pack Rat", "Lab Rat"]],
  ["Mouse", ["Mouse Trap", "Church Mouse", "Field Mouse", "Mouse Hole", "Mickey Mouse"]],
  ["Rabbit", ["Rabbit Hole", "Rabbit Foot", "Rabbit Ears", "Jack Rabbit"]],
  ["Goat", ["Mountain Goat", "Billy Goat", "Goat Cheese"]],
  ["Crab", ["Crab Cake", "Hermit Crab", "Crab Apple", "King Crab", "Crab Grass"]],
  ["Whale", ["Blue Whale", "Killer Whale", "Whale Song"]],
  ["Shark", ["Loan Shark", "Card Shark", "Shark Bite", "Shark Fin", "Great White Shark"]],
  ["Turtle", ["Sea Turtle", "Turtle Dove", "Turtle Shell", "Snapping Turtle"]],
  ["Tiger", ["Paper Tiger", "Tiger Lily", "Tiger Cub", "Bengal Tiger"]],
  ["Monkey", ["Monkey Wrench", "Grease Monkey", "Monkey Business", "Spider Monkey", "Sea Monkey"]],
  ["Elephant", ["White Elephant", "Elephant Seal", "Elephant Ear"]],
  ["Goose", ["Mother Goose", "Goose Egg", "Wild Goose"]],
  ["Swan", ["Swan Dive", "Swan Lake", "Black Swan", "Swan Song"]],
  ["Hawk", ["Night Hawk", "Hawk Eye", "Chicken Hawk"]],
  ["Eagle", ["Bald Eagle", "Legal Eagle", "Golden Eagle", "Eagle Scout"]],

  // --- Food & drink ---
  ["Fruit", ["Fruit Cake", "Fruit Bat", "Passion Fruit", "Fruit Bowl", "Dragon Fruit", "Star Fruit"]],
  ["Cookie", ["Cookie Jar", "Cookie Cutter", "Cookie Dough", "Fortune Cookie"]],
  ["Candy", ["Candy Cane", "Cotton Candy", "Candy Floss", "Eye Candy", "Candy Corn"]],
  ["Chocolate", ["Chocolate Cake", "Chocolate Milk", "Hot Chocolate", "Chocolate Box"]],
  ["Jam", ["Jam Jar", "Traffic Jam", "Jam Session"]],
  ["Pizza", ["Pizza Pie", "Pizza Slice", "Pizza Oven"]],
  ["Sauce", ["Soy Sauce", "Hot Sauce", "Tomato Sauce"]],
  ["Toast", ["French Toast", "Toast Master"]],
  ["Dough", ["Sour Dough", "Play Dough", "Dough Boy"]],
  ["Pepper", ["Pepper Mill", "Chilli Pepper", "Pepper Spray"]],
  ["Pickle", ["Dill Pickle", "Pickle Jar", "Pickle Juice"]],
  ["Onion", ["Onion Skin", "Spring Onion", "Onion Soup"]],
  ["Potato", ["Couch Potato", "Mashed Potato", "Sweet Potato", "Hot Potato", "Potato Skin"]],
  ["Tomato", ["Cherry Tomato", "Tomato Paste", "Tomato Juice"]],
  ["Mint", ["Mint Condition", "Mint Green", "Mint Sauce"]],
  ["Cracker", ["Fire Cracker", "Cream Cracker", "Nut Cracker", "Safe Cracker", "Cracker Jack"]],
  ["Noodle", ["Noodle Soup", "Pool Noodle", "Noodle Bar"]],
  ["Sausage", ["Sausage Roll", "Sausage Dog", "Sausage Link"]],
  ["Steak", ["Steak House", "Rump Steak", "Steak Sauce"]],
  ["Chop", ["Lamb Chop", "Karate Chop", "Chop Shop"]],
  ["Roll", ["Drum Roll", "Bread Roll", "Barrel Roll", "Spring Roll", "Cinnamon Roll", "Roll Call"]],
  ["Syrup", ["Maple Syrup", "Corn Syrup", "Cough Syrup"]],
  ["Cereal", ["Cereal Bowl", "Cereal Box", "Breakfast Cereal"]],
  ["Spice", ["Spice Rack", "All Spice", "Pumpkin Spice"]],
  ["Gum", ["Chewing Gum", "Gum Ball", "Gum Drop", "Gum Tree", "Gum Boot"]],
  ["Wine", ["Red Wine", "White Wine", "Wine Cellar", "Wine Rack"]],
  ["Beer", ["Root Beer", "Ginger Beer", "Beer Belly", "Beer Can"]],
  ["Soda", ["Soda Pop", "Soda Water", "Baking Soda", "Cream Soda", "Soda Fountain"]],
  ["Punch", ["Punch Bag", "Fruit Punch", "Punch Bowl", "Sucker Punch"]],

  // --- Household & objects ---
  ["Window", ["Window Sill", "Window Pane", "Window Shop", "Bay Window", "Window Box"]],
  ["Stair", ["Stair Case", "Stair Way", "Stair Well"]],
  ["Brick", ["Brick Layer", "Brick Work", "Gold Brick"]],
  ["Chimney", ["Chimney Sweep", "Chimney Pot", "Chimney Stack"]],
  ["Basket", ["Bread Basket", "Waste Basket", "Basket Case", "Picnic Basket"]],
  ["Bucket", ["Bucket List", "Bucket Hat", "Rust Bucket", "Bucket Seat"]],
  ["Broom", ["Broom Stick", "Broom Closet"]],
  ["Mirror", ["Mirror Ball", "Mirror Image", "Side Mirror"]],
  ["Curtain", ["Curtain Call", "Shower Curtain", "Iron Curtain", "Curtain Rod"]],
  ["Pillow", ["Pillow Case", "Pillow Fight", "Pillow Talk", "Throw Pillow"]],
  ["Blanket", ["Wet Blanket", "Electric Blanket", "Security Blanket", "Blanket Fort"]],
  ["Sheet", ["Bed Sheet", "Sheet Music", "Balance Sheet", "Ice Sheet", "Sheet Metal"]],
  ["Rope", ["Jump Rope", "Tight Rope", "Rope Ladder", "Tow Rope"]],
  ["String", ["Shoe String", "G String", "String Cheese", "Bow String"]],
  ["Needle", ["Needle Point", "Pine Needle", "Needle Work"]],
  ["Button", ["Belly Button", "Button Hole", "Push Button", "Panic Button"]],
  ["Zip", ["Zip Code", "Zip Line", "Zip Lock"]],
  ["Pocket", ["Pick Pocket", "Pocket Money", "Air Pocket", "Pocket Book"]],
  ["Bench", ["Work Bench", "Bench Press", "Bench Warmer"]],
  ["Desk", ["Desk Top", "Help Desk", "Front Desk", "Desk Job"]],
  ["Cabinet", ["Filing Cabinet", "Cabinet Maker", "Medicine Cabinet"]],
  ["Stool", ["Bar Stool", "Foot Stool", "Step Stool", "Toad Stool"]],

  // --- Tools & machines ---
  ["Hammer", ["Jack Hammer", "Sledge Hammer", "Hammer Head", "Claw Hammer"]],
  ["Saw", ["See Saw", "Jig Saw", "Hack Saw", "Saw Dust", "Saw Mill", "Buzz Saw"]],
  ["Drill", ["Fire Drill", "Drill Bit", "Drill Sergeant", "Power Drill"]],
  ["Screw", ["Screw Driver", "Cork Screw", "Thumb Screw", "Screw Ball"]],
  ["Axe", ["Battle Axe", "Pick Axe", "Ice Axe"]],
  ["Ladder", ["Step Ladder", "Corporate Ladder", "Ladder Rung"]],
  ["Wire", ["Live Wire", "Wire Tap", "Barbed Wire", "High Wire"]],
  ["Tape", ["Duct Tape", "Tape Measure", "Red Tape", "Masking Tape"]],
  ["Glue", ["Glue Stick", "Glue Gun", "Super Glue"]],
  ["Clip", ["Hair Clip", "Clip Board", "Clip Art", "Money Clip"]],
  ["Hook", ["Hook Worm", "Coat Hook", "Meat Hook", "Grappling Hook"]],
  ["Rod", ["Fishing Rod", "Hot Rod", "Fly Rod"]],
  ["Gear", ["Gear Box", "Gear Shift", "Head Gear", "Gear Stick"]],
  ["Engine", ["Search Engine", "Engine Room", "Jet Engine"]],
  ["Motor", ["Motor Way", "Motor Boat", "Motor Cycle", "Motor Home"]],
  ["Jet", ["Jet Lag", "Jet Ski", "Jet Stream", "Jet Pack", "Jumbo Jet", "Jet Black"]],
  ["Flag", ["Flag Pole", "Red Flag", "White Flag", "Flag Stone"]],

  // --- Nature & landscape ---
  ["Mountain", ["Mountain Top", "Mountain Range", "Mountain Side"]],
  ["River", ["River Bank", "River Bed", "River Boat", "River Side"]],
  ["Lake", ["Lake Side", "Lake House", "Lake Front"]],
  ["Ocean", ["Ocean Floor", "Ocean Liner", "Ocean Front", "Ocean Wave"]],
  ["Island", ["Desert Island", "Tropical Island", "Treasure Island", "Island Hop"]],
  ["Desert", ["Desert Storm", "Desert Rat", "Desert Rose"]],
  ["Forest", ["Forest Fire", "Forest Floor", "Forest Ranger"]],
  ["Cave", ["Cave Man", "Bat Cave", "Cave Dweller"]],
  ["Valley", ["Death Valley", "Silicon Valley", "Valley Girl"]],
  ["Cliff", ["Cliff Hanger", "Cliff Edge", "Cliff Diving", "Cliff Top"]],
  ["Jungle", ["Jungle Gym", "Concrete Jungle", "Jungle Cat"]],
  ["Mud", ["Mud Pie", "Mud Bath", "Mud Slide", "Mud Guard"]],
  ["Dirt", ["Dirt Road", "Dirt Cheap", "Dirt Track", "Pay Dirt"]],
  ["Dust", ["Dust Bin", "Star Dust", "Gold Dust", "Dust Bunny"]],
  ["Smoke", ["Smoke Stack", "Smoke Screen", "Smoke Alarm", "Smoke Bomb", "Smoke Detector"]],
  ["Flame", ["Flame Thrower", "Old Flame"]],
  ["Thunder", ["Thunder Bolt", "Thunder Bird"]],
  ["Lightning", ["Lightning Bolt", "Lightning Bug", "Lightning Rod", "Lightning Strike"]],
  ["Shadow", ["Eye Shadow", "Shadow Box", "Shadow Puppet"]],
  ["Rose", ["Rose Bud", "Rose Bush", "Rose Water", "Rose Petal", "Rose Wood", "Rose Gold"]],
  ["Root", ["Square Root", "Root Canal", "Tap Root"]],
  ["Seed", ["Poppy Seed", "Sesame Seed", "Bird Seed"]],
  ["Trunk", ["Tree Trunk", "Elephant Trunk", "Trunk Road"]],
  ["Log", ["Log Cabin", "Log Book", "Yule Log", "Log Jam", "Back Log"]],
  ["Cone", ["Pine Cone", "Traffic Cone", "Snow Cone", "Nose Cone"]],

  // --- People & roles ---
  ["King", ["King Fisher", "King Pin", "King Size", "King Cobra"]],
  ["Queen", ["Drag Queen", "Queen Size", "Beauty Queen"]],
  ["Man", ["Mail Man", "Super Man", "Man Hole", "Best Man", "Con Man", "Weather Man"]],
  ["Boy", ["Tom Boy", "Bad Boy", "Boy Scout", "Paper Boy", "Boy Band"]],
  ["Girl", ["Girl Friend", "Girl Scout", "Baby Girl"]],
  ["Friend", ["Boy Friend", "Best Friend", "Friend Ship"]],
  ["Doctor", ["Witch Doctor", "Spin Doctor"]],
  ["Master", ["Head Master", "Task Master", "Master Piece", "Master Mind", "Master Key", "Grand Master"]],
  ["Maid", ["Brides Maid", "House Maid", "Old Maid"]],

  // --- Abstract but guessable ---
  ["Dream", ["Dream Team", "Dream Land", "Dream Catcher", "Pipe Dream"]],
  ["Peace", ["Peace Maker", "Peace Pipe", "Peace Sign", "Peace Keeper"]],
  ["Love", ["Love Seat", "Love Sick", "Puppy Love", "Love Letter", "Love Bird", "Love Story"]],
  ["Word", ["Pass Word", "Key Word", "Buzz Word", "Swear Word", "Word Search"]],
  ["Voice", ["Voice Mail", "Voice Box", "Voice Over"]],
  ["Sound", ["Sound Track", "Sound Proof", "Sound Bite", "Sound Check"]],
  ["Song", ["Love Song", "Folk Song", "Theme Song", "Song Writer"]],
  ["Story", ["Short Story", "Story Book", "Story Line", "Ghost Story", "Story Teller"]],
  ["Dance", ["Rain Dance", "Tap Dance", "Belly Dance", "Break Dance", "Line Dance", "Square Dance"]],
  ["Luck", ["Pot Luck", "Lady Luck", "Beginners Luck"]],

  // --- Games & sport ---
  ["Goal", ["Goal Post", "Goal Keeper", "Own Goal", "Goal Line"]],
  ["Team", ["Team Mate", "Home Team", "Tag Team"]],
  ["Race", ["Race Track", "Drag Race", "Arms Race", "Race Course"]],
  ["Match", ["Match Stick", "Match Maker", "Match Point", "Boxing Match"]],
  ["Kick", ["Side Kick", "Kick Stand", "Kick Off", "Drop Kick", "Free Kick", "Kick Start"]],
  ["Bat", ["Vampire Bat", "Cricket Bat", "Bat Man", "Bat Boy"]],
  ["Coach", ["Head Coach", "Life Coach", "Stage Coach", "Coach House"]],

  // --- Money ---
  ["Money", ["Money Bag", "Money Box", "Money Order", "Blood Money", "Money Maker"]],
  ["Coin", ["Coin Toss", "Coin Slot", "Bit Coin"]],
  ["Cash", ["Cash Cow", "Cash Flow", "Cash Register", "Cash Back", "Petty Cash", "Cash Machine"]],
  ["Bank", ["Piggy Bank", "Bank Account", "Bank Robber", "Food Bank", "Bank Roll"]],
  ["Diamond", ["Diamond Ring", "Diamond Back", "Blood Diamond", "Diamond Mine"]],
  ["Crown", ["Crown Jewel", "Crown Prince", "Triple Crown"]],
  ["Treasure", ["Treasure Hunt", "Treasure Map", "Buried Treasure", "Treasure Trove"]],

  // --- Fantasy & play ---
  ["Space", ["Space Craft", "Parking Space", "Space Age"]],
  ["World", ["World War", "World Wide", "Under World", "World Record", "Third World"]],
  ["Angel", ["Guardian Angel", "Angel Cake", "Angel Fish", "Angel Food", "Fallen Angel"]],
  ["Ghost", ["Ghost Writer", "Holy Ghost", "Ghost Ship"]],
  ["Witch", ["Witch Craft", "Witch Hunt", "Witch Hazel"]],
  ["Monster", ["Sea Monster", "Cookie Monster", "Monster Mash"]],
  ["Giant", ["Giant Panda", "Gentle Giant", "Giant Squid"]],
  ["Dragon", ["Dragon Boat", "Komodo Dragon", "Bearded Dragon"]],
  ["Clown", ["Clown Fish", "Class Clown", "Clown Car"]],
  ["Toy", ["Toy Box", "Toy Store", "Toy Soldier"]],
  ["Doll", ["Doll House", "Rag Doll", "Paper Doll", "Baby Doll"]],
  ["Balloon", ["Water Balloon", "Balloon Animal", "Party Balloon"]],
  ["Bubble", ["Bubble Gum", "Bubble Wrap", "Soap Bubble"]],

  // --- Colours ---
  ["Pink", ["Pink Slip", "Pink Eye", "Hot Pink"]],
  ["Brown", ["Hash Brown", "Brown Bread", "Brown Nose", "Brown Stone"]],
  ["Grey", ["Grey Hound", "Grey Area", "Earl Grey"]],
  ["Yellow", ["Yellow Belly", "Yellow Fever", "Yellow Jacket", "Yellow Stone"]],

  // --- Sounds & gestures ---
  ["Kiss", ["French Kiss", "Butterfly Kiss", "Kiss Curl"]],
  ["Laugh", ["Laugh Track", "Belly Laugh", "Last Laugh"]],
  ["Cry", ["Battle Cry", "War Cry", "Far Cry"]],
  ["Whistle", ["Dog Whistle", "Whistle Blower", "Tin Whistle", "Whistle Stop"]],

  // --- Animal parts ---
  ["Wing", ["Wing Span", "Wing Man", "Wing Nut", "Buffalo Wing", "Left Wing", "Wing Tip"]],
  ["Tail", ["Pony Tail", "Fish Tail", "Cock Tail", "Tail Gate", "Tail Spin", "Tail Wind", "Cotton Tail"]],
  ["Horn", ["Bull Horn", "French Horn", "Long Horn", "Car Horn"]],
  ["Claw", ["Bear Claw", "Claw Foot", "Crab Claw"]],
  ["Feather", ["Feather Weight", "Feather Bed", "Feather Duster"]],
  ["Scale", ["Fish Scale", "Scale Model", "Pay Scale"]],
  ["Shell", ["Clam Shell", "Shell Fish", "Shell Shock", "Bomb Shell"]],

  // --- Weapons ---
  ["Sword", ["Sword Play", "Sword Fight", "Broad Sword"]],
  ["Gun", ["Gun Powder", "Gun Fire", "Shot Gun", "Machine Gun", "Squirt Gun", "Gun Fight", "Nail Gun"]],
  ["Bomb", ["Time Bomb", "Car Bomb", "Bomb Squad", "Cherry Bomb", "Stink Bomb", "Bath Bomb"]],
  ["Bullet", ["Bullet Proof", "Bullet Point", "Bullet Hole", "Silver Bullet"]],
  ["Tank", ["Water Tank", "Think Tank", "Tank Top", "Gas Tank", "Shark Tank"]],

  // --- Buildings & places ---
  ["Church", ["Church Yard", "Church Bell", "Church Goer"]],
  ["Tower", ["Bell Tower", "Water Tower", "Ivory Tower", "Control Tower", "Tower Block"]],
  ["Hall", ["Study Hall", "Dance Hall", "Pool Hall", "Hall Pass"]],
  ["Shop", ["Work Shop", "Book Shop", "Sweet Shop", "Shop Lift", "Pet Shop", "Gift Shop"]],
  ["Store", ["Drug Store", "Store Room", "Book Store", "Store Front"]],
  ["Market", ["Super Market", "Flea Market", "Stock Market", "Market Place", "Black Market"]],
  ["Office", ["Post Office", "Box Office", "Office Worker", "Head Office"]],
  ["Prison", ["Prison Guard", "Prison Break", "Prison Yard"]],
  ["Jail", ["Jail Bird", "Jail Break", "Jail House", "Jail Time"]],
  ["Border", ["Border Line", "Border Control", "Border Collie"]],

  // --- Time & seasons ---
  ["Week", ["Week End", "Week Day", "Mid Week", "Week Night"]],
  ["Year", ["Year Book", "Leap Year", "New Year", "Light Year"]],
  ["Hour", ["Rush Hour", "Happy Hour", "Hour Hand", "Lunch Hour"]],
  ["Minute", ["Minute Hand", "Last Minute", "Minute Man"]],
  ["Season", ["Season Ticket", "Off Season", "Open Season"]],
  ["Spring", ["Spring Board", "Spring Time", "Hot Spring", "Spring Chicken", "Off Spring", "Spring Clean"]],
  ["Summer", ["Summer Time", "Summer House", "Mid Summer", "Indian Summer"]],
  ["Winter", ["Winter Time", "Winter Coat", "Mid Winter"]],
];

export const EVERYDAY_CARDS: WordCard[] = fromTable(TABLE);
