import type { WordCard } from "../types";
import { fromTable } from "./gen";

// Fantasy: magic, dragons, elves, medieval. Curated real phrases only — each
// hard phrase is an established compound/name that contains the easy word.

const TABLE: [string, string[]][] = [
  ["Dragon", ["Dragon Fire", "Dragon Egg", "Dragon Slayer", "Dragon Rider", "Dragon Scale", "Dragon Lord", "Baby Dragon", "Sea Dragon"]],
  ["Sword", ["Magic Sword", "Broad Sword", "Long Sword", "Sword Fight", "Sword Master", "Flaming Sword", "Great Sword", "Sword Play"]],
  ["Spell", ["Spell Book", "Magic Spell", "Fire Spell", "Ice Spell", "Sleeping Spell", "Counter Spell", "Death Spell"]],
  ["Wizard", ["Wizard Hat", "Wizard Tower", "Wizard Staff", "Grand Wizard", "Battle Wizard"]],
  ["Witch", ["Witch Hat", "Witch Craft", "Sea Witch", "Snow Witch", "Witch Hunt", "Wicked Witch", "Witch Doctor"]],
  ["Knight", ["Dark Knight", "White Knight", "Black Knight", "Knight Errant", "Knight Rider"]],
  ["Castle", ["Castle Gate", "Castle Wall", "Sand Castle", "Castle Keep", "Castle Moat", "Haunted Castle"]],
  ["Magic", ["Black Magic", "White Magic", "Magic Carpet", "Magic Mirror", "Magic Wand", "Magic Ring", "Magic Bean", "Dark Magic", "Magic Trick", "Magic Potion"]],
  ["Fire", ["Dragon Fire", "Wild Fire", "Hell Fire", "Fire Ball", "Fire Storm", "Camp Fire", "Fire Breath"]],
  ["Ice", ["Ice Queen", "Ice Spell", "Ice Storm", "Ice Wall", "Black Ice", "Ice Giant"]],
  ["King", ["Goblin King", "Lich King", "Sorcerer King", "Warrior King", "Boy King", "King Cobra"]],
  ["Queen", ["Ice Queen", "Snow Queen", "Fairy Queen", "Warrior Queen", "Evil Queen", "Red Queen"]],
  ["Elf", ["Wood Elf", "High Elf", "Night Elf", "Dark Elf", "Elf King", "Elf Lord"]],
  ["Giant", ["Frost Giant", "Fire Giant", "Stone Giant", "Cloud Giant", "Hill Giant", "Gentle Giant"]],
  ["Troll", ["Cave Troll", "Bridge Troll", "Mountain Troll", "Troll King"]],
  ["Goblin", ["Goblin King", "Goblin Horde", "Cave Goblin", "Hob Goblin", "Goblin Market"]],
  ["Beast", ["Fell Beast", "Sea Beast", "Wild Beast", "Shadow Beast", "Beast Master"]],
  ["Wolf", ["Were Wolf", "Dire Wolf", "Wolf Pack", "Sea Wolf", "Wolf Man"]],
  ["Crown", ["Iron Crown", "Golden Crown", "Broken Crown", "Royal Crown", "Crown Jewel"]],
  ["Ring", ["Magic Ring", "Gold Ring", "Ring Bearer", "Signet Ring"]],
  ["Staff", ["Magic Staff", "Wizard Staff", "Battle Staff", "Wooden Staff"]],
  ["Shield", ["Magic Shield", "Battle Shield", "Iron Shield", "Shield Wall", "Shield Maiden"]],
  ["Potion", ["Magic Potion", "Healing Potion", "Love Potion", "Poison Potion", "Potion Bottle"]],
  ["Rune", ["Rune Stone", "Rune Sword", "Magic Rune", "Rune Master", "Blood Rune"]],
  ["Cave", ["Dragon Cave", "Cave Troll", "Bat Cave", "Cave Man", "Dark Cave"]],
  ["Forest", ["Dark Forest", "Enchanted Forest", "Haunted Forest", "Elven Forest", "Forest Spirit"]],
  ["Tower", ["Wizard Tower", "Dark Tower", "Bell Tower", "Watch Tower", "Ivory Tower", "Clock Tower"]],
  ["Curse", ["Ancient Curse", "Dark Curse", "Blood Curse", "Family Curse"]],
  ["Ghost", ["Ghost Town", "Ghost Ship", "Ghost Story", "Holy Ghost", "Friendly Ghost"]],
  ["Fairy", ["Fairy Tale", "Tooth Fairy", "Fairy Dust", "Fairy Ring", "Fairy Queen"]],
  ["Phoenix", ["Fire Phoenix", "Phoenix Feather", "Rising Phoenix"]],
  ["Unicorn", ["Magic Unicorn", "Unicorn Horn", "Baby Unicorn", "Rainbow Unicorn"]],
  ["Angel", ["Guardian Angel", "Fallen Angel", "Angel Wing", "Snow Angel", "Dark Angel"]],
  ["Demon", ["Demon King", "Fire Demon", "Demon Lord", "Speed Demon", "Inner Demon"]],
  ["Vampire", ["Vampire Bat", "Vampire Bite", "Vampire King", "Vampire Slayer"]],
  ["Axe", ["Battle Axe", "War Axe", "Great Axe", "Double Axe"]],
  ["Bow", ["Long Bow", "Cross Bow", "War Bow", "Magic Bow"]],
  ["Gold", ["Dragon Gold", "Gold Coin", "Fools Gold", "Gold Crown"]],

  // Relics & magic items
  ["Scroll", ["Magic Scroll", "Ancient Scroll", "Spell Scroll"]],
  ["Orb", ["Crystal Orb", "Magic Orb", "Power Orb"]],
  ["Crystal", ["Crystal Ball", "Crystal Cave", "Crystal Skull", "Crystal Sword"]],
  ["Amulet", ["Magic Amulet", "Gold Amulet", "Cursed Amulet"]],
  ["Charm", ["Lucky Charm", "Magic Charm", "Charm Spell"]],
  ["Mirror", ["Mirror Realm", "Dark Mirror", "Mirror Image"]],
  ["Book", ["Magic Book", "Story Book", "Rune Book"]],
  ["Map", ["Treasure Map", "Magic Map", "Star Map", "World Map"]],
  ["Key", ["Magic Key", "Golden Key", "Master Key", "Key Stone"]],
  ["Chest", ["Treasure Chest", "Magic Chest", "Chest Plate"]],
  ["Treasure", ["Treasure Hunt", "Buried Treasure", "Treasure Hoard"]],
  ["Poison", ["Poison Dart", "Poison Apple", "Snake Poison", "Poison Ivy"]],
  ["Venom", ["Snake Venom", "Spider Venom", "Venom Fang"]],

  // Realms & places
  ["Throne", ["Iron Throne", "Golden Throne", "Throne Room"]],
  ["Kingdom", ["Lost Kingdom", "Magic Kingdom", "Fallen Kingdom"]],
  ["Realm", ["Shadow Realm", "Spirit Realm", "Mortal Realm"]],
  ["Portal", ["Magic Portal", "Time Portal", "Portal Gate"]],
  ["Gate", ["Hell Gate", "Gate Keeper", "Iron Gate", "Dragon Gate"]],
  ["Lair", ["Dragon Lair", "Beast Lair", "Secret Lair"]],
  ["Den", ["Dragon Den", "Wolf Den", "Thieves Den"]],
  ["Nest", ["Dragon Nest", "Serpent Nest", "Birds Nest"]],

  // People & roles
  ["Sorcerer", ["Dark Sorcerer", "Sorcerer Stone", "Evil Sorcerer"]],
  ["Mage", ["Battle Mage", "Fire Mage", "Dark Mage", "Arch Mage", "War Mage"]],
  ["Priest", ["High Priest", "Dark Priest", "War Priest"]],
  ["Warrior", ["Shadow Warrior", "Warrior Monk", "Holy Warrior", "Sky Warrior"]],
  ["Ranger", ["Forest Ranger", "Dark Ranger", "Park Ranger"]],
  ["Hunter", ["Witch Hunter", "Demon Hunter", "Dragon Hunter", "Bounty Hunter", "Ghost Hunter", "Monster Hunter"]],
  ["Slayer", ["Demon Slayer", "Giant Slayer", "Troll Slayer"]],
  ["Lord", ["Dark Lord", "Over Lord", "War Lord", "Shadow Lord", "Lich Lord"]],
  ["Maiden", ["Iron Maiden", "Fair Maiden", "Maiden Voyage"]],
  ["Prince", ["Dark Prince", "Crown Prince", "Demon Prince", "Frog Prince"]],
  ["Princess", ["Ice Princess", "Warrior Princess", "Fairy Princess"]],
  ["Hero", ["Folk Hero", "War Hero", "Super Hero"]],
  ["Quest", ["Hero Quest", "Side Quest", "Epic Quest"]],

  // Spirits & undead
  ["Wraith", ["Ring Wraith", "Night Wraith", "Shadow Wraith"]],
  ["Spirit", ["Water Spirit", "Fire Spirit", "Free Spirit", "Evil Spirit", "Spirit Guide", "Holy Spirit"]],
  ["Soul", ["Lost Soul", "Soul Mate", "Soul Stone", "Dark Soul", "Soul Reaper"]],
  ["Skull", ["Skull Cap", "Death Skull", "Skull King"]],
  ["Zombie", ["Zombie King", "Zombie Horde", "Zombie Land"]],
  ["Skeleton", ["Skeleton Key", "Skeleton King", "Skeleton Crew"]],
  ["Monster", ["Sea Monster", "Monster Horde", "Monster Lair"]],

  // Creatures & folk
  ["Serpent", ["Sea Serpent", "Fire Serpent", "Serpent King"]],
  ["Ogre", ["Cave Ogre", "Ogre King", "Swamp Ogre"]],
  ["Orc", ["Orc King", "Orc Horde", "War Orc"]],
  ["Dwarf", ["Dwarf King", "Mountain Dwarf", "Dwarf Lord"]],
  ["Golem", ["Stone Golem", "Iron Golem", "Clay Golem"]],
  ["Spider", ["Cave Spider", "Giant Spider", "Spider Queen", "Spider Bite"]],
  ["Bat", ["Cave Bat", "Fruit Bat", "Bat Swarm"]],
  ["Raven", ["Night Raven", "Raven King", "Black Raven"]],
  ["Owl", ["Night Owl", "Snowy Owl", "Wise Owl"]],
  ["Hound", ["Hell Hound", "Blood Hound", "War Hound"]],

  // Weapons & armour
  ["Blade", ["Magic Blade", "Blood Blade", "Blade Master", "Frost Blade", "Blade Dancer"]],
  ["Dagger", ["Magic Dagger", "Silver Dagger", "Poison Dagger"]],
  ["Spear", ["War Spear", "Spear Head", "Battle Spear"]],
  ["Hammer", ["War Hammer", "Battle Hammer", "Thunder Hammer", "Hammer Fall"]],
  ["Armor", ["Plate Armor", "Magic Armor", "Iron Armor", "Dragon Armor"]],
  ["Cloak", ["Magic Cloak", "Invisible Cloak", "Cloak Room"]],
  ["Robe", ["Wizard Robe", "Magic Robe", "Bath Robe"]],
  ["Hood", ["Robin Hood", "Red Hood", "Hood Wink"]],
  ["Wish", ["Wish Bone", "Death Wish", "Wish Master"]],

  // Dragon anatomy & elements
  ["Egg", ["Golden Egg", "Serpent Egg", "Egg Shell"]],
  ["Scale", ["Serpent Scale", "Scale Armor", "Scale Mail"]],
  ["Claw", ["Dragon Claw", "Bear Claw", "Beast Claw", "Claw Mark"]],
  ["Fang", ["Dragon Fang", "Snake Fang", "White Fang"]],
  ["Wing", ["Dragon Wing", "Bat Wing", "Fairy Wing", "Wing Span", "Demon Wing"]],
  ["Horn", ["War Horn", "Battle Horn", "Devil Horn"]],
  ["Tail", ["Dragon Tail", "Serpent Tail", "Devil Tail"]],
  ["Eye", ["Dragon Eye", "Evil Eye", "Third Eye"]],
  ["Heart", ["Dragon Heart", "Brave Heart", "Heart Stone", "Cold Heart"]],
  ["Bone", ["Bone Dragon", "Bone Sword", "Bone Armor", "Bone Yard"]],
  ["Blood", ["Blood Magic", "Blood Moon", "Blood Mage", "Blood Oath", "Blood Elf"]],
  ["Moon", ["Full Moon", "Moon Stone", "Moon Light", "Moon Elf", "Half Moon"]],
  ["Star", ["Shooting Star", "Star Light", "Morning Star", "North Star", "Dark Star"]],
  ["Storm", ["Storm Cloud", "Thunder Storm", "Storm Lord", "Storm Bringer"]],
  ["Frost", ["Frost Bite", "Frost Wolf", "Frost Mage", "Frost Bolt"]],
  ["Flame", ["Flame Sword", "Eternal Flame", "Blue Flame", "Flame Lord"]],
  ["Shadow", ["Shadow Blade", "Shadow Magic", "Shadow Knight", "Shadow Wolf"]],
  ["Stone", ["Gem Stone", "Stone Wall", "Standing Stone", "Stone Circle"]],
];

export const FANTASY_CARDS: WordCard[] = fromTable(TABLE);
