import type { WordCard } from "../types";
import { fromTable } from "./gen";

// Internet Slang: the easy 1-point word is a slang term or the noun inside
// one; the hard 3-point phrase is the real, widely-known compound it lives
// in (Aura → "Aura Farming"). Curated only — no adjective+noun filler.
// Mixes current Gen Z/meme terms with older millennial-era internet slang.

const TABLE: [string, string[]][] = [
  ["Aura", ["Aura Farming", "Aura Points"]],
  ["Sigma", ["Sigma Male", "Sigma Female"]],
  ["Skibidi", ["Skibidi Toilet"]],
  ["Six", ["Six Seven"]],
  ["Rizz", ["Unspoken Rizz"]],
  ["Era", ["Villain Era", "Flop Era"]],
  ["Grass", ["Touch Grass", "Grass Toucher"]],
  ["Flag", ["Red Flag", "Green Flag", "Beige Flag", "White Flag", "Yellow Flag"]],
  ["Cap", ["No Cap"]],
  ["Rent", ["Rent Free"]],
  ["Character", ["Main Character", "Side Character"]],
  ["Dinner", ["Girl Dinner"]],
  ["Boss", ["Girl Boss", "Boss Fight", "Final Boss"]],
  ["Rot", ["Brain Rot"]],
  ["Core", ["Cottage Core"]],
  ["Meme", ["Meme Lord"]],
  ["Lord", ["Cringe Lord"]],
  ["Check", ["Vibe Check", "Fit Check"]],
  ["Zone", ["Friend Zone"]],
  ["Queen", ["Drama Queen"]],
  ["Life", ["Best Life"]],
  ["Culture", ["Cancel Culture", "Hustle Culture", "Grind Culture"]],
  ["Clout", ["Clout Chaser", "Clout Farming"]],
  ["Trait", ["Toxic Trait"]],
  ["Energy", ["Main Character Energy"]],
  ["Holiday", ["Jet2 Holiday"]],
  ["Tax", ["Fanum Tax"]],
  ["Guy", ["Chill Guy", "Reply Guy"]],
  ["Demure", ["Very Demure"]],
  ["Grimace", ["Grimace Shake"]],
  ["Math", ["Girl Math"]],
  ["Online", ["Chronically Online", "Extremely Online", "Terminally Online"]],

  // Recent memes
  ["Ick", ["The Ick"]],
  ["NPC", ["NPC Energy", "NPC Behavior"]],
  ["Academia", ["Dark Academia"]],
  ["Syndrome", ["Main Character Syndrome"]],
  ["Goat", ["Goat Mode"]],
  ["Different", ["Built Different"]],
  ["Bad", ["Down Bad"]],
  ["Yikes", ["Big Yikes"]],
  ["Ohio", ["Only In Ohio"]],
  ["Alpha", ["Alpha Male"]],
  ["Beta", ["Beta Male"]],
  ["Chad", ["Chad Energy"]],
  ["Boomer", ["OK Boomer", "Boomer Humor"]],
  ["Dad", ["Girl Dad", "Dad Joke", "Dog Dad"]],
  ["Mom", ["Boy Mom", "Mom Friend", "Dog Mom"]],
  ["Launch", ["Soft Launch", "Hard Launch"]],
  ["Tier", ["God Tier"]],
  ["Issue", ["Skill Issue"]],
  ["Cope", ["Cope Harder"]],
  ["Brain", ["Big Brain", "Smooth Brain", "Galaxy Brain"]],
  ["Chef", ["Chef's Kiss"]],
  ["Take", ["Hot Take"]],
  ["Fire", ["Straight Fire"]],
  ["Mood", ["Big Mood", "Whole Mood"]],
  ["Quest", ["Side Quest"]],
  ["Run", ["Speed Run"]],
  ["Span", ["Attention Span"]],
  ["Hit", ["Dopamine Hit"]],
  ["Hustle", ["Side Hustle"]],
  ["Burn", ["Burn Out"]],
  ["Quitting", ["Quiet Quitting"]],
  ["Quit", ["Rage Quit"]],
  ["DMs", ["Slide Into DMs"]],
  ["Content", ["Wholesome Content"]],
  ["Famous", ["Internet Famous"]],
  ["Karma", ["Instant Karma"]],
  ["Behavior", ["Petty Behavior"]],
  ["Estate", ["Free Real Estate"]],

  // Millennial / older internet slang
  ["Read", ["Left On Read"]],
  ["Selfie", ["Selfie Stick"]],
  ["Photo", ["Photo Bomb"]],
  ["Chill", ["Netflix And Chill"]],
  ["Roll", ["Rick Roll"]],
  ["Troll", ["Internet Troll", "Troll Farm"]],
  ["Warrior", ["Keyboard Warrior"]],
  ["Smash", ["Keyboard Smash"]],
  ["Hashtag", ["Hashtag Blessed"]],
  ["Problems", ["First World Problems"]],
  ["Vibes", ["Good Vibes", "Immaculate Vibes"]],
  ["Face", ["Face Palm", "Poker Face", "Duck Face"]],
  ["Cat", ["Nyan Cat"]],
  ["Comic", ["Rage Comic"]],
  ["Chat", ["Chat Room", "Group Chat"]],
  ["Screen", ["Screen Time"]],
  ["Watch", ["Binge Watch"]],
  ["Alert", ["Spoiler Alert"]],
  ["Bait", ["Click Bait"]],
  ["Hole", ["Rabbit Hole"]],
  ["Scroll", ["Doom Scroll"]],
  ["Thursday", ["Throwback Thursday"]],
  ["Brag", ["Humble Brag"]],
  ["Chamber", ["Echo Chamber"]],
  ["Filter", ["No Filter", "Filter Bubble"]],
  ["Section", ["Comment Section"]],
  ["Fake", ["Fake News", "Deep Fake"]],
  ["Plot", ["Plot Twist", "Plot Armor"]],
  ["Video", ["Viral Video"]],
  ["Legend", ["Living Legend", "Absolute Legend"]],
  ["Fail", ["Epic Fail"]],
  ["Win", ["Epic Win"]],
];

export const INTERNET_SLANG_CARDS: WordCard[] = fromTable(TABLE);
