import type { WordCard } from "../types";
import { fromTable } from "./gen";

// Munchies: food, drink and tasty treats. Curated real dishes only — each hard
// phrase is a genuine food/drink term that contains the easy word. Ethnic
// dishes are welcome; culture-specific slang venues are not.

const TABLE: [string, string[]][] = [
  ["Pizza", ["Cheese Pizza", "Pepperoni Pizza", "Deep Dish Pizza", "Pizza Slice", "Pizza Oven", "Veggie Pizza"]],
  ["Burger", ["Cheese Burger", "Beef Burger", "Veggie Burger", "Bacon Burger", "Chicken Burger", "Burger Bun"]],
  ["Rice", ["Fried Rice", "Sticky Rice", "Rice Bowl", "Rice Ball", "Rice Pudding", "Egg Rice", "Rice Cake", "Brown Rice", "Rice Paper"]],
  ["Noodle", ["Egg Noodle", "Rice Noodle", "Instant Noodle", "Noodle Soup", "Glass Noodle", "Noodle Bowl"]],
  ["Soup", ["Chicken Soup", "Tomato Soup", "Onion Soup", "Pumpkin Soup", "Corn Soup", "Miso Soup", "Soup Bowl", "Noodle Soup"]],
  ["Chicken", ["Fried Chicken", "Roast Chicken", "Chicken Wing", "Chicken Rice", "Chicken Soup", "Chicken Nugget", "Butter Chicken", "Chicken Curry", "Chicken Pie", "Chicken Satay"]],
  ["Egg", ["Fried Egg", "Boiled Egg", "Scrambled Egg", "Egg Tart", "Egg Roll", "Deviled Egg", "Egg Sandwich", "Egg Custard"]],
  ["Cheese", ["Grilled Cheese", "Blue Cheese", "Cream Cheese", "Cheese Cake", "Cheese Board", "String Cheese", "Cheese Ball"]],
  ["Cake", ["Sponge Cake", "Carrot Cake", "Cheese Cake", "Rice Cake", "Cup Cake", "Birthday Cake", "Fish Cake", "Fruit Cake", "Chocolate Cake", "Lava Cake"]],
  ["Chocolate", ["Dark Chocolate", "White Chocolate", "Hot Chocolate", "Chocolate Bar", "Chocolate Chip", "Chocolate Cake", "Milk Chocolate"]],
  ["Potato", ["Mashed Potato", "Baked Potato", "Sweet Potato", "Potato Chip", "Potato Salad", "Potato Wedge"]],
  ["Bread", ["Garlic Bread", "Flat Bread", "Banana Bread", "Corn Bread", "Bread Roll", "White Bread", "Bread Stick", "Ginger Bread"]],
  ["Pie", ["Apple Pie", "Meat Pie", "Pumpkin Pie", "Chicken Pie", "Pecan Pie", "Pie Crust"]],
  ["Roll", ["Spring Roll", "Egg Roll", "Sausage Roll", "Sushi Roll", "Cinnamon Roll", "Bread Roll", "Summer Roll"]],
  ["Curry", ["Green Curry", "Red Curry", "Chicken Curry", "Fish Curry", "Curry Puff", "Curry Sauce"]],
  ["Fish", ["Fish Cake", "Fish Ball", "Fish Finger", "Fish Pie", "Fried Fish", "Fish Taco", "Fish Soup"]],
  ["Tea", ["Green Tea", "Milk Tea", "Bubble Tea", "Iced Tea", "Herbal Tea", "Ginger Tea", "Tea Pot", "Tea Cup", "Sweet Tea"]],
  ["Coffee", ["Iced Coffee", "Black Coffee", "Coffee Bean", "Coffee Cup", "Coffee Cake", "Coffee Shop", "Coffee Pot"]],
  ["Milk", ["Milk Shake", "Milk Tea", "Warm Milk", "Milk Bar", "Coconut Milk", "Almond Milk", "Milk Bottle"]],
  ["Ice", ["Ice Cream", "Ice Cube", "Shaved Ice", "Ice Lolly", "Ice Pop", "Iced Tea"]],
  ["Cream", ["Ice Cream", "Whipped Cream", "Sour Cream", "Cream Puff", "Cream Cheese", "Cream Soda"]],
  ["Sauce", ["Soy Sauce", "Hot Sauce", "Fish Sauce", "Tomato Sauce", "Sweet Sauce", "Chilli Sauce", "Peanut Sauce"]],
  ["Juice", ["Orange Juice", "Apple Juice", "Fruit Juice", "Grape Juice", "Juice Box", "Carrot Juice"]],
  ["Bun", ["Steamed Bun", "Pork Bun", "Sticky Bun", "Hot Cross Bun", "Custard Bun"]],
  ["Dumpling", ["Pork Dumpling", "Soup Dumpling", "Fried Dumpling", "Steamed Dumpling", "Shrimp Dumpling"]],
  ["Fruit", ["Fruit Salad", "Fruit Cup", "Fruit Tart", "Fruit Juice", "Dragon Fruit", "Star Fruit", "Passion Fruit", "Fruit Cake"]],
  ["Salad", ["Fruit Salad", "Potato Salad", "Green Salad", "Egg Salad", "Caesar Salad", "Salad Bowl", "Salad Bar"]],
  ["Sandwich", ["Egg Sandwich", "Club Sandwich", "Ham Sandwich", "Ice Cream Sandwich", "Sandwich Bread"]],
  ["Beef", ["Beef Burger", "Beef Stew", "Roast Beef", "Beef Noodle", "Ground Beef", "Beef Rendang", "Corned Beef", "Beef Ball"]],
  ["Pork", ["Pork Chop", "Pork Bun", "Pork Belly", "Roast Pork", "Pork Ball", "Pulled Pork", "Pork Rib"]],
  ["Corn", ["Sweet Corn", "Corn Bread", "Pop Corn", "Corn Dog", "Corn Chip", "Corn Soup", "Corn Cob"]],
  ["Toast", ["French Toast", "Kaya Toast", "Garlic Toast", "Cheese Toast", "Toast Bread"]],
  ["Pancake", ["Potato Pancake", "Fluffy Pancake", "Pancake Stack", "Pancake Batter"]],
  ["Wrap", ["Chicken Wrap", "Veggie Wrap", "Tortilla Wrap", "Wrap Roll"]],
  ["Taco", ["Fish Taco", "Beef Taco", "Soft Taco", "Taco Salad", "Taco Shell"]],

  // --- Meat & seafood ---
  ["Bacon", ["Bacon Strip", "Bacon Bit", "Bacon Roll", "Turkey Bacon"]],
  ["Sausage", ["Pork Sausage", "Beef Sausage", "Sausage Link", "Breakfast Sausage"]],
  ["Ham", ["Ham Bone", "Honey Ham", "Ham Steak", "Glazed Ham"]],
  ["Steak", ["Beef Steak", "Steak Sauce", "Rump Steak", "Steak House"]],
  ["Lamb", ["Lamb Chop", "Lamb Curry", "Roast Lamb", "Lamb Stew", "Lamb Shank"]],
  ["Duck", ["Roast Duck", "Peking Duck", "Duck Egg", "Crispy Duck"]],
  ["Rib", ["BBQ Rib", "Spare Rib", "Beef Rib", "Rib Eye"]],
  ["Wing", ["Buffalo Wing", "Wing Sauce", "Hot Wing"]],
  ["Shrimp", ["Shrimp Cocktail", "Fried Shrimp", "Shrimp Roll", "Popcorn Shrimp"]],
  ["Prawn", ["Prawn Cracker", "Prawn Cocktail", "Tiger Prawn", "Prawn Toast"]],
  ["Crab", ["Crab Cake", "Crab Stick", "Chilli Crab", "Crab Meat", "Crab Rangoon"]],
  ["Lobster", ["Lobster Roll", "Lobster Bisque", "Lobster Tail"]],
  ["Oyster", ["Oyster Sauce", "Oyster Bar", "Fried Oyster"]],
  ["Tofu", ["Fried Tofu", "Silken Tofu", "Tofu Soup", "Mapo Tofu"]],

  // --- Veg & staples ---
  ["Bean", ["Baked Bean", "Green Bean", "Bean Curd", "Bean Sprout", "Red Bean", "Bean Paste"]],
  ["Pea", ["Green Pea", "Snow Pea", "Split Pea", "Pea Soup", "Chick Pea"]],
  ["Garlic", ["Garlic Sauce", "Garlic Prawn", "Garlic Rice", "Garlic Butter"]],
  ["Onion", ["Onion Ring", "Spring Onion", "Fried Onion", "Green Onion"]],
  ["Pepper", ["Bell Pepper", "Black Pepper", "Chilli Pepper", "Stuffed Pepper", "Pepper Steak"]],
  ["Mushroom", ["Mushroom Soup", "Button Mushroom", "Mushroom Sauce", "Fried Mushroom"]],
  ["Tomato", ["Cherry Tomato", "Tomato Paste", "Tomato Juice"]],
  ["Carrot", ["Carrot Stick", "Baby Carrot", "Carrot Soup"]],
  ["Pumpkin", ["Pumpkin Spice", "Pumpkin Bread", "Pumpkin Seed"]],
  ["Pickle", ["Dill Pickle", "Pickle Juice", "Fried Pickle", "Sweet Pickle"]],
  ["Olive", ["Olive Oil", "Black Olive", "Green Olive"]],
  ["Pasta", ["Pasta Sauce", "Pasta Salad", "Pasta Bake", "Pasta Bowl"]],
  ["Nut", ["Pea Nut", "Cashew Nut", "Nut Butter", "Mixed Nut", "Dough Nut"]],

  // --- Sweets & baking ---
  ["Butter", ["Peanut Butter", "Butter Cake", "Butter Cream", "Almond Butter", "Butter Cookie"]],
  ["Jam", ["Fruit Jam", "Jam Toast", "Jam Tart", "Jam Roll"]],
  ["Honey", ["Honey Toast", "Honey Cake", "Honey Comb", "Honey Bun"]],
  ["Syrup", ["Maple Syrup", "Corn Syrup", "Chocolate Syrup"]],
  ["Sugar", ["Brown Sugar", "Sugar Cube", "Icing Sugar", "Sugar Cane", "Sugar Cookie"]],
  ["Cookie", ["Cookie Dough", "Cookie Jar", "Fortune Cookie", "Oat Cookie"]],
  ["Biscuit", ["Butter Biscuit", "Digestive Biscuit", "Cheese Biscuit"]],
  ["Cracker", ["Cheese Cracker", "Cream Cracker", "Rice Cracker", "Graham Cracker"]],
  ["Chip", ["Chocolate Chip", "Tortilla Chip", "Chip Dip", "Banana Chip"]],
  ["Fries", ["French Fries", "Curly Fries", "Chili Fries", "Cheese Fries"]],
  ["Waffle", ["Belgian Waffle", "Waffle Cone", "Waffle Fries"]],
  ["Donut", ["Donut Hole", "Jelly Donut", "Glazed Donut"]],
  ["Muffin", ["Blueberry Muffin", "English Muffin", "Corn Muffin", "Muffin Top"]],
  ["Tart", ["Pop Tart", "Custard Tart", "Tart Shell"]],
  ["Pudding", ["Bread Pudding", "Christmas Pudding", "Black Pudding", "Chia Pudding"]],
  ["Jelly", ["Jelly Bean", "Jelly Roll", "Grape Jelly"]],
  ["Candy", ["Cotton Candy", "Candy Cane", "Candy Bar", "Rock Candy", "Candy Corn"]],
  ["Bagel", ["Bagel Bite", "Sesame Bagel", "Plain Bagel"]],
  ["Pretzel", ["Soft Pretzel", "Pretzel Stick", "Salted Pretzel"]],
  ["Cereal", ["Breakfast Cereal", "Cereal Bowl", "Cereal Bar"]],
  ["Oat", ["Oat Meal", "Oat Cake", "Oat Milk", "Oat Bar"]],
  ["Yogurt", ["Greek Yogurt", "Frozen Yogurt", "Yogurt Drink"]],
  ["Pastry", ["Danish Pastry", "Puff Pastry", "Pastry Chef"]],

  // --- Fruit ---
  ["Berry", ["Straw Berry", "Blue Berry", "Black Berry", "Berry Tart"]],
  ["Apple", ["Candy Apple", "Apple Sauce", "Apple Crumble", "Apple Tart", "Caramel Apple"]],
  ["Banana", ["Banana Split", "Banana Cake", "Banana Milk", "Banana Muffin"]],
  ["Mango", ["Mango Juice", "Mango Salad", "Mango Lassi", "Dried Mango"]],
  ["Lemon", ["Lemon Tart", "Lemon Cake", "Lemon Meringue", "Lemon Curd", "Lemon Bar"]],
  ["Orange", ["Orange Cake", "Orange Chicken", "Orange Peel", "Blood Orange"]],
  ["Coconut", ["Coconut Rice", "Coconut Cream", "Coconut Water", "Coconut Cake"]],

  // --- Flavours & extras ---
  ["Vanilla", ["Vanilla Bean", "Vanilla Cake", "Vanilla Latte", "Vanilla Custard"]],
  ["Caramel", ["Salted Caramel", "Caramel Latte", "Caramel Corn", "Caramel Sauce"]],
  ["Mint", ["Mint Chocolate", "Mint Tea", "Mint Sauce", "Mint Candy"]],
  ["Cocoa", ["Hot Cocoa", "Cocoa Powder", "Cocoa Bean", "Cocoa Butter"]],

  // --- Dishes & drinks ---
  ["Stew", ["Fish Stew", "Irish Stew", "Veggie Stew", "Chicken Stew"]],
  ["Broth", ["Bone Broth", "Chicken Broth", "Beef Broth"]],
  ["Gravy", ["Onion Gravy", "Gravy Boat", "Brown Gravy"]],
  ["Dip", ["Cheese Dip", "Onion Dip", "Salsa Dip"]],
  ["Sushi", ["Sushi Bar", "Sushi Rice", "Sushi Chef"]],
  ["Kebab", ["Chicken Kebab", "Shish Kebab", "Doner Kebab"]],
  ["Wine", ["Red Wine", "White Wine", "Mulled Wine", "Rice Wine"]],
  ["Beer", ["Root Beer", "Ginger Beer", "Draft Beer", "Craft Beer"]],
  ["Soda", ["Soda Water", "Baking Soda", "Soda Pop", "Orange Soda", "Club Soda"]],
  ["Smoothie", ["Fruit Smoothie", "Berry Smoothie", "Mango Smoothie", "Green Smoothie"]],
  ["Latte", ["Chai Latte", "Iced Latte", "Latte Art"]],
];

export const MUNCHIES_CARDS: WordCard[] = fromTable(TABLE);
