import type { WordCard } from "../types";
import { build } from "./gen";

// Sunny Singapore: local food, places, culture and slang. The easy 1-point word
// is a plain word that appears in the hard 3-point phrase (build() drops any
// card where it doesn't — pure foreign single words like "Laksa" are left out
// or reframed, e.g. "Curry Laksa").
export const SINGAPORE_CARDS: WordCard[] = build([
  // Food & drink
  { easy: "Rice", hard: "Chicken Rice" },
  { easy: "Crab", hard: "Chilli Crab" },
  { easy: "Curry", hard: "Curry Laksa" },
  { easy: "Char", hard: "Char Kway Teow" },
  { easy: "Mee", hard: "Hokkien Mee" },
  { easy: "Mee", hard: "Wanton Mee" },
  { easy: "Prawn", hard: "Prawn Mee" },
  { easy: "Prawn", hard: "Cereal Prawn" },
  { easy: "Chicken", hard: "Chicken Satay" },
  { easy: "Stick", hard: "Satay Stick" },
  { easy: "Duck", hard: "Duck Rice" },
  { easy: "Toast", hard: "Kaya Toast" },
  { easy: "Ice", hard: "Ice Kacang" },
  { easy: "Durian", hard: "King Durian" },
  { easy: "Fish", hard: "Fish Head Curry" },
  { easy: "Carrot", hard: "Fried Carrot Cake" },
  { easy: "Fruit", hard: "Fruit Rojak" },
  { easy: "Roll", hard: "Popiah Roll" },
  { easy: "Puff", hard: "Curry Puff" },
  { easy: "Chicken", hard: "Hainanese Chicken" },
  { easy: "Milo", hard: "Milo Dinosaur" },
  { easy: "Ball", hard: "Fish Ball" },
  { easy: "Jam", hard: "Kaya Jam" },
  { easy: "Porridge", hard: "Frog Porridge" },
  { easy: "Fried", hard: "Fried Bee Hoon" },
  { easy: "Chilli", hard: "Sambal Chilli" },
  { easy: "Egg", hard: "Soft Boiled Egg" },
  { easy: "Egg", hard: "Century Egg" },
  { easy: "Prata", hard: "Egg Prata" },
  { easy: "Stingray", hard: "Sambal Stingray" },
  { easy: "Sugar", hard: "Sugar Cane Juice" },
  { easy: "Bean", hard: "Red Bean Ice" },
  { easy: "Tart", hard: "Egg Tart" },
  { easy: "Bun", hard: "Steamed Bun" },

  // Places & landmarks
  { easy: "Bay", hard: "Marina Bay" },
  { easy: "Statue", hard: "Merlion Statue" },
  { easy: "Island", hard: "Sentosa Island" },
  { easy: "Road", hard: "Orchard Road" },
  { easy: "Bay", hard: "Gardens By The Bay" },
  { easy: "Flyer", hard: "Singapore Flyer" },
  { easy: "Town", hard: "China Town" },
  { easy: "India", hard: "Little India" },
  { easy: "Quay", hard: "Clarke Quay" },
  { easy: "Coast", hard: "East Coast Park" },
  { easy: "Airport", hard: "Changi Airport" },
  { easy: "Waterfall", hard: "Jewel Waterfall" },
  { easy: "Hill", hard: "Bukit Timah Hill" },
  { easy: "Hotel", hard: "Raffles Hotel" },
  { easy: "Flat", hard: "HDB Flat" },
  { easy: "Train", hard: "MRT Train" },
  { easy: "Centre", hard: "Hawker Centre" },
  { easy: "Deck", hard: "Void Deck" },
  { easy: "Gardens", hard: "Botanic Gardens" },
  { easy: "Safari", hard: "Night Safari" },
  { easy: "Zoo", hard: "Singapore Zoo" },
  { easy: "Studios", hard: "Universal Studios" },
  { easy: "Grove", hard: "Supertree Grove" },
  { easy: "Bird", hard: "Jurong Bird Park" },
  { easy: "Sands", hard: "Marina Bay Sands" },
  { easy: "Bridge", hard: "Helix Bridge" },
  { easy: "Fountain", hard: "Fountain Of Wealth" },
  { easy: "Temple", hard: "Buddha Tooth Temple" },
  { easy: "Mosque", hard: "Sultan Mosque" },
  { easy: "River", hard: "Singapore River" },
  { easy: "Lane", hard: "Haji Lane" },
  { easy: "Market", hard: "Tekka Market" },
  { easy: "Orchard", hard: "Ion Orchard" },
  { easy: "Fort", hard: "Fort Canning" },
  { easy: "Reservoir", hard: "MacRitchie Reservoir" },
  { easy: "Beach", hard: "Palawan Beach" },
  { easy: "Cable", hard: "Cable Car" },

  // Culture & slang
  { easy: "Seat", hard: "Chope Seat" },
  { easy: "Time", hard: "Makan Time" },
  { easy: "Auntie", hard: "Kopitiam Auntie" },
  { easy: "Uncle", hard: "Taxi Uncle" },
  { easy: "Packet", hard: "Red Packet" },
  { easy: "Year", hard: "Chinese New Year" },
  { easy: "Day", hard: "National Day" },
  { easy: "Queue", hard: "Kiasu Queue" },
  { easy: "Shiok", hard: "Very Shiok" },
  { easy: "Can", hard: "Can Lah" },
  { easy: "Wet", hard: "Wet Market" },
  { easy: "Slipper", hard: "Rubber Slipper" },
  { easy: "Card", hard: "Ez Link Card" },
  { easy: "Gantry", hard: "ERP Gantry" },
  { easy: "Car", hard: "COE Car" },
  { easy: "Lantern", hard: "Mid Autumn Lantern" },
  { easy: "Dragon", hard: "Dragon Dance" },
  { easy: "Lion", hard: "Lion Dance" },
  { easy: "Fine", hard: "Fine City" },
  { easy: "Gum", hard: "No Chewing Gum" },
  { easy: "Exam", hard: "Mug For Exam" },
  { easy: "Boss", hard: "Big Boss" },
  { easy: "Buddy", hard: "Best Buddy" },
  { easy: "Tissue", hard: "Tissue Packet" },
  { easy: "Weather", hard: "Humid Weather" },
  { easy: "Storm", hard: "Afternoon Storm" },
  { easy: "Fan", hard: "Ceiling Fan" },
  { easy: "Class", hard: "Tuition Class" },
  { easy: "Service", hard: "National Service" },
  { easy: "Lights", hard: "Deepavali Lights" },
  { easy: "Talk", hard: "Singlish Talk" },
  { easy: "Kite", hard: "Kite Flying" },

  // More food & drink
  { easy: "Noodle", hard: "Fish Ball Noodle" },
  { easy: "Sauce", hard: "Satay Sauce" },
  { easy: "Laksa", hard: "Katong Laksa" },
  { easy: "Kaya", hard: "Kaya Butter Toast" },
  { easy: "Kopi", hard: "Kopi O" },
  { easy: "Teh", hard: "Teh Tarik" },
  { easy: "Bak", hard: "Bak Kut Teh" },
  { easy: "Kueh", hard: "Kueh Lapis" },
  { easy: "Cake", hard: "Pandan Cake" },
  { easy: "Pandan", hard: "Pandan Chiffon" },
  { easy: "Chendol", hard: "Coconut Chendol" },
  { easy: "Rojak", hard: "Chinese Rojak" },
  { easy: "Popiah", hard: "Fresh Popiah" },
  { easy: "Nasi", hard: "Nasi Lemak" },
  { easy: "Wanton", hard: "Fried Wanton" },
  { easy: "Dumpling", hard: "Prawn Dumpling" },
  { easy: "Otah", hard: "Grilled Otah" },

  // More places
  { easy: "Park", hard: "Merlion Park" },
  { easy: "Mall", hard: "Shopping Mall" },
  { easy: "Street", hard: "Bugis Street" },
  { easy: "Junction", hard: "Bugis Junction" },
  { easy: "City", hard: "Lion City" },
  { easy: "Port", hard: "Singapore Port" },
  { easy: "Station", hard: "MRT Station" },
  { easy: "Stop", hard: "Bus Stop" },
  { easy: "Mount", hard: "Mount Faber" },

  // More culture & slang
  { easy: "Kiasu", hard: "Very Kiasu" },
  { easy: "Makan", hard: "Makan Session" },
  { easy: "Chope", hard: "Chope Table" },
  { easy: "Hawker", hard: "Hawker Stall" },
  { easy: "Stall", hard: "Food Stall" },
  { easy: "Kopitiam", hard: "Old Kopitiam" },
  { easy: "Aircon", hard: "Aircon Room" },
  { easy: "Kampong", hard: "Kampong Spirit" },

  // More Singlish slang
  { easy: "Sotong", hard: "Blur Sotong" },
  { easy: "Spider", hard: "Kancheong Spider" },
  { easy: "Kaki", hard: "Makan Kaki" },
  { easy: "Towkay", hard: "Big Towkay" },
  { easy: "Paiseh", hard: "Very Paiseh" },
  { easy: "Sian", hard: "So Sian" },
  { easy: "Atas", hard: "Very Atas" },
  { easy: "Jialat", hard: "Very Jialat" },
  { easy: "Kaypoh", hard: "Very Kaypoh" },
  { easy: "Lepak", hard: "Lepak Corner" },
  { easy: "Sabo", hard: "Sabo King" },
  { easy: "Bojio", hard: "Always Bojio" },
  { easy: "Dabao", hard: "Dabao Lunch" },
  { easy: "Steady", hard: "Steady Lah" },
  { easy: "Chio", hard: "Chio Bu" },
  { easy: "Kiam", hard: "Very Kiam" },
  { easy: "Siao", hard: "Siao Lang" },

  // More festivals & everyday culture
  { easy: "Reunion", hard: "Reunion Dinner" },
  { easy: "Pasar", hard: "Pasar Malam" },
  { easy: "Bazaar", hard: "Ramadan Bazaar" },
  { easy: "Raya", hard: "Hari Raya" },
  { easy: "Wayang", hard: "Wayang Show" },
  { easy: "Chingay", hard: "Chingay Parade" },
  { easy: "Cab", hard: "Taxi Cab" },
  { easy: "Botak", hard: "Botak Head" },
]);
