import type { WordCard } from "../types";
import { build } from "./gen";

// TV Shows: same shape as Movies — the hard 3-point answer is a famous show
// title, the easy 1-point word is a word taken *from the title* so it
// satisfies containment. One-word titles (Friends, Seinfeld, Cheers, Lost)
// can't be used and are left out.
export const TV_SHOW_CARDS: WordCard[] = build([
  // 2000s-2020s
  { easy: "Bad", hard: "Breaking Bad" },
  { easy: "Thrones", hard: "Game Of Thrones" },
  { easy: "Dead", hard: "The Walking Dead" },
  { easy: "Things", hard: "Stranger Things" },
  { easy: "Office", hard: "The Office" },
  { easy: "Mother", hard: "How I Met Your Mother" },
  { easy: "Theory", hard: "The Big Bang Theory" },
  { easy: "Nine", hard: "Brooklyn Nine Nine" },
  { easy: "Horror", hard: "American Horror Story" },
  { easy: "Crown", hard: "The Crown" },
  { easy: "Heist", hard: "Money Heist" },
  { easy: "Abbey", hard: "Downton Abbey" },
  { easy: "Cards", hard: "House Of Cards" },
  { easy: "Family", hard: "Modern Family" },
  { easy: "Black", hard: "Orange Is The New Black" },
  { easy: "Girl", hard: "Gossip Girl" },
  { easy: "Girl", hard: "New Girl" },
  { easy: "Girls", hard: "Two Broke Girls" },
  { easy: "Girls", hard: "Gilmore Girls" },
  { easy: "Game", hard: "Squid Game" },
  { easy: "Boys", hard: "The Boys" },
  { easy: "Middle", hard: "Malcolm In The Middle" },
  { easy: "Queens", hard: "King Of Queens" },
  { easy: "Rock", hard: "30 Rock" },
  { easy: "Development", hard: "Arrested Development" },
  { easy: "Sunny", hard: "Its Always Sunny In Philadelphia" },
  { easy: "Recreation", hard: "Parks And Recreation" },
  { easy: "Enthusiasm", hard: "Curb Your Enthusiasm" },
  { easy: "Break", hard: "Prison Break" },
  { easy: "Housewives", hard: "Desperate Housewives" },
  { easy: "Hill", hard: "One Tree Hill" },
  { easy: "Diaries", hard: "The Vampire Diaries" },
  { easy: "Creek", hard: "Schitts Creek" },
  { easy: "Anatomy", hard: "Greys Anatomy" },
  { easy: "Anarchy", hard: "Sons Of Anarchy" },
  { easy: "Wing", hard: "The West Wing" },
  { easy: "Blinders", hard: "Peaky Blinders" },
  { easy: "Tale", hard: "The Handmaids Tale" },
  { easy: "Liars", hard: "Pretty Little Liars" },
  { easy: "Call", hard: "Better Call Saul" },
  { easy: "Avatar", hard: "Avatar The Last Airbender" },

  // 90s-2000s sitcoms
  { easy: "Men", hard: "Mad Men" },
  { easy: "Men", hard: "Two And A Half Men" },
  { easy: "Raymond", hard: "Everybody Loves Raymond" },
  { easy: "Children", hard: "Married With Children" },
  { easy: "House", hard: "Full House" },
  { easy: "Improvement", hard: "Home Improvement" },
  { easy: "Prince", hard: "The Fresh Prince Of Bel Air" },
  { easy: "Witch", hard: "Sabrina The Teenage Witch" },
  { easy: "World", hard: "Boy Meets World" },
  { easy: "Sun", hard: "3rd Rock From The Sun" },
  { easy: "Matters", hard: "Family Matters" },
  { easy: "Bell", hard: "Saved By The Bell" },
  { easy: "Nanny", hard: "The Nanny" },
  { easy: "Show", hard: "That 70s Show" },
  { easy: "Grace", hard: "Will And Grace" },
  { easy: "Files", hard: "The X Files" },
  { easy: "Order", hard: "Law And Order" },
  { easy: "Vampire", hard: "Buffy The Vampire Slayer" },
  { easy: "Creek", hard: "Dawsons Creek" },
  { easy: "Hills", hard: "Beverly Hills 90210" },

  // Classic sitcoms & dramas (70s-80s)
  { easy: "Pains", hard: "Growing Pains" },
  { easy: "Boss", hard: "Whos The Boss" },
  { easy: "Ties", hard: "Family Ties" },
  { easy: "Strangers", hard: "Perfect Strangers" },
  { easy: "Days", hard: "Happy Days" },
  { easy: "Times", hard: "Good Times" },
  { easy: "Women", hard: "Designing Women" },
  { easy: "Years", hard: "The Wonder Years" },
  { easy: "Peaks", hard: "Twin Peaks" },
  { easy: "Team", hard: "The A Team" },
  { easy: "Vice", hard: "Miami Vice" },
  { easy: "Rider", hard: "Knight Rider" },
]);
