import type { WordCard } from "./types";

// Down Under: Aussie animals, servo snacks, slang and landmarks.
export const DOWN_UNDER_CARDS: WordCard[] = [
  { easy: "Roo", hard: "Boxing Kangaroo" },
  { easy: "Joey", hard: "Baby Joey" },
  { easy: "Koala", hard: "Sleepy Koala" },
  { easy: "Emu", hard: "Giant Emu" },
  { easy: "Dingo", hard: "Wild Dingo" },
  { easy: "Croc", hard: "Salt Water Croc" },
  { easy: "Shark", hard: "Great White Shark" },
  { easy: "Snake", hard: "Brown Snake" },
  { easy: "Spider", hard: "Huntsman Spider" },
  { easy: "Wombat", hard: "Chubby Wombat" },
  { easy: "Platypus", hard: "Duck Billed Platypus" },
  { easy: "Echidna", hard: "Spiny Echidna" },
  { easy: "Quokka", hard: "Smiling Quokka" },
  { easy: "Possum", hard: "Ring Tail Possum" },
  { easy: "Bat", hard: "Fruit Bat" },
  { easy: "Fly", hard: "Bush Fly" },
  { easy: "Parrot", hard: "White Cockatoo" },
  { easy: "Bird", hard: "Laughing Kookaburra" },
  { easy: "Wallaby", hard: "Rock Wallaby" },
  { easy: "Pie", hard: "Meat Pie" },
  { easy: "Snag", hard: "Sausage Sizzle" },
  { easy: "Chook", hard: "Roast Chook" },
  { easy: "Prawn", hard: "Prawn On The Barbie" },
  { easy: "Roll", hard: "Sausage Roll" },
  { easy: "Toast", hard: "Vegemite Toast" },
  { easy: "Tim Tam", hard: "Choc Tim Tam" },
  { easy: "Cake", hard: "Coconut Lamington" },
  { easy: "Pav", hard: "Fruit Pavlova" },
  { easy: "Bread", hard: "Fairy Bread" },
  { easy: "Bikkie", hard: "Anzac Bikkie" },
  { easy: "Chips", hard: "Hot Chips" },
  { easy: "Mate", hard: "G'day Mate" },
  { easy: "Thongs", hard: "Rubber Thongs" },
  { easy: "Ute", hard: "Farm Ute" },
  { easy: "Esky", hard: "Cold Esky" },
  { easy: "Footy", hard: "Aussie Footy" },
  { easy: "Barbie", hard: "Backyard Barbie" },
  { easy: "Arvo", hard: "Lazy Arvo" },
  { easy: "Servo", hard: "Petrol Servo" },
  { easy: "Sunnies", hard: "Cool Sunnies" },
  { easy: "Doona", hard: "Warm Doona" },
  { easy: "Dunny", hard: "Outback Dunny" },
  { easy: "Tinnie", hard: "Cold Tinnie" },
  { easy: "Bang", hard: "Wooden Boomerang" },
  { easy: "Pipe", hard: "Droning Didgeridoo" },
  { easy: "Reef", hard: "Great Barrier Reef" },
  { easy: "Rock", hard: "Uluru Rock" },
  { easy: "Bush", hard: "The Outback" },
  { easy: "Beach", hard: "Bondi Beach" },
  { easy: "Surf", hard: "Surf Life Saver" },
  { easy: "Tree", hard: "Gum Tree" },
  { easy: "Star", hard: "Southern Cross" },
  { easy: "Hat", hard: "Cork Hat" },
  { easy: "House", hard: "Opera House" },
];
