import type { WordCard } from "./types";

// The default "Everyday" deck is large (2000+ words) so cards rarely repeat.
// Rather than hand-list ~1000 pairs, it's generated from a curated table of
// base words, each paired with a list of real, recognisable compounds. The
// base is the easy 1-point word; each compound is a harder 3-point phrase.
//
// Everything is deduped by the hard phrase, so overlaps between bases (e.g.
// "Fire Ball" under both "Fire" and "Ball") only appear once.

type Entry = [easy: string, hards: string[]];

const TABLE: Entry[] = [
  ["Fire", ["Camp Fire", "Fire Fly", "Fire Truck", "Fire Wood", "Fire Place", "Fire Works", "Fire Man", "Bon Fire", "Fire Drill", "Fire Alarm", "Cross Fire", "Fire Ball"]],
  ["Water", ["Water Fall", "Water Mill", "Water Melon", "Under Water", "Rain Water", "Salt Water", "Water Slide", "Water Gun", "Water Wheel", "Sea Water", "Water Proof", "Water Colour"]],
  ["Sun", ["Sun Shine", "Sun Flower", "Sun Burn", "Sun Set", "Sun Rise", "Sun Glasses", "Sun Dial", "Sun Roof", "Sun Block", "Sun Light", "Sun Bath"]],
  ["Moon", ["Full Moon", "Moon Light", "Moon Walk", "Half Moon", "Honey Moon", "Moon Beam", "New Moon", "Moon Shine", "Moon Landing"]],
  ["Star", ["Movie Star", "Star Fish", "Shooting Star", "Rock Star", "Star Light", "North Star", "Pop Star", "Star Dust", "Star Gazer"]],
  ["Rain", ["Rain Bow", "Rain Coat", "Rain Drop", "Rain Forest", "Acid Rain", "Rain Fall", "Rain Cloud", "Rain Storm"]],
  ["Snow", ["Snow Man", "Snow Ball", "Snow Flake", "Snow Storm", "Snow Plow", "Snow Board", "Snow Fall", "Snow Angel", "Snow Shoe"]],
  ["Wind", ["Wind Mill", "Wind Screen", "Whirl Wind", "Wind Pipe", "Wind Surf", "Wind Chime", "Head Wind", "Wind Fall"]],
  ["Sea", ["Sea Shell", "Sea Weed", "Sea Horse", "Sea Sick", "Sea Food", "Sea Shore", "Sea Gull", "Sea Side", "Sea Lion", "Sea Salt"]],
  ["Fish", ["Gold Fish", "Jelly Fish", "Cat Fish", "Sword Fish", "Fish Hook", "Fish Bowl", "Fish Tank", "Fish Cake", "Fish Net", "Fish Finger"]],
  ["Bird", ["Bird Bath", "Black Bird", "Bird House", "Bird Song", "Bird Cage", "Song Bird", "Bird Seed", "Lady Bird", "Bird Nest"]],
  ["Cat", ["Copy Cat", "Wild Cat", "Cat Nap", "Cat Walk", "Cat Nip", "Bob Cat", "Tom Cat", "Cat Call"]],
  ["Dog", ["Hot Dog", "Bull Dog", "Dog House", "Sheep Dog", "Watch Dog", "Lap Dog", "Dog Tag", "Guard Dog", "Dog Food"]],
  ["Horse", ["Sea Horse", "Horse Shoe", "Race Horse", "Horse Back", "Horse Play", "Rocking Horse", "War Horse", "Work Horse", "Horse Power"]],
  ["Cow", ["Cow Boy", "Cow Girl", "Cow Bell", "Cow Hide", "Cow Shed", "Mad Cow", "Sea Cow"]],
  ["Pig", ["Guinea Pig", "Pig Pen", "Pig Tail", "Pig Sty", "Pig Skin"]],
  ["Sheep", ["Sheep Dog", "Sheep Skin", "Black Sheep", "Sheep Pen"]],
  ["Snake", ["Rattle Snake", "Snake Skin", "Snake Bite", "Sea Snake", "Snake Pit", "Corn Snake", "Grass Snake"]],
  ["Bear", ["Teddy Bear", "Polar Bear", "Bear Hug", "Grizzly Bear", "Bear Trap", "Sun Bear", "Brown Bear", "Care Bear"]],
  ["Bee", ["Bumble Bee", "Bee Hive", "Spelling Bee", "Queen Bee", "Bee Line", "Honey Bee", "Bee Sting", "Bee Keeper"]],
  ["Ant", ["Fire Ant", "Ant Hill", "Ant Eater", "Carpenter Ant", "Army Ant", "Worker Ant"]],
  ["Fly", ["Butter Fly", "Dragon Fly", "Fire Fly", "May Fly", "Horse Fly", "Fruit Fly", "House Fly", "Fly Trap", "Fly Swatter", "Fly Paper"]],
  ["Frog", ["Bull Frog", "Tree Frog", "Frog Spawn", "Leap Frog", "Pond Frog"]],
  ["Duck", ["Rubber Duck", "Duck Pond", "Sitting Duck", "Duck Bill", "Wild Duck", "Duck Weed"]],
  ["Worm", ["Earth Worm", "Silk Worm", "Ear Worm", "Book Worm", "Glow Worm", "Round Worm", "Ring Worm", "Wood Worm", "Tape Worm"]],
  ["Book", ["Note Book", "Text Book", "Book Shelf", "Book Mark", "Book Store", "Cook Book", "Book Case", "Comic Book", "Scrap Book", "Year Book", "Sketch Book", "Book End", "Face Book"]],
  ["Foot", ["Foot Ball", "Foot Print", "Foot Path", "Foot Step", "Bare Foot", "Foot Note", "Foot Bridge", "Foot Stool", "Big Foot", "Foot Hill", "Foot Rest"]],
  ["Hand", ["Hand Shake", "Hand Bag", "Hand Cuff", "Hand Ball", "Hand Made", "Hand Rail", "Hand Book", "Hand Writing", "Hand Print", "Second Hand", "Farm Hand", "Hand Stand", "Hand Gun"]],
  ["Eye", ["Eye Ball", "Eye Brow", "Eye Lash", "Eye Lid", "Eye Sight", "Black Eye", "Eye Drop", "Eagle Eye", "Eye Liner", "Eye Wear", "Eye Patch", "Fish Eye"]],
  ["Head", ["Head Ache", "Fore Head", "Head Light", "Head Line", "Head Phone", "Egg Head", "Hot Head", "Head Band", "Head Rest", "Head Set", "Head Master", "Red Head", "Head Stone", "Head Count"]],
  ["Hair", ["Hair Cut", "Hair Brush", "Hair Pin", "Hair Line", "Hair Style", "Hair Band", "Hair Spray", "Hair Do", "Hair Dryer"]],
  ["Tooth", ["Sweet Tooth", "Tooth Brush", "Tooth Paste", "Tooth Ache", "Tooth Pick", "Blue Tooth", "Saw Tooth", "Tooth Fairy"]],
  ["Nose", ["Runny Nose", "Nose Dive", "Nose Bleed", "Nose Ring", "Brown Nose", "Button Nose"]],
  ["Ear", ["Ear Ring", "Ear Drum", "Ear Ache", "Ear Wax", "Ear Phone", "Ear Bud", "Ear Muff", "Dog Ear", "Ear Plug", "Ear Lobe"]],
  ["Face", ["Face Paint", "Face Lift", "Poker Face", "Baby Face", "Two Face", "Face Off", "Face Mask", "Face Cloth", "Face Time"]],
  ["Heart", ["Broken Heart", "Heart Beat", "Sweet Heart", "Heart Burn", "Heart Break", "Heart Attack", "Heart Land", "Heart Throb", "Brave Heart"]],
  ["Ball", ["Beach Ball", "Base Ball", "Basket Ball", "Snow Ball", "Meat Ball", "Golf Ball", "Ball Room", "Ball Park", "Odd Ball", "Fire Ball", "Ball Game", "Hair Ball", "Cannon Ball", "Ball Point", "Pin Ball", "Volley Ball", "Dodge Ball", "Wrecking Ball", "Crystal Ball", "Disco Ball"]],
  ["Box", ["Music Box", "Mail Box", "Match Box", "Sand Box", "Tool Box", "Lunch Box", "Ice Box", "Box Car", "Box Office", "Boom Box", "Cash Box", "Juke Box", "Shoe Box", "Fuse Box", "Box Spring"]],
  ["Bell", ["Door Bell", "Dumb Bell", "Blue Bell", "Cow Bell", "Bell Boy", "Bell Hop", "Jingle Bell", "Bell Tower", "School Bell", "Bell Pepper", "Wedding Bell"]],
  ["Bath", ["Bird Bath", "Bath Room", "Bath Tub", "Bubble Bath", "Blood Bath", "Bath Robe", "Bath Mat", "Bath Towel", "Sun Bath", "Mud Bath"]],
  ["Bed", ["Bed Room", "Flower Bed", "Bed Time", "River Bed", "Bunk Bed", "Bed Bug", "Water Bed", "Bed Sheet", "Bed Spread", "Day Bed", "Bed Rock", "Sea Bed"]],
  ["Door", ["Trap Door", "Door Bell", "Door Way", "Door Step", "Door Knob", "Back Door", "Front Door", "Door Mat", "Door Frame", "Barn Door", "Car Door", "Screen Door", "Door Man"]],
  ["Clock", ["Alarm Clock", "Clock Work", "Clock Wise", "Cuckoo Clock", "Clock Tower", "Time Clock", "Body Clock"]],
  ["Wheel", ["Wheel Chair", "Ferris Wheel", "Water Wheel", "Steering Wheel", "Wheel Barrow", "Cart Wheel", "Spinning Wheel", "Wagon Wheel", "Wheel House", "Hamster Wheel"]],
  ["Chair", ["Wheel Chair", "Arm Chair", "High Chair", "Deck Chair", "Rocking Chair", "Chair Man", "Chair Lift", "Beach Chair", "Easy Chair", "Chair Person"]],
  ["Table", ["Time Table", "Table Cloth", "Turn Table", "Pool Table", "Table Spoon", "Coffee Table", "Picnic Table", "Table Top", "Round Table", "Water Table", "Dinner Table", "Card Table"]],
  ["Bread", ["Ginger Bread", "Bread Crumb", "Corn Bread", "White Bread", "Bread Stick", "Bread Basket", "Bread Box", "Bread Winner", "Short Bread", "Bread Board", "Flat Bread", "Banana Bread"]],
  ["Egg", ["Egg Roll", "Egg Plant", "Egg Shell", "Egg Cup", "Egg Nog", "Scotch Egg", "Egg Head", "Egg Timer", "Egg White", "Egg Beater", "Nest Egg", "Easter Egg", "Egg Yolk"]],
  ["Milk", ["Milk Shake", "Milk Man", "Milk Carton", "Butter Milk", "Milk Maid", "Coconut Milk", "Milk Tooth", "Milk Bar", "Milk Weed"]],
  ["Corn", ["Pop Corn", "Corn Bread", "Corn Field", "Sweet Corn", "Corn Flake", "Corn Cob", "Uni Corn", "Corn Dog", "Corn Starch", "Corn Row", "Candy Corn"]],
  ["Cake", ["Cup Cake", "Pan Cake", "Cheese Cake", "Fish Cake", "Carrot Cake", "Birthday Cake", "Fruit Cake", "Sponge Cake", "Rice Cake", "Crab Cake", "Cake Walk", "Short Cake", "Marble Cake", "Beef Cake", "Wedding Cake"]],
  ["Pie", ["Meat Pie", "Apple Pie", "Pork Pie", "Pie Chart", "Pumpkin Pie", "Cutie Pie", "Mud Pie", "Pie Crust", "Humble Pie", "Cherry Pie"]],
  ["Cream", ["Ice Cream", "Sun Cream", "Cream Cheese", "Sour Cream", "Whipped Cream", "Cream Puff", "Face Cream", "Hand Cream", "Shaving Cream", "Cold Cream", "Cream Soda"]],
  ["Cup", ["Cup Board", "Cup Cake", "Tea Cup", "Egg Cup", "Butter Cup", "World Cup", "Cup Holder", "Measuring Cup"]],
  ["Pot", ["Jack Pot", "Tea Pot", "Flower Pot", "Pot Hole", "Crack Pot", "Hot Pot", "Pot Luck", "Pot Belly", "Ink Pot", "Chamber Pot", "Stock Pot", "Honey Pot", "Pot Pie", "Melting Pot", "Pot Plant"]],
  ["Pan", ["Frying Pan", "Pan Cake", "Sauce Pan", "Dust Pan", "Pan Handle", "Dish Pan", "Bed Pan", "Pan Fry", "Sheet Pan"]],
  ["Plate", ["License Plate", "Home Plate", "Hot Plate", "Number Plate", "Plate Glass", "Name Plate", "Tectonic Plate"]],
  ["Knife", ["Pocket Knife", "Butter Knife", "Jack Knife", "Knife Edge", "Bread Knife", "Steak Knife", "Pen Knife", "Putty Knife"]],
  ["Spoon", ["Wooden Spoon", "Tea Spoon", "Table Spoon", "Spoon Feed", "Greasy Spoon", "Serving Spoon", "Soup Spoon"]],
  ["Fork", ["Tuning Fork", "Pitch Fork", "Fork Lift", "Salad Fork", "Garden Fork", "Toasting Fork"]],
  ["Salt", ["Salt Shaker", "Sea Salt", "Salt Water", "Salt Mine", "Rock Salt", "Table Salt", "Salt Marsh", "Bath Salt", "Salt Lick", "Salt Cellar"]],
  ["Bean", ["Jelly Bean", "Bean Bag", "String Bean", "Coffee Bean", "Bean Stalk", "Baked Bean", "Green Bean", "Bean Sprout", "Broad Bean", "Runner Bean", "Kidney Bean", "Bean Pole"]],
  ["Rock", ["Rock Band", "Rock Star", "Bed Rock", "Rock Salt", "Rock Pool", "Rock Slide", "Rock Garden", "Punk Rock", "Rock Climb", "Hard Rock", "Rock Bottom", "Rock Candy", "Rock Face"]],
  ["Tree", ["Family Tree", "Tree House", "Palm Tree", "Tree Top", "Pine Tree", "Gum Tree", "Apple Tree", "Fir Tree", "Tree Trunk", "Christmas Tree", "Oak Tree", "Tree Line", "Shoe Tree", "Tree Bark"]],
  ["Wood", ["Fire Wood", "Wood Pecker", "Ply Wood", "Drift Wood", "Wood Land", "Red Wood", "Wood Work", "Wood Wind", "Hard Wood", "Rose Wood", "Wood Cutter", "Wood Shed", "Soft Wood", "Dog Wood"]],
  ["Leaf", ["Tea Leaf", "Fig Leaf", "Bay Leaf", "Gold Leaf", "Clover Leaf", "Leaf Blower", "Palm Leaf", "Loose Leaf", "Maple Leaf"]],
  ["Grass", ["Grass Hopper", "Grass Land", "Sea Grass", "Lemon Grass", "Crab Grass", "Grass Roots", "Grass Snake", "Blue Grass"]],
  ["Flower", ["Sun Flower", "Flower Pot", "Wild Flower", "Flower Bed", "May Flower", "Flower Girl", "Corn Flower", "Passion Flower", "Flower Power"]],
  ["Field", ["Corn Field", "Battle Field", "Field Trip", "Oil Field", "Coal Field", "Field Day", "Air Field", "Ice Field", "Snow Field", "Left Field", "Field Mouse", "Mine Field", "Field Goal", "Wheat Field"]],
  ["Hill", ["Ant Hill", "Down Hill", "Up Hill", "Hill Side", "Hill Top", "Sand Hill", "Foot Hill", "Dung Hill", "Hill Billy", "Mole Hill"]],
  ["Stone", ["Grave Stone", "Mile Stone", "Corner Stone", "Stone Wall", "Lime Stone", "Birth Stone", "Gem Stone", "Stone Age", "Cobble Stone", "Key Stone", "Hail Stone", "Flag Stone", "Brim Stone", "Curb Stone", "Stepping Stone", "Head Stone"]],
  ["Sand", ["Sand Castle", "Sand Box", "Sand Paper", "Quick Sand", "Sand Bag", "Sand Storm", "Sand Dune", "Sand Bar", "Sand Pit", "Sand Stone", "Sand Bank", "Sand Man"]],
  ["Ice", ["Ice Cream", "Ice Berg", "Ice Cube", "Ice Box", "Black Ice", "Dry Ice", "Ice Skate", "Ice Rink", "Ice Cap", "Ice Age", "Ice Pick", "Ice Pack", "Ice Tea", "Thin Ice"]],
  ["Cloud", ["Rain Cloud", "Cloud Burst", "Storm Cloud", "Cloud Nine", "Mushroom Cloud", "Thunder Cloud", "Dust Cloud"]],
  ["Storm", ["Thunder Storm", "Snow Storm", "Sand Storm", "Brain Storm", "Storm Cloud", "Rain Storm", "Dust Storm", "Storm Surge", "Wind Storm", "Fire Storm", "Storm Front"]],
  ["Light", ["Sun Light", "Moon Light", "Flash Light", "Day Light", "Spot Light", "Traffic Light", "Star Light", "Head Light", "Night Light", "Candle Light", "Torch Light", "Search Light", "Light House", "Light Bulb", "Light Year", "Light Switch", "Green Light", "Sky Light", "Tail Light", "Lamp Light", "Light Weight", "Fairy Light"]],
  ["House", ["Tree House", "Dog House", "Light House", "Green House", "Dolls House", "House Boat", "House Hold", "House Work", "House Fly", "White House", "House Coat", "Bird House", "Play House", "Farm House", "House Wife", "Full House", "Court House", "House Plant", "Ware House", "Club House", "Hen House", "Guest House", "House Keeper", "Round House", "Steak House"]],
  ["Room", ["Bed Room", "Bath Room", "Class Room", "Living Room", "Ball Room", "Court Room", "Dark Room", "Rest Room", "Show Room", "Store Room", "Waiting Room", "Elbow Room", "Board Room", "Dining Room", "Play Room", "Wash Room", "Chat Room", "Leg Room", "Green Room", "Locker Room", "News Room", "Mail Room"]],
  ["Yard", ["Back Yard", "Court Yard", "Grave Yard", "Junk Yard", "Barn Yard", "Ship Yard", "Farm Yard", "Vine Yard", "Front Yard", "Scrap Yard", "School Yard", "Yard Stick", "Boat Yard", "Brick Yard"]],
  ["Way", ["High Way", "Drive Way", "Rail Way", "Run Way", "Path Way", "Sub Way", "Hall Way", "Free Way", "Gate Way", "Door Way", "Mid Way", "Walk Way", "Air Way", "Speed Way", "Motor Way", "Cause Way", "Water Way", "Express Way", "Stair Way", "Tram Way"]],
  ["Side", ["Sea Side", "Country Side", "Road Side", "Bed Side", "Fire Side", "Out Side", "In Side", "Up Side", "Hill Side", "Pool Side", "Way Side", "Ring Side", "Curb Side", "Blind Side", "Flip Side", "Bright Side", "Off Side", "Broad Side", "Under Side", "Mountain Side", "Dark Side"]],
  ["Line", ["Head Line", "Base Line", "Coast Line", "Dead Line", "Life Line", "Out Line", "Hair Line", "Punch Line", "Time Line", "Pipe Line", "Guide Line", "Clothes Line", "Border Line", "Fault Line", "Finish Line", "Fishing Line", "Land Line", "Neck Line", "Tan Line", "Zip Line", "Bee Line", "Side Line", "Hot Line", "Sky Line", "Waist Line", "Story Line", "Front Line", "Bottom Line", "Power Line", "Phone Line", "Tree Line", "Straight Line"]],
  ["Time", ["Bed Time", "Day Time", "Night Time", "Life Time", "Over Time", "Play Time", "Tea Time", "Half Time", "Spring Time", "Summer Time", "Big Time", "Time Table", "Time Zone", "Time Out", "Time Keeper", "Story Time", "Rag Time", "Show Time", "Prime Time", "Nap Time", "Lunch Time", "Screen Time", "Time Machine", "Time Bomb", "Time Capsule", "Part Time", "Full Time", "Time Warp", "Bath Time", "Meal Time", "Peace Time"]],
  ["Work", ["Home Work", "Net Work", "Art Work", "Team Work", "Frame Work", "Fire Work", "Guess Work", "Wood Work", "Metal Work", "Ground Work", "Paper Work", "Body Work", "Patch Work", "Clock Work", "Brick Work", "Course Work", "Wax Work", "Iron Work", "Road Work", "Class Work", "School Work"]],
  ["Ground", ["Play Ground", "Back Ground", "Fore Ground", "Under Ground", "Camp Ground", "Battle Ground", "Ground Hog", "Ground Work", "Ground Nut", "Fair Ground", "Ground Water", "High Ground", "Common Ground", "Ground Floor", "Ground Beef"]],
  ["Paper", ["News Paper", "Sand Paper", "Wall Paper", "Paper Clip", "Paper Back", "Paper Weight", "Fly Paper", "Tissue Paper", "Paper Cut", "Note Paper", "Paper Boy", "Toilet Paper", "Paper Trail", "Paper Mill", "Term Paper", "Graph Paper", "Paper Chain"]],
  ["Board", ["Key Board", "Cup Board", "Surf Board", "Chalk Board", "Card Board", "Dash Board", "Skate Board", "Snow Board", "Score Board", "Bill Board", "White Board", "Black Board", "Diving Board", "Ironing Board", "Notice Board", "Bread Board", "Chess Board", "Clip Board", "Board Walk", "Board Room", "Board Game", "Cheese Board", "Head Board", "Over Board", "Spring Board"]],
  ["Chip", ["Potato Chip", "Poker Chip", "Chocolate Chip", "Wood Chip", "Blue Chip", "Micro Chip", "Corn Chip", "Paint Chip"]],
  ["Coffee", ["Coffee Cup", "Coffee Bean", "Coffee Table", "Coffee Break", "Coffee Pot", "Coffee Shop", "Coffee Mug", "Iced Coffee", "Coffee Cake", "Black Coffee", "Coffee Maker", "Coffee Grounds"]],
  ["Tea", ["Tea Pot", "Tea Cup", "Tea Spoon", "Tea Bag", "Tea Time", "Green Tea", "Ice Tea", "Tea Party", "Tea Leaf", "Tea Kettle", "Tea Room", "Herbal Tea", "Tea Tree", "Sweet Tea", "High Tea", "Bubble Tea", "Tea Towel", "Tea Set"]],
  ["Cheese", ["Cheese Cake", "Cheese Burger", "Cheese Board", "Blue Cheese", "String Cheese", "Cream Cheese", "Cheese Cloth", "Grilled Cheese", "Goat Cheese", "Cottage Cheese", "Cheese Grater", "Cheese Ball", "Big Cheese", "Swiss Cheese"]],
  ["Butter", ["Butter Fly", "Butter Cup", "Butter Milk", "Peanut Butter", "Butter Scotch", "Apple Butter", "Butter Knife", "Butter Bean", "Butter Nut", "Cocoa Butter", "Body Butter"]],
  ["Honey", ["Honey Bee", "Honey Comb", "Honey Moon", "Honey Pot", "Honey Dew", "Honey Suckle", "Honey Bun", "Wild Honey"]],
  ["Sugar", ["Sugar Cane", "Sugar Cube", "Brown Sugar", "Sugar Plum", "Sugar Rush", "Sugar Free", "Icing Sugar", "Sugar Beet", "Blood Sugar", "Sugar Bowl", "Powdered Sugar", "Sugar Coat"]],
  ["Apple", ["Apple Pie", "Apple Sauce", "Pine Apple", "Apple Tree", "Apple Juice", "Candy Apple", "Apple Cart", "Crab Apple", "Big Apple", "Apple Core", "Apple Cider", "Toffee Apple"]],
  ["Orange", ["Orange Juice", "Orange Peel", "Blood Orange", "Orange Zest", "Orange Tree"]],
  ["Berry", ["Straw Berry", "Blue Berry", "Black Berry", "Rasp Berry", "Cran Berry", "Goose Berry", "Elder Berry", "Mul Berry", "Berry Bush", "Dew Berry"]],
  ["Grape", ["Grape Fruit", "Grape Vine", "Grape Juice", "Sour Grape", "Grape Jelly"]],
  ["Lemon", ["Lemon Ade", "Lemon Grass", "Lemon Tree", "Lemon Zest", "Lemon Drop", "Lemon Curd", "Lemon Peel", "Lemon Juice", "Lemon Meringue"]],
  ["Nut", ["Pea Nut", "Wal Nut", "Coco Nut", "Chest Nut", "Dough Nut", "Nut Shell", "Nut Cracker", "Ground Nut", "Pine Nut", "Nut Meg", "Hazel Nut", "Nut Case", "Nut Bar", "Cashew Nut", "Nut Hatch"]],
  ["Meat", ["Meat Ball", "Meat Loaf", "Mince Meat", "Meat Pie", "Red Meat", "Lunch Meat", "Meat Hook", "Deli Meat", "Meat Head", "Dark Meat", "Meat Grinder", "White Meat"]],
  ["Beef", ["Beef Burger", "Corned Beef", "Beef Cake", "Beef Steak", "Ground Beef", "Roast Beef", "Beef Stew", "Beef Jerky", "Beef Eater", "Minced Beef"]],
  ["Ham", ["Ham Burger", "Ham Bone", "Ham String", "Honey Ham", "Ham Steak"]],
  ["Pork", ["Pork Chop", "Pork Pie", "Pork Rind", "Pork Belly", "Roast Pork", "Pulled Pork", "Pork Barrel", "Ground Pork"]],
  ["Chicken", ["Chicken Pox", "Chicken Wing", "Chicken Coop", "Chicken Soup", "Chicken Feed", "Chicken Broth", "Rubber Chicken", "Fried Chicken", "Spring Chicken", "Chicken Run", "Chicken Wire", "Roast Chicken"]],
  ["Rice", ["Fried Rice", "Rice Cake", "Rice Pudding", "Wild Rice", "Rice Paper", "Brown Rice", "White Rice", "Rice Bowl", "Rice Field", "Rice Ball"]],
  ["Soup", ["Chicken Soup", "Soup Spoon", "Pea Soup", "Soup Kitchen", "Tomato Soup", "Alphabet Soup", "Duck Soup", "Soup Bowl", "Onion Soup", "Miso Soup"]],
  ["Salad", ["Fruit Salad", "Salad Bowl", "Salad Bar", "Potato Salad", "Salad Dressing", "Salad Days", "Caesar Salad", "Green Salad", "Egg Salad", "Salad Fork"]],
  ["Bar", ["Chocolate Bar", "Candy Bar", "Crow Bar", "Sand Bar", "Space Bar", "Snack Bar", "Salad Bar", "Bar Bell", "Bar Stool", "Handle Bar", "Bar Code", "Bar Tender", "Milk Bar", "Cross Bar", "Monkey Bar", "Bar Chart", "Grab Bar", "Menu Bar", "Tool Bar", "Wine Bar", "Juice Bar", "Bar Graph"]],
  ["Juice", ["Orange Juice", "Apple Juice", "Fruit Juice", "Grape Juice", "Juice Box", "Lemon Juice", "Tomato Juice", "Juice Bar", "Carrot Juice", "Lime Juice"]],
  ["Bug", ["Lady Bug", "Bed Bug", "June Bug", "Bug Spray", "Litter Bug", "Love Bug", "Fire Bug", "Stink Bug", "Water Bug", "Doodle Bug", "Jitter Bug", "May Bug", "Shield Bug", "Bug Bear", "Bug Bite"]],
  ["Spider", ["Spider Web", "Spider Man", "Sea Spider", "Water Spider", "Spider Bite", "Spider Plant"]],
  ["Web", ["Spider Web", "Web Site", "Web Page", "Cob Web", "Web Cam", "Food Web", "Web Master", "Web Foot"]],
  ["Net", ["Fish Net", "Hair Net", "Net Work", "Safety Net", "Net Ball", "Cast Net", "Drift Net", "Hoop Net"]],
  ["Bag", ["Hand Bag", "Tea Bag", "Sleeping Bag", "Bean Bag", "Sand Bag", "Air Bag", "Garbage Bag", "Punch Bag", "Gift Bag", "Duffel Bag", "Grab Bag", "Body Bag", "Mail Bag", "Bag Pipe", "Doggy Bag", "School Bag", "Tote Bag", "Trash Bag", "Wind Bag", "Money Bag", "Bag Lady", "Ice Bag", "Kit Bag", "Gym Bag", "Bin Bag"]],
  ["Belt", ["Seat Belt", "Green Belt", "Belt Buckle", "Sun Belt", "Rust Belt", "Tool Belt", "Fan Belt", "Conveyor Belt", "Bible Belt", "Safety Belt", "Black Belt", "Belt Loop", "Money Belt", "Karate Belt"]],
  ["Boot", ["Boot Camp", "Boot Strap", "Rubber Boot", "Boot Lace", "Ski Boot", "Snow Boot", "Boot Jack", "Work Boot", "Combat Boot", "Rain Boot", "Riding Boot", "Boot Print"]],
  ["Shoe", ["Horse Shoe", "Snow Shoe", "Shoe Lace", "Shoe Box", "Shoe Horn", "Shoe String", "Ballet Shoe", "Gym Shoe", "Shoe Maker", "Tennis Shoe", "Running Shoe", "Over Shoe", "Shoe Tree", "Shoe Shine", "Shoe Rack", "Brake Shoe", "Tap Shoe"]],
  ["Sock", ["Sweat Sock", "Sock Puppet", "Wind Sock", "Ankle Sock", "Bobby Sock", "Tube Sock", "Knee Sock", "Sock Hop", "Dress Sock"]],
  ["Hat", ["Top Hat", "Hard Hat", "Sun Hat", "Hat Band", "Hat Box", "Hat Trick", "Straw Hat", "Party Hat", "Hat Rack", "Bowler Hat", "Old Hat", "Rain Hat", "Witch Hat", "Tin Hat", "Hat Pin", "Wooly Hat", "Hat Stand", "Chef Hat"]],
  ["Coat", ["Rain Coat", "Over Coat", "Trench Coat", "Coat Rack", "Coat Hanger", "Coat Tail", "Turn Coat", "Fur Coat", "Lab Coat", "Under Coat", "Top Coat", "Coat Room", "Pea Coat", "Waist Coat", "Coat Check", "House Coat"]],
  ["Glass", ["Hour Glass", "Eye Glass", "Spy Glass", "Glass Ware", "Wine Glass", "Magnifying Glass", "Looking Glass", "Stained Glass", "Glass House", "Water Glass", "Shot Glass", "Glass Eye", "Plate Glass", "Frosted Glass", "Glass Blower", "Pint Glass"]],
  ["Key", ["Key Board", "Key Ring", "Key Hole", "Key Chain", "Key Stone", "Key Note", "Key Word", "Key Pad", "Turn Key", "Master Key", "Skeleton Key", "Latch Key", "Car Key", "Key Card", "Pass Key", "Low Key", "Key Lime"]],
  ["Lock", ["Pad Lock", "Dead Lock", "Lock Smith", "Lock Down", "Lock Jaw", "Lock Out", "Combination Lock", "Grid Lock", "Lock Box", "Lock Step", "War Lock", "Wed Lock", "Air Lock", "Body Lock", "Bike Lock", "Lock Screen", "Zip Lock"]],
  ["Chain", ["Key Chain", "Chain Saw", "Food Chain", "Daisy Chain", "Chain Mail", "Chain Link", "Chain Reaction", "Chain Gang", "Watch Chain", "Chain Smoker", "Chain Letter", "Bike Chain", "Snow Chain", "Chain Store"]],
  ["Nail", ["Finger Nail", "Toe Nail", "Nail Polish", "Nail File", "Nail Gun", "Thumb Nail", "Nail Clipper", "Nail Bed", "Hang Nail", "Coffin Nail", "Nail Brush", "Nail Salon", "Door Nail", "Nail Bar"]],
  ["Pin", ["Safety Pin", "Push Pin", "Rolling Pin", "Bobby Pin", "Clothes Pin", "Hair Pin", "Pin Wheel", "Pin Cushion", "Ten Pin", "Pin Ball", "Pin Point", "Pin Stripe", "Pin Head", "Cotter Pin", "Hat Pin", "King Pin", "Pin Prick", "Tie Pin", "Stick Pin"]],
  ["Pen", ["Play Pen", "Pig Pen", "Pen Knife", "Pen Pal", "Sheep Pen", "Bull Pen", "Fountain Pen", "Pen Name", "Felt Pen", "Pen Light", "Pen Holder", "Cattle Pen", "Marker Pen"]],
  ["Cap", ["Night Cap", "Knee Cap", "Ice Cap", "Hub Cap", "Bottle Cap", "Mad Cap", "Red Cap", "Cap Stone", "Skull Cap", "Snow Cap", "Toe Cap", "Cap Gun", "Swim Cap", "Cap Rock"]],
  ["Cloth", ["Table Cloth", "Wash Cloth", "Face Cloth", "Cheese Cloth", "Dish Cloth", "Loin Cloth", "Sack Cloth", "Broad Cloth", "Oil Cloth"]],
  ["Brush", ["Tooth Brush", "Hair Brush", "Paint Brush", "Nail Brush", "Bottle Brush", "Brush Fire", "Brush Stroke", "Wire Brush", "Shoe Brush", "Under Brush", "Brush Off", "Scrub Brush", "Brush Work"]],
  ["Comb", ["Honey Comb", "Comb Over", "Curry Comb", "Cox Comb"]],
  ["Soap", ["Soap Box", "Soap Opera", "Soap Dish", "Soap Suds", "Soap Stone", "Saddle Soap", "Soap Bubble", "Hand Soap", "Dish Soap"]],
  ["Towel", ["Bath Towel", "Beach Towel", "Tea Towel", "Paper Towel", "Hand Towel", "Towel Rack", "Dish Towel", "Towel Rail"]],
  ["Mat", ["Door Mat", "Bath Mat", "Place Mat", "Yoga Mat", "Welcome Mat", "Mouse Mat", "Bar Mat", "Beer Mat", "Prayer Mat", "Wrestling Mat", "Play Mat", "Table Mat"]],
  ["Rug", ["Bear Rug", "Bath Rug", "Area Rug", "Rug Rat", "Throw Rug", "Prayer Rug", "Persian Rug", "Rag Rug", "Rug Burn"]],
  ["Lamp", ["Lamp Shade", "Lamp Post", "Lamp Light", "Desk Lamp", "Oil Lamp", "Lava Lamp", "Street Lamp", "Heat Lamp", "Table Lamp", "Lamp Black", "Floor Lamp", "Head Lamp", "Reading Lamp"]],
  ["Candle", ["Candle Stick", "Candle Light", "Candle Wick", "Wax Candle", "Candle Wax", "Roman Candle", "Birthday Candle", "Scented Candle", "Candle Holder"]],
  ["Watch", ["Wrist Watch", "Watch Dog", "Watch Man", "Watch Tower", "Night Watch", "Watch Word", "Stop Watch", "Pocket Watch", "Bird Watch", "Watch Band", "Watch Maker", "Over Watch", "Watch List", "Watch House", "Watch Strap", "Storm Watch"]],
  ["Ring", ["Ear Ring", "Boxing Ring", "Key Ring", "Ring Master", "Ring Worm", "Wedding Ring", "Ring Leader", "Ring Side", "Nose Ring", "Ring Tone", "Onion Ring", "Ring Finger", "Smoke Ring", "Ring Road", "Napkin Ring", "Circus Ring", "Ring Binder", "Mood Ring", "Toe Ring", "Diamond Ring", "Teething Ring"]],
  ["Card", ["Post Card", "Playing Card", "Score Card", "Flash Card", "Credit Card", "Report Card", "Card Board", "Birthday Card", "Wild Card", "Business Card", "Card Trick", "Trump Card", "Debit Card", "Index Card", "Green Card", "Card Game", "Place Card", "Trading Card", "Card Shark", "Time Card", "Punch Card", "Note Card", "Red Card", "Card Table", "Yellow Card", "Memory Card", "Gift Card", "Cue Card", "Card Holder"]],
  ["Game", ["Board Game", "Video Game", "Ball Game", "Card Game", "Game Show", "End Game", "Game Plan", "War Game", "Fair Game", "Mind Game", "Game Night", "Game Over", "Game Face", "Big Game", "Waiting Game", "Number Game", "Guessing Game", "Game Bird", "Game Room", "Game Point", "Perfect Game", "Game Keeper", "Away Game", "Home Game", "Game Warden", "Party Game"]],
  ["Show", ["Talk Show", "Game Show", "Slide Show", "Show Down", "Show Off", "Show Case", "Show Time", "Show Girl", "Peep Show", "Show Room", "Puppet Show", "Freak Show", "Road Show", "Air Show", "Show Business", "No Show", "Horror Show", "Show Boat", "Fashion Show", "Show Man", "Side Show", "Show Piece", "Magic Show", "Talent Show", "Trade Show", "Dog Show", "Show Stopper", "Light Show"]],
  ["Play", ["Play Ground", "Play Time", "Play House", "Play Pen", "Play Boy", "Word Play", "Fair Play", "Horse Play", "Role Play", "Play Mate", "Play Off", "Play Book", "Play List", "Play Room", "Play Wright", "Screen Play", "Play Dough", "Play Date", "Power Play", "Play Group", "Play Thing", "Play Field"]],
  ["Note", ["Note Book", "Note Pad", "Foot Note", "Bank Note", "Key Note", "Note Paper", "Love Note", "Sticky Note", "Note Worthy", "Ransom Note", "Whole Note", "Half Note", "Music Note", "Quarter Note", "Note Card", "Grace Note"]],
  ["Pad", ["Note Pad", "Key Pad", "Launch Pad", "Lily Pad", "Mouse Pad", "Scratch Pad", "Knee Pad", "Shoulder Pad", "Elbow Pad", "Ink Pad", "Foot Pad", "Crash Pad", "Brake Pad", "Sketch Pad", "Touch Pad", "Number Pad", "Landing Pad", "Stamp Pad"]],
  ["Mark", ["Book Mark", "Land Mark", "Bench Mark", "Trade Mark", "Post Mark", "Birth Mark", "Check Mark", "Hall Mark", "Ear Mark", "Question Mark", "Skid Mark", "Tide Mark", "Bite Mark", "Water Mark", "Stretch Mark", "Pock Mark", "Quotation Mark"]],
  ["Print", ["Foot Print", "Finger Print", "Blue Print", "News Print", "Print Out", "Paw Print", "Small Print", "Hoof Print", "Thumb Print", "Over Print", "Hand Print", "Screen Print", "Fine Print", "Print Head", "Voice Print", "Print Maker", "Nose Print"]],
  ["Camp", ["Camp Fire", "Camp Site", "Camp Ground", "Boot Camp", "Base Camp", "Day Camp", "Summer Camp", "Camp Stove", "Break Camp", "Camp Bed", "Camp Out", "Scout Camp"]],
  ["Trip", ["Road Trip", "Field Trip", "Trip Wire", "Guilt Trip", "Day Trip", "Ego Trip", "Round Trip", "Power Trip", "Trip Hazard", "Boat Trip", "Bus Trip"]],
  ["Boat", ["Sail Boat", "Row Boat", "Speed Boat", "House Boat", "Tug Boat", "Steam Boat", "Life Boat", "Ferry Boat", "Gravy Boat", "Boat House", "Boat Yard", "Fishing Boat", "Show Boat", "Boat Load", "Motor Boat", "Dream Boat", "Long Boat", "Boat Ramp", "Party Boat", "Canal Boat", "Boat Neck"]],
  ["Ship", ["Space Ship", "Battle Ship", "Ship Yard", "Ship Wreck", "Ship Mate", "Star Ship", "Flag Ship", "War Ship", "Air Ship", "Steam Ship", "Ship Load", "Cargo Ship", "Ghost Ship", "Cruise Ship", "Pirate Ship", "Sister Ship", "Ship Board", "Mother Ship", "Rocket Ship", "Ship Shape", "Tall Ship", "Sinking Ship"]],
  ["Car", ["Race Car", "Cable Car", "Box Car", "Car Wash", "Car Park", "Car Pool", "Street Car", "Car Port", "Bumper Car", "Side Car", "Sports Car", "Dining Car", "Car Sick", "Freight Car", "Car Seat", "Rail Car", "Patrol Car", "Car Jack", "Squad Car", "Company Car", "Sleeping Car", "Clown Car", "Car Wax", "Stock Car", "Toy Car"]],
  ["Truck", ["Fire Truck", "Dump Truck", "Monster Truck", "Tow Truck", "Food Truck", "Truck Stop", "Mail Truck", "Garbage Truck", "Truck Load", "Truck Driver", "Cement Truck", "Milk Truck", "Truck Bed", "Toy Truck", "Semi Truck"]],
  ["Train", ["Freight Train", "Train Track", "Steam Train", "Train Station", "Night Train", "Bullet Train", "Toy Train", "Gravy Train", "Wagon Train", "Train Wreck", "Ghost Train", "Train Set", "Cargo Train", "Mule Train", "Train Car"]],
  ["Plane", ["Air Plane", "Sea Plane", "Bi Plane", "War Plane", "Jet Plane", "Plane Crash", "Paper Plane", "Fighter Plane", "Astral Plane", "Tail Plane", "Spy Plane", "Cargo Plane", "Model Plane"]],
  ["Bike", ["Motor Bike", "Mountain Bike", "Dirt Bike", "Bike Rack", "Push Bike", "Bike Lane", "Bike Path", "Trail Bike", "Exercise Bike", "Bike Helmet", "Bike Shed", "Quad Bike", "Mini Bike", "Racing Bike", "Bike Ride"]],
  ["Road", ["Rail Road", "Cross Road", "Road Block", "Road Side", "Road Trip", "Road Kill", "Road Map", "Main Road", "Road Work", "Road Sign", "Ring Road", "High Road", "Road Runner", "Road Rage", "Road Show", "Off Road", "Silk Road", "Toll Road", "Road House", "Dirt Road", "Road Hog", "Back Road", "Road Way", "Road Bike", "Country Road", "Road Test"]],
  ["Rail", ["Rail Road", "Rail Way", "Guard Rail", "Hand Rail", "Rail Car", "Mono Rail", "Third Rail", "Rail Gun", "Rail Yard", "Curtain Rail", "Towel Rail", "Rail Track", "Rail Head"]],
  ["Bridge", ["Draw Bridge", "Foot Bridge", "Toll Bridge", "Bridge Head", "Rope Bridge", "Land Bridge", "Bridge Club"]],
  ["Station", ["Train Station", "Bus Station", "Gas Station", "Space Station", "Fire Station", "Police Station", "Petrol Station", "Radio Station", "Power Station", "Weather Station", "Station Master", "Way Station", "Work Station", "Filling Station", "Charging Station", "Service Station", "Base Station", "Polling Station"]],
  ["Port", ["Air Port", "Sea Port", "Car Port", "Port Hole", "Pass Port", "Free Port", "Home Port", "Heli Port", "Space Port", "Port Wine", "Sally Port", "Port Side"]],
  ["Park", ["Car Park", "Ball Park", "Theme Park", "National Park", "Park Bench", "Park Way", "Water Park", "Trailer Park", "Amusement Park", "Park Ranger", "Skate Park", "Dog Park", "Business Park", "Park Land", "Caravan Park", "Retail Park", "Park Keeper"]],
  ["Garden", ["Garden Gnome", "Rose Garden", "Garden Hose", "Zen Garden", "Beer Garden", "Garden Path", "Roof Garden", "Tea Garden", "Herb Garden", "Vegetable Garden", "Kitchen Garden", "Garden Party", "Garden Shed", "Botanical Garden", "Garden Wall", "Water Garden", "Rock Garden", "Garden Fork", "Garden Bed"]],
  ["Farm", ["Farm House", "Farm Yard", "Farm Hand", "Wind Farm", "Farm Land", "Dairy Farm", "Ant Farm", "Chicken Farm", "Farm Animal", "Fish Farm", "Funny Farm", "Farm Fresh", "Cattle Farm", "Farm Gate", "Solar Farm", "Pig Farm", "Farm Track", "Tree Farm"]],
  ["City", ["City Hall", "Inner City", "City Centre", "City Slicker", "City Scape", "City Limits", "Capital City", "City Block", "City Council", "City Wall", "Sister City", "Big City", "City Life", "City Gate", "City State", "City Lights"]],
  ["Town", ["Down Town", "Home Town", "China Town", "Ghost Town", "Town Hall", "Town House", "Cape Town", "Up Town", "Boom Town", "Town Square", "Town Centre", "Town Crier", "Small Town", "Old Town", "Town Council", "Shanty Town", "Cow Town", "Town Folk"]],
  ["Street", ["Street Light", "Main Street", "Street Car", "Side Street", "Wall Street", "Back Street", "Street Wise", "Street Corner", "High Street", "Street Lamp", "Cross Street", "Street Sign", "Street Sweeper", "Street Vendor", "Street Fighter", "Street Food"]],
  ["Wall", ["Fire Wall", "Wall Paper", "Stone Wall", "Sea Wall", "Wall Flower", "Brick Wall", "Dry Wall", "Great Wall", "Wall Clock", "Party Wall", "Wall Chart", "Garden Wall", "Cavity Wall", "Wall Mount", "Climbing Wall"]],
  ["Roof", ["Roof Top", "Sun Roof", "Roof Rack", "Thatched Roof", "Roof Tile", "Flat Roof", "Roof Garden", "Roof Beam", "Tin Roof"]],
  ["Floor", ["Ground Floor", "Floor Board", "Dance Floor", "Floor Plan", "Sea Floor", "First Floor", "Top Floor", "Floor Mat", "Shop Floor", "Ocean Floor", "Floor Lamp", "Forest Floor", "Floor Tile", "Factory Floor", "Floor Space"]],
  ["Gate", ["Gate Way", "Gate Keeper", "Gate Post", "Gate Crasher", "Flood Gate", "Toll Gate", "Star Gate", "Front Gate", "Water Gate", "Farm Gate", "Gate House", "Boarding Gate", "Garden Gate", "Golden Gate", "Departure Gate", "Baby Gate"]],
  ["Fence", ["Picket Fence", "Fence Post", "Electric Fence", "Fence Sitter", "Wire Fence", "Garden Fence", "Snow Fence", "Ring Fence", "Fence Line"]],
  ["Sky", ["Sky Line", "Sky Scraper", "Sky Light", "Sky Diver", "Sky Lark", "Sky Way", "Sky Rocket", "Sky Blue", "Sky Dive", "Sky Ward", "Big Sky", "Night Sky", "Sky Cap", "Sky Watch", "Sky Box", "Sky Bridge", "Sky High", "Sky Walk"]],
  ["Air", ["Air Port", "Air Plane", "Air Line", "Air Craft", "Air Bag", "Air Way", "Air Field", "Air Space", "Air Show", "Air Mail", "Air Force", "Air Lift", "Air Time", "Air Fare", "Air Head", "Air Wave", "Air Strip", "Air Drop", "Fresh Air", "Hot Air", "Air Duct", "Mid Air", "Air Ship", "Air Base", "Air Gun", "Open Air", "Air Pump", "Air Vent", "Air Brush", "Air Tight", "Air Flow", "Air Bed", "Air Guitar", "Thin Air", "Air Pocket"]],
  ["Fog", ["Fog Horn", "Fog Bank", "Fog Light", "Fog Machine", "Sea Fog", "Brain Fog", "Ground Fog", "Fog Bound"]],
  ["Frost", ["Frost Bite", "Jack Frost", "Frost Ing", "Hoar Frost", "Ground Frost", "Frost Line", "Perma Frost", "Frost Free"]],
  ["Dew", ["Dew Drop", "Honey Dew", "Morning Dew", "Dew Point", "Dew Claw"]],
  ["Wave", ["Tidal Wave", "Heat Wave", "Micro Wave", "Radio Wave", "Sound Wave", "Wave Length", "Cold Wave", "Brain Wave", "Shock Wave", "Wave Form", "New Wave", "Crime Wave", "Sine Wave", "Mexican Wave", "Ocean Wave", "Ground Wave"]],
  ["Tide", ["High Tide", "Low Tide", "Red Tide", "Rip Tide", "Tide Pool", "Neap Tide", "Ebb Tide", "Spring Tide", "Tide Table", "Tide Water", "Storm Tide"]],
  ["Beach", ["Beach Ball", "Beach Chair", "Beach Towel", "Beach House", "Beach Comber", "Beach Front", "Beach Wear", "Sandy Beach", "Beach Head", "Beach Bum", "Palm Beach", "Beach Umbrella", "Beach Party", "Long Beach", "Beach Buggy"]],
  ["Gold", ["Gold Fish", "Gold Mine", "Gold Smith", "Gold Rush", "Gold Dust", "Fool's Gold", "Gold Leaf", "Gold Bar", "Gold Medal", "Gold Digger", "White Gold", "Rose Gold", "Solid Gold", "Gold Field"]],
  ["Silver", ["Silver Ware", "Silver Fish", "Silver Smith", "Silver Screen", "Quick Silver", "Silver Lining", "Silver Foil", "Silver Medal", "Silver Spoon", "Sterling Silver"]],
  ["Iron", ["Iron Work", "Cast Iron", "Iron Man", "Flat Iron", "Iron Fist", "Iron Clad", "Waffle Iron", "Iron Age", "Wrought Iron", "Curling Iron", "Iron Bar", "Steam Iron", "Iron Lung"]],
  ["Coal", ["Coal Mine", "Coal Field", "Char Coal", "Coal Face", "Coal Dust", "Coal Bunker", "Coal Scuttle", "Coal Fire"]],
  ["Oil", ["Oil Field", "Oil Well", "Oil Rig", "Oil Paint", "Olive Oil", "Oil Slick", "Baby Oil", "Snake Oil", "Oil Can", "Crude Oil", "Oil Spill", "Motor Oil", "Oil Drum", "Coconut Oil", "Oil Lamp"]],
  ["Gas", ["Gas Station", "Gas Mask", "Tear Gas", "Gas Pump", "Natural Gas", "Gas Light", "Laughing Gas", "Gas Works", "Gas Fire", "Gas Bag", "Gas Meter", "Gas Ring", "Gas Guzzler"]],
  ["Steam", ["Steam Boat", "Steam Ship", "Steam Roller", "Steam Engine", "Steam Train", "Steam Punk", "Full Steam", "Steam Bath", "Steam Room", "Steam Iron", "Let Off Steam"]],
  ["Life", ["Life Boat", "Life Guard", "Wild Life", "Life Time", "Life Line", "Life Style", "Life Span", "Life Cycle", "Night Life", "Shelf Life", "Life Long", "Sea Life", "Life Jacket", "Still Life", "Life Raft", "Life Size", "Low Life", "Life Blood", "Half Life", "Life Work", "Plant Life", "Pro Life", "Real Life", "Life Coach"]],
  ["Home", ["Home Work", "Home Made", "Home Town", "Home Sick", "Home Land", "Home Run", "Home Page", "Home Coming", "Home Body", "Nursing Home", "Home Grown", "Mobile Home", "Home Owner", "Home Stead", "Home Boy", "Home School", "Home Base", "Rest Home", "Stay Home", "Home Ward"]],
  ["School", ["High School", "School Boy", "School Girl", "School Bus", "School Yard", "Pre School", "School Work", "School House", "School Bag", "Sunday School", "School Master", "Boarding School", "Grammar School", "School Book", "Old School", "School Teacher", "Night School", "School Bell", "Art School", "Charm School", "Fish School"]],
  ["Baby", ["Baby Sit", "Baby Boom", "Baby Food", "Baby Face", "Baby Shower", "Baby Talk", "Baby Tooth", "Cry Baby", "Baby Blue", "Water Baby", "Baby Grand", "Baby Steps", "Baby Wipe", "Bush Baby", "Baby Doll"]],
  ["Blood", ["Blood Hound", "Blood Bath", "Blood Shot", "Blood Stream", "Blood Line", "Cold Blood", "Blood Sport", "Blood Sucker", "Blood Cell", "Blood Bank", "Blue Blood", "Blood Type", "Blood Shed", "Blood Pressure", "Blood Vessel", "Blood Orange"]],
  ["Night", ["Night Fall", "Night Gown", "Night Mare", "Night Owl", "Mid Night", "Over Night", "Good Night", "Night Cap", "Night Club", "Night Life", "Night Time", "Night Watch", "Night Shift", "Late Night", "Night Light", "Night Stand", "Night Vision", "Fort Night", "Night School", "Night Wear", "Night Sky", "Night Crawler"]],
  ["Day", ["Day Dream", "Day Break", "Day Light", "Birth Day", "Holi Day", "Sun Day", "Mon Day", "Day Time", "Week Day", "Every Day", "Pay Day", "May Day", "Dooms Day", "Day Care", "Work Day", "Snow Day", "Day Bed", "Field Day", "Play Day", "Race Day", "Wash Day", "Day Trip", "Some Day", "Day Job", "Rainy Day", "Yester Day"]],
  ["Green", ["Green House", "Green Horn", "Ever Green", "Green Room", "Green Belt", "Green Back", "Green Thumb", "Green Field", "Green Grocer", "Bowling Green", "Green Light", "Village Green", "Green Card", "Green Wood"]],
  ["Blue", ["Blue Bird", "Blue Berry", "Blue Print", "Blue Bell", "Blue Bottle", "Blue Grass", "Baby Blue", "Blue Jay", "Blue Blood", "Navy Blue", "Sky Blue", "Blue Whale", "Blue Cheese", "Out Of The Blue", "Blue Jeans", "True Blue", "Royal Blue", "Blue Collar"]],
  ["Black", ["Black Bird", "Black Board", "Black Berry", "Black Out", "Black Smith", "Black Mail", "Black List", "Black Belt", "Black Sheep", "Black Hole", "Black Jack", "Black Beard", "Coal Black", "Black Top", "Black Ice", "Black Eye", "Black Market", "Jet Black", "Black Bear", "Pitch Black", "Black Widow", "Black Box"]],
  ["White", ["White Wash", "White Board", "Egg White", "White Out", "Snow White", "White Water", "White Wall", "Off White", "White Cap", "White Bread", "White Meat", "White House", "Lily White", "White Collar", "White Noise", "Bone White"]],
  ["Red", ["Red Head", "Red Wood", "Red Neck", "Red Skin", "Red Coat", "Red Fish", "Red Bud", "Red Cap", "Fire Red", "Red Eye", "Blood Red", "Red Card", "Red Carpet", "Ruby Red", "Red Hot", "Red Brick"]],
  ["Under", ["Under Dog", "Under Wear", "Under Water", "Under Ground", "Under Cover", "Under Stand", "Under Pass", "Under Line", "Under Arm", "Under Study", "Under World", "Under Coat", "Under Brush", "Under Foot", "Under Rated", "Under Score", "Under Growth", "Under Current"]],
  ["Over", ["Over Board", "Over Coat", "Over Come", "Over Dose", "Over Flow", "Over Haul", "Over Head", "Over Lap", "Over Load", "Over Night", "Over Pass", "Over Ride", "Over Seas", "Over Time", "Over Turn", "Over View", "Over Grown", "Over Cast", "Over Bite", "Over Alls", "Over Kill", "Over Lord"]],
  ["Out", ["Out Break", "Out Cast", "Out Come", "Out Cry", "Out Doors", "Out Fit", "Out Grow", "Out House", "Out Last", "Out Law", "Out Let", "Out Line", "Out Look", "Out Post", "Out Put", "Out Rage", "Out Reach", "Out Right", "Out Side", "Out Skirts", "Out Smart", "Out Spoken", "Out Weigh", "Out Number", "Out Back", "Out Field"]],
  ["Back", ["Back Bone", "Back Fire", "Back Ground", "Back Hand", "Back Lash", "Back Log", "Back Pack", "Back Side", "Back Stage", "Back Stroke", "Back Track", "Back Up", "Back Ward", "Back Yard", "Draw Back", "Feed Back", "Flash Back", "Horse Back", "Out Back", "Pay Back", "Set Back", "Throw Back", "Hump Back", "Half Back", "Quarter Back", "Bare Back", "Come Back", "Cut Back", "Hunch Back"]],
  ["Down", ["Down Fall", "Down Hill", "Down Load", "Down Play", "Down Pour", "Down Right", "Down Size", "Down Stairs", "Down Stream", "Down Town", "Down Turn", "Down Ward", "Break Down", "Count Down", "Melt Down", "Show Down", "Sun Down", "Touch Down", "Low Down", "Hoe Down", "Hand Me Down", "Let Down", "Melt Down", "Sun Down"]],
  ["Up", ["Up Beat", "Up Bringing", "Up Grade", "Up Hill", "Up Hold", "Up Keep", "Up Land", "Up Lift", "Up Load", "Up Right", "Up Rising", "Up Roar", "Up Root", "Up Scale", "Up Set", "Up Side", "Up Stairs", "Up Stream", "Up Take", "Up Town", "Up Ward", "Up Wind", "Check Up", "Grown Up", "Push Up", "Sit Up", "Wake Up", "Warm Up", "Round Up", "Close Up"]],
  ["Cross", ["Cross Bow", "Cross Fire", "Cross Road", "Cross Walk", "Cross Word", "Cross Over", "Cross Bones", "Cross Hair", "Cross Check", "Cross Cut", "Rail Cross", "Cross Wind", "Cross Bar", "Cross Breed", "Cross Fit", "Cross Guard", "Cross Stitch", "South Cross", "Cross Beam", "Cross Country"]],
];

function generate(): WordCard[] {
  const cards: WordCard[] = [];
  const seenHard = new Set<string>();
  for (const [easy, hards] of TABLE) {
    for (const hard of hards) {
      // Skip malformed / single-word entries and self-references.
      if (!hard.includes(" ")) continue;
      const key = hard.toLowerCase();
      if (seenHard.has(key)) continue;
      if (hard.toLowerCase() === easy.toLowerCase()) continue;
      seenHard.add(key);
      cards.push({ easy, hard });
    }
  }
  return cards;
}

export const EVERYDAY_CARDS: WordCard[] = generate();
