import type { WordCard } from "./types";
import { unique } from "./gen";

// Movies: the hard 3-point answer is a famous film (aimed at players born in
// the 1990s and later — animated hits, blockbusters and big franchises). The
// easy 1-point word is a simple thing associated with the film.
//
// Curated for recognisability rather than padded to a fixed count.

const M: WordCard[] = [
  { easy: "Toy", hard: "Toy Story" },
  { easy: "Fish", hard: "Finding Nemo" },
  { easy: "Lion", hard: "The Lion King" },
  { easy: "Snow", hard: "Frozen" },
  { easy: "Ogre", hard: "Shrek" },
  { easy: "Balloon", hard: "Up" },
  { easy: "Car", hard: "Cars" },
  { easy: "Ocean", hard: "Moana" },
  { easy: "Guitar", hard: "Coco" },
  { easy: "Rat", hard: "Ratatouille" },
  { easy: "Magic", hard: "Encanto" },
  { easy: "Lamp", hard: "Aladdin" },
  { easy: "Hair", hard: "Tangled" },
  { easy: "Bear", hard: "Brave" },
  { easy: "Fox", hard: "Zootopia" },
  { easy: "Brain", hard: "Inside Out" },
  { easy: "Robot", hard: "Big Hero Six" },
  { easy: "Panda", hard: "Kung Fu Panda" },
  { easy: "Zebra", hard: "Madagascar" },
  { easy: "Mammoth", hard: "Ice Age" },
  { easy: "Minion", hard: "Despicable Me" },
  { easy: "Cape", hard: "The Incredibles" },
  { easy: "Monster", hard: "Monsters Inc" },
  { easy: "Trash", hard: "Wall E" },
  { easy: "Rose", hard: "Beauty And The Beast" },
  { easy: "Sword", hard: "Mulan" },
  { easy: "Snowman", hard: "Olaf" },
  { easy: "Mic", hard: "Sing" },
  { easy: "Hair", hard: "Trolls" },
  { easy: "Green", hard: "The Grinch" },
  { easy: "Bear", hard: "Paddington" },
  { easy: "Hedgehog", hard: "Sonic The Hedgehog" },
  { easy: "Brick", hard: "The Lego Movie" },
  { easy: "Video", hard: "Wreck It Ralph" },
  { easy: "Wizard", hard: "Harry Potter" },
  { easy: "Space", hard: "Star Wars" },
  { easy: "Hero", hard: "The Avengers" },
  { easy: "Spider", hard: "Spider Man" },
  { easy: "Bat", hard: "Batman" },
  { easy: "Iron", hard: "Iron Man" },
  { easy: "Hammer", hard: "Thor" },
  { easy: "Cat", hard: "Black Panther" },
  { easy: "Lasso", hard: "Wonder Woman" },
  { easy: "Mask", hard: "Deadpool" },
  { easy: "Dino", hard: "Jurassic Park" },
  { easy: "Pirate", hard: "Pirates Of The Caribbean" },
  { easy: "Code", hard: "The Matrix" },
  { easy: "Ship", hard: "Titanic" },
  { easy: "Blue", hard: "Avatar" },
  { easy: "Arrow", hard: "The Hunger Games" },
  { easy: "Vampire", hard: "Twilight" },
  { easy: "Ring", hard: "Lord Of The Rings" },
  { easy: "Ring", hard: "The Hobbit" },
  { easy: "Race", hard: "Fast And Furious" },
  { easy: "Robot", hard: "Transformers" },
  { easy: "Home", hard: "Home Alone" },
  { easy: "Jungle", hard: "Jumanji" },
  { easy: "Ghost", hard: "Ghostbusters" },
  { easy: "Alien", hard: "Men In Black" },
  { easy: "Island", hard: "Cast Away" },
  { easy: "Feather", hard: "Forrest Gump" },
  { easy: "Sword", hard: "Gladiator" },
  { easy: "Clown", hard: "The Dark Knight" },
  { easy: "Dream", hard: "Inception" },
  { easy: "Space", hard: "Interstellar" },
  { easy: "Clown", hard: "Joker" },
  { easy: "Dance", hard: "La La Land" },
  { easy: "Queen", hard: "Bohemian Rhapsody" },
  { easy: "Tiger", hard: "Life Of Pi" },
  { easy: "Desert", hard: "Mad Max" },
  { easy: "Pink", hard: "Barbie" },
  { easy: "Bomb", hard: "Oppenheimer" },
  { easy: "Jet", hard: "Top Gun" },
  { easy: "Circus", hard: "The Greatest Showman" },
  { easy: "Clown", hard: "It" },
  { easy: "Silence", hard: "A Quiet Place" },
  { easy: "Bug", hard: "A Bugs Life" },
  { easy: "Egg", hard: "Chicken Run" },
  { easy: "Snail", hard: "Turbo" },
  { easy: "Bird", hard: "Rio" },
  { easy: "Dragon", hard: "How To Train Your Dragon" },
  { easy: "Panda", hard: "Kung Fu Panda Two" },
  { easy: "Snow", hard: "Frozen Two" },
  { easy: "Emoji", hard: "The Emoji Movie" },
  { easy: "Dog", hard: "Bolt" },
  { easy: "Fish", hard: "Shark Tale" },
  { easy: "Bee", hard: "Bee Movie" },
  { easy: "Egg", hard: "The Boss Baby" },
  { easy: "Pig", hard: "Peppa Pig" },
  { easy: "Rabbit", hard: "Peter Rabbit" },
  { easy: "Duck", hard: "Migration" },
  { easy: "Robot", hard: "The Wild Robot" },
  { easy: "Boat", hard: "Moana Two" },
  { easy: "Web", hard: "Spider Verse" },
  { easy: "Racoon", hard: "Guardians Of The Galaxy" },
  { easy: "Snap", hard: "Infinity War" },
  { easy: "Doctor", hard: "Doctor Strange" },
  { easy: "Ant", hard: "Ant Man" },
  { easy: "Shield", hard: "Captain America" },
  { easy: "Hulk", hard: "The Incredible Hulk" },
  { easy: "Wolf", hard: "The Wolverine" },
  { easy: "Ape", hard: "Planet Of The Apes" },
  { easy: "Robot", hard: "Terminator" },
  { easy: "Alien", hard: "Independence Day" },
  { easy: "Wave", hard: "The Meg" },
  { easy: "Storm", hard: "Twister" },
  { easy: "Volcano", hard: "San Andreas" },
  { easy: "Boxer", hard: "Rocky" },
  { easy: "Boxer", hard: "Creed" },
  { easy: "Race", hard: "Ford V Ferrari" },
  { easy: "Maze", hard: "The Maze Runner" },
  { easy: "Train", hard: "Snowpiercer" },
  { easy: "Basement", hard: "Parasite" },
  { easy: "Door", hard: "Get Out" },
  { easy: "Mirror", hard: "Us" },
  { easy: "Doll", hard: "Annabelle" },
  { easy: "House", hard: "The Conjuring" },
  { easy: "Knife", hard: "Scream" },
  { easy: "Nun", hard: "The Nun" },
  { easy: "Clown", hard: "It Chapter Two" },
  { easy: "Boat", hard: "Life Of Pi" },
  { easy: "Music", hard: "A Star Is Born" },
  { easy: "Chess", hard: "The Queens Gambit" },
  { easy: "Sand", hard: "Dune" },
  { easy: "Worm", hard: "Dune Part Two" },
  { easy: "Money", hard: "The Wolf Of Wall Street" },
  { easy: "Slum", hard: "Slumdog Millionaire" },
  { easy: "Space", hard: "Gravity" },
  { easy: "War", hard: "Dunkirk" },
  { easy: "War", hard: "Nineteen Seventeen" },
  { easy: "Knife", hard: "Knives Out" },
  { easy: "Rich", hard: "Crazy Rich Asians" },
  { easy: "Bagel", hard: "Everything Everywhere All At Once" },
  { easy: "Doll", hard: "M Three Gan" },
  { easy: "Bear", hard: "Cocaine Bear" },
  { easy: "Mario", hard: "The Super Mario Movie" },
  { easy: "Cat", hard: "Puss In Boots" },
  { easy: "Panda", hard: "Kung Fu Panda Four" },
  { easy: "Toy", hard: "Toy Story Four" },
  { easy: "Car", hard: "Cars Three" },
  { easy: "Fish", hard: "Finding Dory" },
  { easy: "Family", hard: "The Incredibles Two" },
  { easy: "Sheep", hard: "Shaun The Sheep" },
  { easy: "Gnome", hard: "Gnomeo And Juliet" },
  { easy: "Angry", hard: "The Angry Birds Movie" },
  { easy: "Lego", hard: "The Lego Batman Movie" },
  { easy: "Dog", hard: "A Dogs Purpose" },
  { easy: "Horse", hard: "Spirit" },
  { easy: "Deer", hard: "Bambi" },
  { easy: "Elephant", hard: "Dumbo" },
  { easy: "Jungle", hard: "The Jungle Book" },
  { easy: "Genie", hard: "Aladdin" },
  { easy: "Mermaid", hard: "The Little Mermaid" },
  { easy: "Beast", hard: "Beauty And The Beast" },
  { easy: "Clock", hard: "Hugo" },
  { easy: "Robot", hard: "Real Steel" },
  { easy: "Egg", hard: "Rango" },
];

export const MOVIE_CARDS: WordCard[] = unique(M);
