import type { WordCard } from "./types";
import { build } from "./gen";

// Movies: the hard 3-point answer is a famous film (1990s onward). The easy
// 1-point word is a word taken *from the title* so it satisfies containment —
// one-word titles (Frozen, Shrek) can't be used and are left out.
export const MOVIE_CARDS: WordCard[] = build([
  { easy: "Toy", hard: "Toy Story" },
  { easy: "Lion", hard: "The Lion King" },
  { easy: "Star", hard: "A Star Is Born" },
  { easy: "Star", hard: "Star Wars" },
  { easy: "Spider", hard: "Spider Man" },
  { easy: "Iron", hard: "Iron Man" },
  { easy: "Ant", hard: "Ant Man" },
  { easy: "Panther", hard: "Black Panther" },
  { easy: "Knight", hard: "The Dark Knight" },
  { easy: "Home", hard: "Home Alone" },
  { easy: "Black", hard: "Men In Black" },
  { easy: "Jungle", hard: "The Jungle Book" },
  { easy: "Panda", hard: "Kung Fu Panda" },
  { easy: "Ice", hard: "Ice Age" },
  { easy: "Nemo", hard: "Finding Nemo" },
  { easy: "Harry", hard: "Harry Potter" },
  { easy: "Galaxy", hard: "Guardians Of The Galaxy" },
  { easy: "Captain", hard: "Captain America" },
  { easy: "Doctor", hard: "Doctor Strange" },
  { easy: "Wonder", hard: "Wonder Woman" },
  { easy: "Park", hard: "Jurassic Park" },
  { easy: "Pirates", hard: "Pirates Of The Caribbean" },
  { easy: "Hunger", hard: "The Hunger Games" },
  { easy: "Maze", hard: "The Maze Runner" },
  { easy: "Wall", hard: "Wall E" },
  { easy: "Bugs", hard: "A Bugs Life" },
  { easy: "Dragon", hard: "How To Train Your Dragon" },
  { easy: "Monsters", hard: "Monsters Inc" },
  { easy: "Space", hard: "Space Jam" },
  { easy: "Night", hard: "Night At The Museum" },
  { easy: "Mario", hard: "The Super Mario Movie" },
  { easy: "Robot", hard: "The Wild Robot" },
  { easy: "Place", hard: "A Quiet Place" },
  { easy: "Knives", hard: "Knives Out" },
  { easy: "Rich", hard: "Crazy Rich Asians" },
  { easy: "Gun", hard: "Top Gun" },
  { easy: "Mad", hard: "Mad Max" },
  { easy: "Lego", hard: "The Lego Movie" },
  { easy: "Lord", hard: "The Lord Of The Rings" },
  { easy: "Fast", hard: "Fast And Furious" },
  { easy: "Kong", hard: "King Kong" },
  { easy: "War", hard: "World War Z" },
  { easy: "John", hard: "John Wick" },
  { easy: "Angry", hard: "The Angry Birds Movie" },
  { easy: "Hedgehog", hard: "Sonic The Hedgehog" },
  { easy: "Beast", hard: "Beauty And The Beast" },
  { easy: "Mermaid", hard: "The Little Mermaid" },
  { easy: "Wreck", hard: "Wreck It Ralph" },
]);
