import type { WordCard } from "./types";
import { unique } from "./gen";

// Sunny Singapore: local food, places, culture and slang. The easy 1-point
// word is a plain English hint; the hard 3-point answer is the Singaporean
// thing. Curated for authenticity rather than padded to a fixed count.

const SG: WordCard[] = [
  // Food & drink
  { easy: "Rice", hard: "Chicken Rice" },
  { easy: "Crab", hard: "Chilli Crab" },
  { easy: "Noodle", hard: "Laksa" },
  { easy: "Noodle", hard: "Char Kway Teow" },
  { easy: "Noodle", hard: "Hokkien Mee" },
  { easy: "Noodle", hard: "Wanton Mee" },
  { easy: "Noodle", hard: "Bak Chor Mee" },
  { easy: "Pork", hard: "Bak Kut Teh" },
  { easy: "Skewer", hard: "Satay Stick" },
  { easy: "Bread", hard: "Roti Prata" },
  { easy: "Rice", hard: "Nasi Lemak" },
  { easy: "Rice", hard: "Duck Rice" },
  { easy: "Rice", hard: "Nasi Briyani" },
  { easy: "Toast", hard: "Kaya Toast" },
  { easy: "Coffee", hard: "Kopi O" },
  { easy: "Tea", hard: "Teh Tarik" },
  { easy: "Ice", hard: "Ice Kacang" },
  { easy: "Ice", hard: "Chendol" },
  { easy: "Fruit", hard: "King Durian" },
  { easy: "Curry", hard: "Fish Head Curry" },
  { easy: "Cake", hard: "Fried Carrot Cake" },
  { easy: "Salad", hard: "Fruit Rojak" },
  { easy: "Roll", hard: "Popiah Roll" },
  { easy: "Puff", hard: "Curry Puff" },
  { easy: "Chicken", hard: "Hainanese Chicken" },
  { easy: "Milk", hard: "Milo Dinosaur" },
  { easy: "Drink", hard: "Bandung Drink" },
  { easy: "Ball", hard: "Fish Ball" },
  { easy: "Cake", hard: "Otah Otah" },
  { easy: "Jam", hard: "Kaya Jam" },
  { easy: "Noodle", hard: "Prawn Mee" },
  { easy: "Porridge", hard: "Frog Porridge" },
  { easy: "Noodle", hard: "Fried Bee Hoon" },
  { easy: "Chilli", hard: "Sambal Chilli" },
  { easy: "Egg", hard: "Soft Boiled Egg" },
  { easy: "Pancake", hard: "Min Jiang Kueh" },
  { easy: "Bun", hard: "Char Siew Bao" },
  { easy: "Dumpling", hard: "Xiao Long Bao" },
  { easy: "Stingray", hard: "Sambal Stingray" },
  { easy: "Toast", hard: "French Toast" },
  { easy: "Cendol", hard: "Red Bean Ice" },
  { easy: "Bean", hard: "Tau Huay" },
  { easy: "Sugar", hard: "Sugar Cane Juice" },
  { easy: "Chicken", hard: "Chicken Satay" },
  { easy: "Prawn", hard: "Cereal Prawn" },
  { easy: "Pork", hard: "Char Siew" },
  { easy: "Soup", hard: "Bak Kut Teh Soup" },
  { easy: "Noodle", hard: "Mee Goreng" },

  // Places & landmarks
  { easy: "Bay", hard: "Marina Bay" },
  { easy: "Lion", hard: "Merlion Statue" },
  { easy: "Island", hard: "Sentosa Island" },
  { easy: "Road", hard: "Orchard Road" },
  { easy: "Garden", hard: "Gardens By The Bay" },
  { easy: "Wheel", hard: "Singapore Flyer" },
  { easy: "Town", hard: "China Town" },
  { easy: "India", hard: "Little India" },
  { easy: "Quay", hard: "Clarke Quay" },
  { easy: "Beach", hard: "East Coast Park" },
  { easy: "Plane", hard: "Changi Airport" },
  { easy: "Waterfall", hard: "Jewel Waterfall" },
  { easy: "Hill", hard: "Bukit Timah" },
  { easy: "Theatre", hard: "The Esplanade" },
  { easy: "Hotel", hard: "Raffles Hotel" },
  { easy: "Flat", hard: "HDB Flat" },
  { easy: "Train", hard: "MRT Train" },
  { easy: "Food", hard: "Hawker Centre" },
  { easy: "Deck", hard: "Void Deck" },
  { easy: "Village", hard: "Old Kampong" },
  { easy: "Garden", hard: "Botanic Gardens" },
  { easy: "Safari", hard: "Night Safari" },
  { easy: "Zoo", hard: "Singapore Zoo" },
  { easy: "Studio", hard: "Universal Studios" },
  { easy: "Tree", hard: "Supertree Grove" },
  { easy: "Bird", hard: "Jurong Bird Park" },
  { easy: "Casino", hard: "Marina Bay Sands" },
  { easy: "Bridge", hard: "Helix Bridge" },
  { easy: "Fountain", hard: "Fountain Of Wealth" },
  { easy: "Temple", hard: "Buddha Tooth Temple" },
  { easy: "Mosque", hard: "Sultan Mosque" },
  { easy: "River", hard: "Singapore River" },
  { easy: "Street", hard: "Haji Lane" },
  { easy: "Market", hard: "Tekka Market" },
  { easy: "Mall", hard: "Ion Orchard" },
  { easy: "Park", hard: "Fort Canning" },
  { easy: "Reservoir", hard: "MacRitchie Reservoir" },
  { easy: "Beach", hard: "Palawan Beach" },
  { easy: "Cable", hard: "Cable Car" },
  { easy: "Tower", hard: "Pinnacle Duxton" },

  // Culture & slang
  { easy: "Reserve", hard: "Chope Seat" },
  { easy: "Eat", hard: "Makan Time" },
  { easy: "Auntie", hard: "Kopitiam Auntie" },
  { easy: "Uncle", hard: "Taxi Uncle" },
  { easy: "Packet", hard: "Red Packet" },
  { easy: "Year", hard: "Chinese New Year" },
  { easy: "Day", hard: "National Day" },
  { easy: "Queue", hard: "Kiasu Queue" },
  { easy: "Good", hard: "Very Shiok" },
  { easy: "Yes", hard: "Can Lah" },
  { easy: "Market", hard: "Wet Market" },
  { easy: "Slipper", hard: "Rubber Slipper" },
  { easy: "Card", hard: "Ez Link Card" },
  { easy: "Toll", hard: "ERP Gantry" },
  { easy: "Car", hard: "COE Car" },
  { easy: "Money", hard: "Ang Bao" },
  { easy: "Lantern", hard: "Mid Autumn Lantern" },
  { easy: "Dragon", hard: "Dragon Dance" },
  { easy: "Lion", hard: "Lion Dance" },
  { easy: "Fine", hard: "Fine City" },
  { easy: "Gum", hard: "No Chewing Gum" },
  { easy: "Study", hard: "Mug For Exam" },
  { easy: "Boss", hard: "Big Boss" },
  { easy: "Friend", hard: "Best Buddy" },
  { easy: "Tissue", hard: "Tissue Packet" },
  { easy: "Weather", hard: "Humid Weather" },
  { easy: "Rain", hard: "Afternoon Storm" },
  { easy: "Fan", hard: "Ceiling Fan" },
  { easy: "School", hard: "Tuition Class" },
  { easy: "Army", hard: "National Service" },
  { easy: "Festival", hard: "Hari Raya" },
  { easy: "Festival", hard: "Deepavali Lights" },
  { easy: "Language", hard: "Singlish Talk" },
  { easy: "Kite", hard: "Kite Flying" },
];

export const SINGAPORE_CARDS: WordCard[] = unique(SG);
