import type { WordCard } from "./types";
import { build } from "./gen";

// Songs: the hard 3-point answer is a famous song (1990s onward). The easy
// 1-point word is a word taken *from the title* (containment) — one-word titles
// (Happy, Umbrella, Firework) can't be used and are left out.
export const SONG_CARDS: WordCard[] = build([
  { easy: "Shark", hard: "Baby Shark" },
  { easy: "Road", hard: "Old Town Road" },
  { easy: "Deep", hard: "Rolling In The Deep" },
  { easy: "Guy", hard: "Bad Guy" },
  { easy: "Funk", hard: "Uptown Funk" },
  { easy: "Space", hard: "Blank Space" },
  { easy: "Single", hard: "Single Ladies" },
  { easy: "Face", hard: "Poker Face" },
  { easy: "Romance", hard: "Bad Romance" },
  { easy: "Dance", hard: "Just Dance" },
  { easy: "Teen", hard: "Smells Like Teen Spirit" },
  { easy: "Stars", hard: "Counting Stars" },
  { easy: "Girls", hard: "Girls Like You" },
  { easy: "Sugar", hard: "Watermelon Sugar" },
  { easy: "Lights", hard: "Blinding Lights" },
  { easy: "Party", hard: "Party In The Usa" },
  { easy: "Blood", hard: "Bad Blood" },
  { easy: "Time", hard: "Baby One More Time" },
  { easy: "Stop", hard: "Cant Stop The Feeling" },
  { easy: "World", hard: "A Whole New World" },
  { easy: "Circle", hard: "Circle Of Life" },
  { easy: "Summer", hard: "Cruel Summer" },
  { easy: "Kill", hard: "Kill Bill" },
  { easy: "Habits", hard: "Bad Habits" },
  { easy: "Cold", hard: "Cold Heart" },
  { easy: "Heat", hard: "Heat Waves" },
  { easy: "Just", hard: "Something Just Like This" },
  { easy: "Loud", hard: "Thinking Out Loud" },
  { easy: "Castle", hard: "Castle On The Hill" },
  { easy: "Purple", hard: "Purple Rain" },
  { easy: "Prayer", hard: "Livin On A Prayer" },
  { easy: "Sweet", hard: "Sweet Child O Mine" },
  { easy: "Rocket", hard: "Rocket Man" },
  { easy: "Rain", hard: "Set Fire To The Rain" },
  { easy: "Sky", hard: "A Sky Full Of Stars" },
  { easy: "Baby", hard: "Ice Ice Baby" },
  { easy: "Story", hard: "Love Story" },
  { easy: "Style", hard: "Gangnam Style" },
  { easy: "Shape", hard: "Shape Of You" },
  { easy: "Shake", hard: "Shake It Off" },
  { easy: "Hero", hard: "Anti Hero" },
  { easy: "Dreams", hard: "Wildest Dreams" },
  { easy: "Church", hard: "Take Me To Church" },
  { easy: "Feeling", hard: "I Gotta Feeling" },
  { easy: "Call", hard: "Call Me Maybe" },
  { easy: "Moves", hard: "Moves Like Jagger" },
  { easy: "Lucky", hard: "Get Lucky" },
  { easy: "Kicks", hard: "Pumped Up Kicks" },
  { easy: "Lines", hard: "Blurred Lines" },
  { easy: "Lie", hard: "Hips Dont Lie" },
  { easy: "Ball", hard: "Wrecking Ball" },
  { easy: "Horse", hard: "Dark Horse" },
  { easy: "Bling", hard: "Hotline Bling" },
  { easy: "Plan", hard: "Gods Plan" },
  { easy: "Dance", hard: "One Dance" },
  { easy: "Monkey", hard: "Dance Monkey" },
  { easy: "Easy", hard: "Easy On Me" },
  { easy: "Sign", hard: "Sign Of The Times" },
  { easy: "Truth", hard: "Truth Hurts" },
  { easy: "Magic", hard: "24k Magic" },
  { easy: "Marry", hard: "Marry You" },
  { easy: "Heaven", hard: "Locked Out Of Heaven" },
  { easy: "Rules", hard: "New Rules" },
  { easy: "Start", hard: "Dont Start Now" },
  { easy: "Heart", hard: "Break My Heart" },
  { easy: "Water", hard: "Cold Water" },
  { easy: "Wild", hard: "Wild Thoughts" },
  { easy: "Hopes", hard: "High Hopes" },
  { easy: "Kiss", hard: "Kiss Me More" },
  { easy: "Calm", hard: "Calm Down" },
  { easy: "Night", hard: "Last Night" },
  { easy: "Red", hard: "Paint The Town Red" },
  { easy: "Ocean", hard: "Ocean Eyes" },
  { easy: "Wake", hard: "Wake Me Up" },
  { easy: "Lean", hard: "Lean On" },
  { easy: "Cheap", hard: "Cheap Thrills" },
  { easy: "Name", hard: "Say My Name" },
  { easy: "Class", hard: "First Class" },
  { easy: "Crazy", hard: "Crazy In Love" },
  { easy: "State", hard: "Empire State Of Mind" },
  { easy: "Young", hard: "We Are Young" },
  { easy: "Love", hard: "Love Yourself" },
  { easy: "Mean", hard: "What Do You Mean" },
]);
