import type { WordCard } from "./types";
import { build } from "./gen";

// Songs: the hard 3-point answer is a famous song (1990s onward). The easy
// 1-point word is a word taken *from the title* (containment) — one-word titles
// (Happy, Umbrella, Firework) can't be used and are left out.
export const SONG_CARDS: WordCard[] = build([
  { easy: "Shark", hard: "Baby Shark" },
  { easy: "Road", hard: "Old Town Road" },
  { easy: "Deep", hard: "Rolling In The Deep" },
  { easy: "Guy", hard: "Bad Guy" },
  { easy: "Funk", hard: "Uptown Funk" },
  { easy: "Space", hard: "Blank Space" },
  { easy: "Single", hard: "Single Ladies" },
  { easy: "Face", hard: "Poker Face" },
  { easy: "Romance", hard: "Bad Romance" },
  { easy: "Dance", hard: "Just Dance" },
  { easy: "Teen", hard: "Smells Like Teen Spirit" },
  { easy: "Stars", hard: "Counting Stars" },
  { easy: "Girls", hard: "Girls Like You" },
  { easy: "Sugar", hard: "Watermelon Sugar" },
  { easy: "Lights", hard: "Blinding Lights" },
  { easy: "Party", hard: "Party In The Usa" },
  { easy: "Blood", hard: "Bad Blood" },
  { easy: "Time", hard: "Baby One More Time" },
  { easy: "Stop", hard: "Cant Stop The Feeling" },
  { easy: "World", hard: "A Whole New World" },
  { easy: "Circle", hard: "Circle Of Life" },
  { easy: "Summer", hard: "Cruel Summer" },
  { easy: "Kill", hard: "Kill Bill" },
  { easy: "Habits", hard: "Bad Habits" },
  { easy: "Cold", hard: "Cold Heart" },
  { easy: "Heat", hard: "Heat Waves" },
  { easy: "Just", hard: "Something Just Like This" },
  { easy: "Loud", hard: "Thinking Out Loud" },
  { easy: "Castle", hard: "Castle On The Hill" },
  { easy: "Purple", hard: "Purple Rain" },
  { easy: "Prayer", hard: "Livin On A Prayer" },
  { easy: "Sweet", hard: "Sweet Child O Mine" },
  { easy: "Rocket", hard: "Rocket Man" },
  { easy: "Rain", hard: "Set Fire To The Rain" },
  { easy: "Sky", hard: "A Sky Full Of Stars" },
  { easy: "Baby", hard: "Ice Ice Baby" },
  { easy: "Story", hard: "Love Story" },
  { easy: "Style", hard: "Gangnam Style" },
]);
