import type { WordCard } from "./types";
import { unique } from "./gen";

// Songs: the hard 3-point answer is a famous song from the 1990s onward. The
// easy 1-point word is a simple thing linked to the title. Curated for
// recognisability rather than padded to a fixed count.

const S: WordCard[] = [
  { easy: "Shark", hard: "Baby Shark" },
  { easy: "Horse", hard: "Old Town Road" },
  { easy: "Heart", hard: "Shape Of You" },
  { easy: "Deep", hard: "Rolling In The Deep" },
  { easy: "Phone", hard: "Hello" },
  { easy: "Bad", hard: "Bad Guy" },
  { easy: "Funk", hard: "Uptown Funk" },
  { easy: "Smile", hard: "Happy" },
  { easy: "Shake", hard: "Shake It Off" },
  { easy: "Space", hard: "Blank Space" },
  { easy: "Rain", hard: "Umbrella" },
  { easy: "Ring", hard: "Single Ladies" },
  { easy: "Spark", hard: "Firework" },
  { easy: "Lion", hard: "Roar" },
  { easy: "Card", hard: "Poker Face" },
  { easy: "Love", hard: "Bad Romance" },
  { easy: "Dance", hard: "Just Dance" },
  { easy: "Poison", hard: "Toxic" },
  { easy: "Baby", hard: "Baby One More Time" },
  { easy: "Spice", hard: "Wannabe" },
  { easy: "Wall", hard: "Wonderwall" },
  { easy: "Teen", hard: "Smells Like Teen Spirit" },
  { easy: "Faith", hard: "Believer" },
  { easy: "Storm", hard: "Thunder" },
  { easy: "Glow", hard: "Radioactive" },
  { easy: "Star", hard: "Counting Stars" },
  { easy: "Sweet", hard: "Sugar" },
  { easy: "Girl", hard: "Girls Like You" },
  { easy: "Memory", hard: "Memories" },
  { easy: "Float", hard: "Levitating" },
  { easy: "Melon", hard: "Watermelon Sugar" },
  { easy: "Past", hard: "As It Was" },
  { easy: "Light", hard: "Blinding Lights" },
  { easy: "Peach", hard: "Peaches" },
  { easy: "Boom", hard: "Dynamite" },
  { easy: "Butter", hard: "Butter" },
  { easy: "Slow", hard: "Despacito" },
  { easy: "Dance", hard: "Gangnam Style" },
  { easy: "Party", hard: "Party Rock Anthem" },
  { easy: "Phone", hard: "Payphone" },
  { easy: "Maybe", hard: "Call Me Maybe" },
  { easy: "Sorry", hard: "Sorry" },
  { easy: "Mirror", hard: "Love Yourself" },
  { easy: "Baby", hard: "Baby" },
  { easy: "Perfect", hard: "Perfect" },
  { easy: "Photo", hard: "Photograph" },
  { easy: "Loud", hard: "Thinking Out Loud" },
  { easy: "Castle", hard: "Castle On The Hill" },
  { easy: "City", hard: "Havana" },
  { easy: "Duet", hard: "Senorita" },
  { easy: "Cheap", hard: "Cheap Thrills" },
  { easy: "Swing", hard: "Chandelier" },
  { easy: "Metal", hard: "Titanium" },
  { easy: "Ball", hard: "Wrecking Ball" },
  { easy: "Flag", hard: "Party In The Usa" },
  { easy: "Gem", hard: "Diamonds" },
  { easy: "Work", hard: "Work" },
  { easy: "Love", hard: "We Found Love" },
  { easy: "Snow", hard: "Let It Go" },
  { easy: "Feel", hard: "Cant Stop The Feeling" },
  { easy: "Try", hard: "Try Everything" },
  { easy: "World", hard: "A Whole New World" },
  { easy: "Life", hard: "Circle Of Life" },
  { easy: "Zombie", hard: "Zombie" },
  { easy: "Scrub", hard: "No Scrubs" },
  { easy: "Dance", hard: "Macarena" },
  { easy: "Doll", hard: "Barbie Girl" },
  { easy: "Back", hard: "I Want It That Way" },
  { easy: "Bye", hard: "Bye Bye Bye" },
  { easy: "Bottle", hard: "Genie In A Bottle" },
  { easy: "Roof", hard: "Hot In Herre" },
  { easy: "Milk", hard: "Milkshake" },
  { easy: "Crazy", hard: "Crazy In Love" },
  { easy: "Hips", hard: "Hips Dont Lie" },
  { easy: "Umbrella", hard: "Since U Been Gone" },
  { easy: "Fire", hard: "Sex On Fire" },
  { easy: "Viva", hard: "Viva La Vida" },
  { easy: "Yellow", hard: "Yellow" },
  { easy: "Fix", hard: "Fix You" },
  { easy: "Sky", hard: "Sky Full Of Stars" },
  { easy: "Feel", hard: "Feel Good Inc" },
  { easy: "Seven", hard: "Seven Nation Army" },
  { easy: "Boulevard", hard: "Boulevard Of Broken Dreams" },
  { easy: "Numb", hard: "Numb" },
  { easy: "Crawl", hard: "Crawling" },
  { easy: "Rock", hard: "It Is My Life" },
  { easy: "Prayer", hard: "Livin On A Prayer" },
  { easy: "Hey", hard: "Hey There Delilah" },
  { easy: "Sun", hard: "Here Comes The Sun" },
  { easy: "Fire", hard: "Firework" },
  { easy: "Royal", hard: "Royals" },
  { easy: "Halo", hard: "Halo" },
  { easy: "Grenade", hard: "Grenade" },
  { easy: "Rain", hard: "Purple Rain" },
  { easy: "Money", hard: "Money" },
  { easy: "Star", hard: "Shooting Star" },
  { easy: "Fire", hard: "This Girl Is On Fire" },
  { easy: "Titanium", hard: "Titanium" },
  { easy: "Radio", hard: "Radio Ga Ga" },
  { easy: "Rocket", hard: "Rocket Man" },
  { easy: "Sweet", hard: "Sweet Child O Mine" },
  { easy: "Roses", hard: "Kiss From A Rose" },
  { easy: "Angel", hard: "Angels" },
  { easy: "River", hard: "The River" },
  { easy: "Ocean", hard: "Ocean Eyes" },
  { easy: "Bury", hard: "Bury A Friend" },
  { easy: "Guy", hard: "When The Party Is Over" },
  { easy: "Drive", hard: "Drivers License" },
  { easy: "Good", hard: "Good For You" },
  { easy: "Sour", hard: "Vampire" },
  { easy: "Save", hard: "Save Your Tears" },
  { easy: "Star", hard: "Starboy" },
  { easy: "Weekend", hard: "The Hills" },
  { easy: "Closer", hard: "Closer" },
  { easy: "Song", hard: "Something Just Like This" },
  { easy: "Wolf", hard: "Wolves" },
  { easy: "Sun", hard: "Sunflower" },
  { easy: "Circle", hard: "Circles" },
  { easy: "Rock", hard: "Rockstar" },
  { easy: "Toes", hard: "Butterfly" },
  { easy: "Dragon", hard: "Enemy" },
  { easy: "Heat", hard: "Heat Waves" },
  { easy: "Stay", hard: "Stay" },
  { easy: "Ghost", hard: "Ghost" },
  { easy: "Habit", hard: "Bad Habits" },
  { easy: "Cold", hard: "Cold Heart" },
  { easy: "Flower", hard: "Flowers" },
  { easy: "Kill", hard: "Kill Bill" },
  { easy: "Cruel", hard: "Cruel Summer" },
  { easy: "Snooze", hard: "Snooze" },
  { easy: "Paint", hard: "Paint The Town Red" },
  { easy: "Bird", hard: "Blackbird" },
  { easy: "Fever", hard: "Night Fever" },
];

export const SONG_CARDS: WordCard[] = unique(S);
