import type { WordCard } from "./types";

export type WordSet = {
  id: string;
  name: string;
  emoji: string;
  blurb: string;
  cards: WordCard[];
};

// In Poetry for Neanderthals the "caveman" twist is the *mechanic* — you may
// only clue using single-syllable words — not the cards. So the cards here are
// ordinary modern words and phrases. Each card has a simple one-point word and
// a harder three-point term (usually a compound or short phrase).

const EVERYDAY: WordCard[] = [
  { easy: "Dog", hard: "Hot Dog" },
  { easy: "Cat", hard: "Copy Cat" },
  { easy: "Ball", hard: "Disco Ball" },
  { easy: "Star", hard: "Movie Star" },
  { easy: "Book", hard: "Note Book" },
  { easy: "Chair", hard: "Wheel Chair" },
  { easy: "Door", hard: "Trap Door" },
  { easy: "Clock", hard: "Alarm Clock" },
  { easy: "Box", hard: "Music Box" },
  { easy: "Fish", hard: "Gold Fish" },
  { easy: "Bird", hard: "Bird Bath" },
  { easy: "Tree", hard: "Family Tree" },
  { easy: "Rock", hard: "Rock Band" },
  { easy: "Snow", hard: "Snow Man" },
  { easy: "Fire", hard: "Camp Fire" },
  { easy: "Sun", hard: "Sun Burn" },
  { easy: "Moon", hard: "Full Moon" },
  { easy: "Wind", hard: "Wind Mill" },
  { easy: "Sand", hard: "Sand Castle" },
  { easy: "Rain", hard: "Acid Rain" },
  { easy: "Hand", hard: "Hand Shake" },
  { easy: "Foot", hard: "Foot Ball" },
  { easy: "Eye", hard: "Eye Ball" },
  { easy: "Head", hard: "Head Ache" },
  { easy: "Face", hard: "Face Paint" },
  { easy: "Nose", hard: "Runny Nose" },
  { easy: "Ear", hard: "Ear Ring" },
  { easy: "Hair", hard: "Hair Cut" },
  { easy: "Tooth", hard: "Sweet Tooth" },
  { easy: "Bone", hard: "Funny Bone" },
  { easy: "Heart", hard: "Broken Heart" },
  { easy: "Milk", hard: "Milk Carton" },
  { easy: "Egg", hard: "Egg Roll" },
  { easy: "Bread", hard: "Ginger Bread" },
  { easy: "Corn", hard: "Pop Corn" },
  { easy: "Bean", hard: "Jelly Bean" },
  { easy: "Salt", hard: "Salt Shaker" },
  { easy: "Cup", hard: "Cup Board" },
  { easy: "Pot", hard: "Jack Pot" },
  { easy: "Pan", hard: "Frying Pan" },
  { easy: "Plate", hard: "License Plate" },
  { easy: "Fork", hard: "Tuning Fork" },
  { easy: "Spoon", hard: "Wooden Spoon" },
  { easy: "Knife", hard: "Pocket Knife" },
  { easy: "Glass", hard: "Wine Glass" },
  { easy: "Grass", hard: "Grass Hopper" },
  { easy: "Leaf", hard: "Maple Leaf" },
  { easy: "Wood", hard: "Fire Wood" },
  { easy: "Stone", hard: "Stepping Stone" },
  { easy: "Cloud", hard: "Storm Cloud" },
  { easy: "Wave", hard: "Heat Wave" },
  { easy: "Pool", hard: "Swimming Pool" },
  { easy: "Road", hard: "Road Trip" },
  { easy: "Bridge", hard: "Draw Bridge" },
  { easy: "Wall", hard: "Brick Wall" },
  { easy: "Roof", hard: "Roof Top" },
  { easy: "Floor", hard: "Dance Floor" },
  { easy: "Bed", hard: "Bunk Bed" },
  { easy: "Lamp", hard: "Lava Lamp" },
  { easy: "Desk", hard: "Front Desk" },
  { easy: "Shelf", hard: "Book Shelf" },
  { easy: "Mirror", hard: "Rear View Mirror" },
  { easy: "Towel", hard: "Beach Towel" },
  { easy: "Soap", hard: "Soap Opera" },
  { easy: "Brush", hard: "Paint Brush" },
  { easy: "Comb", hard: "Honey Comb" },
  { easy: "Broom", hard: "Broom Stick" },
  { easy: "Rope", hard: "Jump Rope" },
  { easy: "Chain", hard: "Key Chain" },
  { easy: "Nail", hard: "Finger Nail" },
  { easy: "Screw", hard: "Screw Driver" },
  { easy: "Saw", hard: "See Saw" },
  { easy: "Tape", hard: "Duct Tape" },
  { easy: "Wheel", hard: "Ferris Wheel" },
  { easy: "Bell", hard: "Door Bell" },
  { easy: "Drum", hard: "Drum Stick" },
  { easy: "Coin", hard: "Gold Coin" },
  { easy: "Ring", hard: "Boxing Ring" },
  { easy: "Watch", hard: "Stop Watch" },
  { easy: "Belt", hard: "Seat Belt" },
  { easy: "Sock", hard: "Sock Puppet" },
  { easy: "Shoe", hard: "Horse Shoe" },
  { easy: "Hat", hard: "Top Hat" },
  { easy: "Coat", hard: "Rain Coat" },
  { easy: "Glove", hard: "Boxing Glove" },
  { easy: "Scarf", hard: "Winter Scarf" },
  { easy: "Shirt", hard: "Sweat Shirt" },
  { easy: "Bag", hard: "Sleeping Bag" },
  { easy: "Pen", hard: "Pig Pen" },
  { easy: "Card", hard: "Credit Card" },
  { easy: "Stamp", hard: "Rubber Stamp" },
  { easy: "Flag", hard: "Red Flag" },
  { easy: "Kite", hard: "Box Kite" },
  { easy: "Wire", hard: "Live Wire" },
  { easy: "Bulb", hard: "Light Bulb" },
  { easy: "Fan", hard: "Ceiling Fan" },
  { easy: "Plug", hard: "Spark Plug" },
  { easy: "Switch", hard: "Light Switch" },
  { easy: "Fence", hard: "Picket Fence" },
  { easy: "Gate", hard: "Boarding Gate" },
  { easy: "Barn", hard: "Barn Yard" },
  { easy: "Well", hard: "Wishing Well" },
  { easy: "Farm", hard: "Ant Farm" },
  { easy: "Field", hard: "Corn Field" },
  { easy: "Hill", hard: "Ant Hill" },
  { easy: "Cave", hard: "Bat Cave" },
  { easy: "River", hard: "River Bank" },
  { easy: "Ocean", hard: "Ocean Liner" },
  { easy: "Island", hard: "Desert Island" },
  { easy: "Mountain", hard: "Mountain Bike" },
  { easy: "Forest", hard: "Rain Forest" },
  { easy: "Desert", hard: "Desert Storm" },
  { easy: "Valley", hard: "Death Valley" },
  { easy: "Sky", hard: "Sky Scraper" },
  { easy: "Rainbow", hard: "Double Rainbow" },
  { easy: "Thunder", hard: "Thunder Storm" },
  { easy: "Lightning", hard: "Lightning Bolt" },
  { easy: "Ice", hard: "Ice Berg" },
  { easy: "Frost", hard: "Jack Frost" },
  { easy: "Smoke", hard: "Smoke Alarm" },
  { easy: "Dust", hard: "Dust Bunny" },
  { easy: "Bubble", hard: "Bubble Bath" },
  { easy: "Shadow", hard: "Eye Shadow" },
  { easy: "Ghost", hard: "Ghost Town" },
  { easy: "Web", hard: "Spider Web" },
  { easy: "Key", hard: "Key Note" },
  { easy: "Ladder", hard: "Step Ladder" },
  { easy: "Print", hard: "Foot Print" },
  { easy: "Nap", hard: "Cat Nap" },
];

const PARTY_PACK: WordCard[] = [
  { easy: "Dance", hard: "Break Dance" },
  { easy: "Sing", hard: "Sing Along" },
  { easy: "Laugh", hard: "Belly Laugh" },
  { easy: "Cry", hard: "Cry Baby" },
  { easy: "Sleep", hard: "Sleep Over" },
  { easy: "Dream", hard: "Day Dream" },
  { easy: "Kiss", hard: "French Kiss" },
  { easy: "Hug", hard: "Bear Hug" },
  { easy: "Wink", hard: "Sly Wink" },
  { easy: "Clap", hard: "Slow Clap" },
  { easy: "Jump", hard: "Jumping Jack" },
  { easy: "Run", hard: "Home Run" },
  { easy: "Hop", hard: "Hip Hop" },
  { easy: "Kick", hard: "Drop Kick" },
  { easy: "Punch", hard: "Fruit Punch" },
  { easy: "Throw", hard: "Throw Pillow" },
  { easy: "Catch", hard: "Catch Phrase" },
  { easy: "Slide", hard: "Water Slide" },
  { easy: "Swing", hard: "Mood Swing" },
  { easy: "Roll", hard: "Barrel Roll" },
  { easy: "Spin", hard: "Spin The Bottle" },
  { easy: "Flip", hard: "Flip Flop" },
  { easy: "Race", hard: "Rat Race" },
  { easy: "Dive", hard: "Swan Dive" },
  { easy: "Whistle", hard: "Dog Whistle" },
  { easy: "Giggle", hard: "Giggle Fit" },
  { easy: "Tickle", hard: "Tickle Fight" },
  { easy: "Wrestle", hard: "Arm Wrestle" },
  { easy: "Tag", hard: "Freeze Tag" },
  { easy: "Hide", hard: "Hide And Seek" },
  { easy: "Chase", hard: "Goose Chase" },
  { easy: "Bounce", hard: "Bounce House" },
  { easy: "Twirl", hard: "Baton Twirl" },
  { easy: "Cheer", hard: "Cheer Leader" },
  { easy: "Pose", hard: "Yoga Pose" },
  { easy: "Stretch", hard: "Home Stretch" },
  { easy: "Sprint", hard: "Wind Sprint" },
  { easy: "Party", hard: "Block Party" },
  { easy: "Balloon", hard: "Water Balloon" },
  { easy: "Candle", hard: "Birthday Candle" },
  { easy: "Gift", hard: "Gift Wrap" },
  { easy: "Game", hard: "Board Game" },
  { easy: "Toy", hard: "Toy Store" },
  { easy: "Doll", hard: "Rag Doll" },
  { easy: "Prize", hard: "Grand Prize" },
  { easy: "Trick", hard: "Magic Trick" },
  { easy: "Joke", hard: "Inside Joke" },
  { easy: "Prank", hard: "April Fool" },
  { easy: "Clown", hard: "Class Clown" },
  { easy: "Circus", hard: "Circus Tent" },
  { easy: "Magic", hard: "Magic Wand" },
  { easy: "Puzzle", hard: "Jigsaw Puzzle" },
  { easy: "Dice", hard: "Rolling Dice" },
  { easy: "Costume", hard: "Costume Party" },
  { easy: "Mask", hard: "Ski Mask" },
  { easy: "Wig", hard: "Curly Wig" },
  { easy: "Glitter", hard: "Gold Glitter" },
  { easy: "Disco", hard: "Disco Fever" },
  { easy: "Crown", hard: "Flower Crown" },
  { easy: "Whisper", hard: "Soft Whisper" },
  { easy: "Shout", hard: "Shout Out" },
  { easy: "Scream", hard: "Primal Scream" },
  { easy: "Boo", hard: "Boo Hoo" },
  { easy: "Buzz", hard: "Buzz Word" },
  { easy: "Cheers", hard: "Three Cheers" },
  { easy: "Bet", hard: "Sure Bet" },
  { easy: "Dare", hard: "Truth Or Dare" },
  { easy: "Charade", hard: "Play Charade" },
  { easy: "Bingo", hard: "Bingo Night" },
  { easy: "Poker", hard: "Poker Face" },
  { easy: "Chess", hard: "Chess Match" },
  { easy: "Dart", hard: "Dart Board" },
  { easy: "Golf", hard: "Mini Golf" },
  { easy: "Tennis", hard: "Table Tennis" },
  { easy: "Ping", hard: "Ping Pong" },
  { easy: "Team", hard: "Team Spirit" },
  { easy: "Goal", hard: "Field Goal" },
  { easy: "Win", hard: "Win Streak" },
  { easy: "Lose", hard: "Sore Loser" },
  { easy: "Tie", hard: "Tie Game" },
  { easy: "Trophy", hard: "Trophy Case" },
  { easy: "Medal", hard: "Gold Medal" },
  { easy: "Coach", hard: "Head Coach" },
  { easy: "Crowd", hard: "Crowd Surf" },
  { easy: "Chant", hard: "War Chant" },
  { easy: "Firework", hard: "Fire Works" },
  { easy: "Parade", hard: "Parade Float" },
  { easy: "Feast", hard: "Royal Feast" },
  { easy: "Ticket", hard: "Golden Ticket" },
  { easy: "Line", hard: "Finish Line" },
  { easy: "Award", hard: "Award Show" },
  { easy: "Fart", hard: "Whoopee Cushion" },
  { easy: "Burp", hard: "Baby Burp" },
  { easy: "Sneeze", hard: "Sneeze Attack" },
  { easy: "Itch", hard: "Seven Year Itch" },
  { easy: "Sweat", hard: "Sweat Band" },
  { easy: "Blush", hard: "Cheek Blush" },
  { easy: "Frown", hard: "Big Frown" },
  { easy: "Smile", hard: "Cheese Smile" },
  { easy: "Grin", hard: "Wide Grin" },
  { easy: "Snooze", hard: "Snooze Button" },
  { easy: "Wish", hard: "Birthday Wish" },
  { easy: "Guest", hard: "Party Guest" },
  { easy: "Host", hard: "Game Host" },
  { easy: "Invite", hard: "Wedding Invite" },
  { easy: "Limbo", hard: "Limbo Stick" },
  { easy: "Hula", hard: "Hula Hoop" },
  { easy: "Skate", hard: "Roller Skate" },
  { easy: "Board", hard: "Skate Board" },
  { easy: "Scooter", hard: "Kick Scooter" },
  { easy: "Kart", hard: "Go Kart" },
  { easy: "Bumper", hard: "Bumper Car" },
  { easy: "Coaster", hard: "Roller Coaster" },
  { easy: "Booth", hard: "Photo Booth" },
  { easy: "Fair", hard: "County Fair" },
  { easy: "Cotton", hard: "Cotton Candy" },
  { easy: "Mascot", hard: "Sports Mascot" },
  { easy: "Streamer", hard: "Paper Streamer" },
  { easy: "Ribbon", hard: "Blue Ribbon" },
  { easy: "Bow", hard: "Take A Bow" },
  { easy: "Spell", hard: "Spelling Bee" },
  { easy: "Genie", hard: "Genie Lamp" },
  { easy: "Fortune", hard: "Fortune Teller" },
  { easy: "Luck", hard: "Good Luck" },
  { easy: "Trend", hard: "Party Trend" },
  { easy: "Boogie", hard: "Boogie Down" },
  { easy: "Pinata", hard: "Party Pinata" },
];

const SCREEN_TIME: WordCard[] = [
  { easy: "Screen", hard: "Big Screen" },
  { easy: "Phone", hard: "Smart Phone" },
  { easy: "Text", hard: "Text Message" },
  { easy: "App", hard: "App Store" },
  { easy: "Link", hard: "Web Link" },
  { easy: "Mouse", hard: "Computer Mouse" },
  { easy: "Click", hard: "Double Click" },
  { easy: "Type", hard: "Type Cast" },
  { easy: "Scroll", hard: "Scroll Bar" },
  { easy: "Swipe", hard: "Swipe Right" },
  { easy: "Post", hard: "Blog Post" },
  { easy: "Like", hard: "Like Button" },
  { easy: "Share", hard: "Screen Share" },
  { easy: "Stream", hard: "Live Stream" },
  { easy: "Play", hard: "Play Button" },
  { easy: "Level", hard: "Boss Level" },
  { easy: "Boss", hard: "Final Boss" },
  { easy: "Score", hard: "High Score" },
  { easy: "Save", hard: "Save Point" },
  { easy: "Quest", hard: "Side Quest" },
  { easy: "Lag", hard: "Server Lag" },
  { easy: "Pixel", hard: "Pixel Art" },
  { easy: "Avatar", hard: "Cartoon Avatar" },
  { easy: "Emoji", hard: "Smile Emoji" },
  { easy: "Filter", hard: "Photo Filter" },
  { easy: "Binge", hard: "Binge Watch" },
  { easy: "Remote", hard: "Remote Control" },
  { easy: "Mute", hard: "Mute Button" },
  { easy: "Zoom", hard: "Zoom Call" },
  { easy: "Chat", hard: "Group Chat" },
  { easy: "Meme", hard: "Meme Lord" },
  { easy: "Troll", hard: "Internet Troll" },
  { easy: "Blog", hard: "Travel Blog" },
  { easy: "Vlog", hard: "Daily Vlog" },
  { easy: "Wifi", hard: "Free Wifi" },
  { easy: "Byte", hard: "Mega Byte" },
  { easy: "Code", hard: "Cheat Code" },
  { easy: "Hack", hard: "Life Hack" },
  { easy: "Tweet", hard: "Viral Tweet" },
  { easy: "Feed", hard: "News Feed" },
  { easy: "Reel", hard: "Insta Reel" },
  { easy: "Spam", hard: "Spam Folder" },
  { easy: "Virus", hard: "Computer Virus" },
  { easy: "Robot", hard: "Robot Arm" },
  { easy: "Laptop", hard: "Gaming Laptop" },
  { easy: "Tablet", hard: "Drawing Tablet" },
  { easy: "Channel", hard: "News Channel" },
  { easy: "Show", hard: "Talk Show" },
  { easy: "Movie", hard: "Horror Movie" },
  { easy: "Film", hard: "Silent Film" },
  { easy: "Actor", hard: "Voice Actor" },
  { easy: "Scene", hard: "Love Scene" },
  { easy: "Script", hard: "Script Writer" },
  { easy: "Stage", hard: "Center Stage" },
  { easy: "Fame", hard: "Hall Of Fame" },
  { easy: "Oscar", hard: "Oscar Night" },
  { easy: "Trailer", hard: "Trailer Park" },
  { easy: "Cartoon", hard: "Saturday Cartoon" },
  { easy: "Comic", hard: "Comic Strip" },
  { easy: "Hero", hard: "Super Hero" },
  { easy: "Villain", hard: "Evil Villain" },
  { easy: "Alien", hard: "Space Alien" },
  { easy: "Space", hard: "Space Ship" },
  { easy: "Rocket", hard: "Rocket Launch" },
  { easy: "Laser", hard: "Laser Beam" },
  { easy: "Ninja", hard: "Ninja Move" },
  { easy: "Zombie", hard: "Zombie Apocalypse" },
  { easy: "Wizard", hard: "Tech Wizard" },
  { easy: "Dragon", hard: "Baby Dragon" },
  { easy: "Knight", hard: "Dark Knight" },
  { easy: "Sword", hard: "Sword Fight" },
  { easy: "Shield", hard: "Wind Shield" },
  { easy: "Map", hard: "Treasure Map" },
  { easy: "Gem", hard: "Rare Gem" },
  { easy: "Loot", hard: "Loot Crate" },
  { easy: "Player", hard: "Player One" },
  { easy: "Console", hard: "Game Console" },
  { easy: "Joystick", hard: "Joy Stick" },
  { easy: "Arcade", hard: "Arcade Room" },
  { easy: "Pad", hard: "Game Pad" },
  { easy: "Sound", hard: "Sound Track" },
  { easy: "Beat", hard: "Beat Box" },
  { easy: "Bass", hard: "Bass Drop" },
  { easy: "Volume", hard: "Max Volume" },
  { easy: "Speaker", hard: "Loud Speaker" },
  { easy: "Headset", hard: "Gaming Headset" },
  { easy: "Charger", hard: "Fast Charger" },
  { easy: "Battery", hard: "Low Battery" },
  { easy: "Selfie", hard: "Selfie Stick" },
  { easy: "Camera", hard: "Spy Camera" },
  { easy: "Photo", hard: "Photo Bomb" },
  { easy: "Video", hard: "Music Video" },
  { easy: "Music", hard: "Pop Music" },
  { easy: "Song", hard: "Theme Song" },
  { easy: "Playlist", hard: "Party Playlist" },
  { easy: "Podcast", hard: "Crime Podcast" },
  { easy: "Radio", hard: "Car Radio" },
  { easy: "News", hard: "Fake News" },
  { easy: "Signal", hard: "Weak Signal" },
  { easy: "Login", hard: "Guest Login" },
  { easy: "Password", hard: "Weak Password" },
  { easy: "Email", hard: "Junk Email" },
  { easy: "Inbox", hard: "Full Inbox" },
  { easy: "Folder", hard: "File Folder" },
  { easy: "File", hard: "Zip File" },
  { easy: "Drive", hard: "Hard Drive" },
  { easy: "Disk", hard: "Floppy Disk" },
  { easy: "Blueprint", hard: "Blue Print" },
  { easy: "Search", hard: "Search Bar" },
  { easy: "Tab", hard: "Open Tab" },
  { easy: "Bug", hard: "Software Bug" },
  { easy: "Glitch", hard: "Game Glitch" },
  { easy: "Patch", hard: "Update Patch" },
  { easy: "Update", hard: "System Update" },
  { easy: "Ad", hard: "Pop Up Ad" },
  { easy: "Pop", hard: "K Pop" },
  { easy: "Viral", hard: "Gone Viral" },
  { easy: "Clip", hard: "News Clip" },
  { easy: "Frame", hard: "Freeze Frame" },
  { easy: "Loop", hard: "Time Loop" },
  { easy: "Bot", hard: "Chat Bot" },
  { easy: "Drone", hard: "Camera Drone" },
  { easy: "Cursor", hard: "Blinking Cursor" },
  { easy: "Cable", hard: "Charge Cable" },
  { easy: "Sequel", hard: "Movie Sequel" },
];

const MUNCHIES: WordCard[] = [
  { easy: "Cake", hard: "Birthday Cake" },
  { easy: "Pie", hard: "Pumpkin Pie" },
  { easy: "Taco", hard: "Taco Truck" },
  { easy: "Pizza", hard: "Pepperoni Pizza" },
  { easy: "Burger", hard: "Cheese Burger" },
  { easy: "Fries", hard: "French Fries" },
  { easy: "Soup", hard: "Chicken Soup" },
  { easy: "Rice", hard: "Fried Rice" },
  { easy: "Noodle", hard: "Pool Noodle" },
  { easy: "Pasta", hard: "Angel Hair" },
  { easy: "Cheese", hard: "Grilled Cheese" },
  { easy: "Butter", hard: "Peanut Butter" },
  { easy: "Sauce", hard: "Hot Sauce" },
  { easy: "Candy", hard: "Candy Cane" },
  { easy: "Gum", hard: "Bubble Gum" },
  { easy: "Mint", hard: "Mint Chip" },
  { easy: "Cookie", hard: "Fortune Cookie" },
  { easy: "Donut", hard: "Donut Hole" },
  { easy: "Waffle", hard: "Belgian Waffle" },
  { easy: "Pancake", hard: "Pancake Stack" },
  { easy: "Bacon", hard: "Bacon Bits" },
  { easy: "Ham", hard: "Ham Sandwich" },
  { easy: "Steak", hard: "T Bone Steak" },
  { easy: "Chicken", hard: "Fried Chicken" },
  { easy: "Turkey", hard: "Cold Turkey" },
  { easy: "Shrimp", hard: "Shrimp Cocktail" },
  { easy: "Crab", hard: "Crab Cake" },
  { easy: "Lobster", hard: "Lobster Roll" },
  { easy: "Sushi", hard: "Sushi Roll" },
  { easy: "Bagel", hard: "Bagel Bites" },
  { easy: "Toast", hard: "French Toast" },
  { easy: "Jam", hard: "Jam Jar" },
  { easy: "Honey", hard: "Honey Bee" },
  { easy: "Syrup", hard: "Maple Syrup" },
  { easy: "Sugar", hard: "Brown Sugar" },
  { easy: "Spice", hard: "Pumpkin Spice" },
  { easy: "Pepper", hard: "Bell Pepper" },
  { easy: "Garlic", hard: "Garlic Bread" },
  { easy: "Onion", hard: "Onion Ring" },
  { easy: "Potato", hard: "Mashed Potato" },
  { easy: "Tomato", hard: "Cherry Tomato" },
  { easy: "Carrot", hard: "Baby Carrot" },
  { easy: "Pea", hard: "Sweet Pea" },
  { easy: "Kale", hard: "Kale Chip" },
  { easy: "Pickle", hard: "Dill Pickle" },
  { easy: "Olive", hard: "Olive Oil" },
  { easy: "Lemon", hard: "Lemon Drop" },
  { easy: "Lime", hard: "Lime Soda" },
  { easy: "Grape", hard: "Sour Grape" },
  { easy: "Apple", hard: "Candy Apple" },
  { easy: "Pear", hard: "Prickly Pear" },
  { easy: "Peach", hard: "Peach Fuzz" },
  { easy: "Plum", hard: "Sugar Plum" },
  { easy: "Berry", hard: "Blue Berry" },
  { easy: "Cherry", hard: "Cherry Bomb" },
  { easy: "Melon", hard: "Water Melon" },
  { easy: "Banana", hard: "Banana Split" },
  { easy: "Mango", hard: "Mango Salsa" },
  { easy: "Kiwi", hard: "Kiwi Fruit" },
  { easy: "Coconut", hard: "Coconut Milk" },
  { easy: "Coffee", hard: "Iced Coffee" },
  { easy: "Latte", hard: "Latte Art" },
  { easy: "Soda", hard: "Cream Soda" },
  { easy: "Juice", hard: "Orange Juice" },
  { easy: "Smoothie", hard: "Fruit Smoothie" },
  { easy: "Shake", hard: "Milk Shake" },
  { easy: "Wine", hard: "Red Wine" },
  { easy: "Beer", hard: "Root Beer" },
  { easy: "Cola", hard: "Diet Cola" },
  { easy: "Water", hard: "Sparkling Water" },
  { easy: "Tea", hard: "Sweet Tea" },
  { easy: "Chip", hard: "Chocolate Chip" },
  { easy: "Cream", hard: "Whipped Cream" },
  { easy: "Nacho", hard: "Nacho Cheese" },
  { easy: "Salad", hard: "Caesar Salad" },
  { easy: "Bowl", hard: "Cereal Bowl" },
  { easy: "Cereal", hard: "Corn Flakes" },
  { easy: "Yogurt", hard: "Frozen Yogurt" },
  { easy: "Dumpling", hard: "Soup Dumpling" },
  { easy: "Rib", hard: "Baby Back Rib" },
  { easy: "Wing", hard: "Buffalo Wing" },
  { easy: "Dip", hard: "Onion Dip" },
  { easy: "Meatball", hard: "Meatball Sub" },
  { easy: "Sundae", hard: "Ice Cream Sundae" },
  { easy: "Mustard", hard: "Honey Mustard" },
  { easy: "Ketchup", hard: "Tomato Ketchup" },
  { easy: "Cinnamon", hard: "Cinnamon Roll" },
  { easy: "Muffin", hard: "English Muffin" },
  { easy: "Pretzel", hard: "Soft Pretzel" },
  { easy: "Almond", hard: "Almond Milk" },
  { easy: "Jelly", hard: "Grape Jelly" },
  { easy: "Brownie", hard: "Fudge Brownie" },
  { easy: "Fudge", hard: "Hot Fudge" },
  { easy: "Caramel", hard: "Caramel Apple" },
  { easy: "Marshmallow", hard: "Toasted Marshmallow" },
  { easy: "Cracker", hard: "Graham Cracker" },
  { easy: "Broth", hard: "Bone Broth" },
  { easy: "Stew", hard: "Beef Stew" },
  { easy: "Chili", hard: "Chili Dog" },
  { easy: "Curry", hard: "Curry Powder" },
  { easy: "Wrap", hard: "Veggie Wrap" },
  { easy: "Combo", hard: "Combo Meal" },
  { easy: "Meal", hard: "Happy Meal" },
  { easy: "Snack", hard: "Snack Bar" },
  { easy: "Buffet", hard: "Buffet Line" },
  { easy: "Diner", hard: "Corner Diner" },
  { easy: "Menu", hard: "Kids Menu" },
  { easy: "Tip", hard: "Big Tip" },
  { easy: "Chef", hard: "Head Chef" },
  { easy: "Grill", hard: "BBQ Grill" },
  { easy: "Popcorn", hard: "Kettle Corn" },
  { easy: "Cupcake", hard: "Cup Cake" },
  { easy: "Sprinkle", hard: "Rainbow Sprinkle" },
];

const DOWN_UNDER: WordCard[] = [
  { easy: "Roo", hard: "Boxing Kangaroo" },
  { easy: "Joey", hard: "Baby Joey" },
  { easy: "Koala", hard: "Sleepy Koala" },
  { easy: "Emu", hard: "Giant Emu" },
  { easy: "Dingo", hard: "Wild Dingo" },
  { easy: "Croc", hard: "Salt Water Croc" },
  { easy: "Shark", hard: "Great White Shark" },
  { easy: "Snake", hard: "Brown Snake" },
  { easy: "Spider", hard: "Huntsman Spider" },
  { easy: "Wombat", hard: "Chubby Wombat" },
  { easy: "Platypus", hard: "Duck Billed Platypus" },
  { easy: "Echidna", hard: "Spiny Echidna" },
  { easy: "Quokka", hard: "Smiling Quokka" },
  { easy: "Possum", hard: "Ring Tail Possum" },
  { easy: "Bat", hard: "Fruit Bat" },
  { easy: "Fly", hard: "Bush Fly" },
  { easy: "Parrot", hard: "White Cockatoo" },
  { easy: "Bird", hard: "Laughing Kookaburra" },
  { easy: "Wallaby", hard: "Rock Wallaby" },
  { easy: "Pie", hard: "Meat Pie" },
  { easy: "Snag", hard: "Sausage Sizzle" },
  { easy: "Chook", hard: "Roast Chook" },
  { easy: "Prawn", hard: "Prawn On The Barbie" },
  { easy: "Roll", hard: "Sausage Roll" },
  { easy: "Toast", hard: "Vegemite Toast" },
  { easy: "Tim Tam", hard: "Choc Tim Tam" },
  { easy: "Cake", hard: "Coconut Lamington" },
  { easy: "Pav", hard: "Fruit Pavlova" },
  { easy: "Bread", hard: "Fairy Bread" },
  { easy: "Bikkie", hard: "Anzac Bikkie" },
  { easy: "Chips", hard: "Hot Chips" },
  { easy: "Mate", hard: "G'day Mate" },
  { easy: "Thongs", hard: "Rubber Thongs" },
  { easy: "Ute", hard: "Farm Ute" },
  { easy: "Esky", hard: "Cold Esky" },
  { easy: "Footy", hard: "Aussie Footy" },
  { easy: "Barbie", hard: "Backyard Barbie" },
  { easy: "Arvo", hard: "Lazy Arvo" },
  { easy: "Servo", hard: "Petrol Servo" },
  { easy: "Sunnies", hard: "Cool Sunnies" },
  { easy: "Doona", hard: "Warm Doona" },
  { easy: "Dunny", hard: "Outback Dunny" },
  { easy: "Tinnie", hard: "Cold Tinnie" },
  { easy: "Bang", hard: "Wooden Boomerang" },
  { easy: "Pipe", hard: "Droning Didgeridoo" },
  { easy: "Reef", hard: "Great Barrier Reef" },
  { easy: "Rock", hard: "Uluru Rock" },
  { easy: "Bush", hard: "The Outback" },
  { easy: "Beach", hard: "Bondi Beach" },
  { easy: "Surf", hard: "Surf Life Saver" },
  { easy: "Tree", hard: "Gum Tree" },
  { easy: "Star", hard: "Southern Cross" },
  { easy: "Hat", hard: "Cork Hat" },
  { easy: "House", hard: "Opera House" },
];

export const WORD_SETS: WordSet[] = [
  {
    id: "everyday",
    name: "Everyday",
    emoji: "🎯",
    blurb: "A mixed bag of everyday words",
    cards: EVERYDAY,
  },
  {
    id: "party-pack",
    name: "Party Pack",
    emoji: "🎉",
    blurb: "Games, moves and party mayhem",
    cards: PARTY_PACK,
  },
  {
    id: "screen-time",
    name: "Screen Time",
    emoji: "📺",
    blurb: "Movies, games, tech and the web",
    cards: SCREEN_TIME,
  },
  {
    id: "munchies",
    name: "Munchies",
    emoji: "🍕",
    blurb: "Food, drink and tasty treats",
    cards: MUNCHIES,
  },
  {
    id: "down-under",
    name: "Down Under",
    emoji: "🦘",
    blurb: "Roos, servo snacks and the outback",
    cards: DOWN_UNDER,
  },
];

export function wordSetById(id: string): WordSet {
  return WORD_SETS.find((s) => s.id === id) ?? WORD_SETS[0];
}
